### ISSUE TITLE
Review outputted schema for errors

### ISSUE THREAD

**Issue by michael-cannon** [easydigitaldownloads/Easy-Digital-Downloads#1623]
[product snippets don't generate](http://www.google.com/webmasters/tools/richsnippets?q=http%3A%2F%2Faihr.us%2Fstore%2F).

[Product entries themselves are broken](http://www.google.com/webmasters/tools/richsnippets?q=http%3A%2F%2Faihr.us%2Fproducts%2Ftestimonials-widget-premium-wordpress-plugin%2F)

`Item 
type:	http://schema.org/product
property:	
aggregaterating:	
Item 1
Error: Missing required field "name (fn)".`

[idea reference](https://github.com/michael-cannon/testimonials-widget/blob/master/testimonials-widget.php#L1745)

**Comment by cklosowski** [comment]
Looks like our variable pricing is working but single price items are missing a name field:

![image](https://cloud.githubusercontent.com/assets/1390124/6447421/0f742bce-c0c7-11e4-89cb-a827a8131ccf.png)

**Comment by cklosowski** [comment]
I think I've got this nailed down, the issue lies in the nesting of our `itemtype` attribute. The `name` was on the `the_title` and the `scope & description` were on `the_content`, so the name was outside of the scope.

I'm moving to create a `span` on `loop_start` and closing it on `loop_end`, that declares the scope so that it's nested as:
```
scope
    name
    description
/scope
```
This is currently validating on the Google Testing Tool for both single and variable price
![image](https://cloud.githubusercontent.com/assets/1390124/6448090/4c51833e-c0cc-11e4-8836-f33887fb4a97.png)

**Comment by alvarokid** [comment]
Anyone still having issues with this "Missing required field name"? I get an error when there is a list of downloads (archive pages, etc.), but not in single pages.

**Comment by cklosowski** [comment]
@alvarokid It's possible that we've fixed this in the 3.0 branch that we're currently working on here:
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5240

This branch isn't ready for product yet, but once we hit beta we can look into it to make sure it's still not an issue.

**Comment by alvarokid** [comment]
Ok, thank you. Any ETA for 3.0? Unless it is a beta? Thank you.
