### ISSUE TITLE
Add better "grouping" for Extensions tab

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#1960]
Once there are a lot of extensions activated, the Extensions tab can get really crowded. We should look into a way of separating each extension into it's own group and then maybe hiding the fields for all extensions until a link for an extension is clicked. On click, the related extension's settings would be shown. 

Woo did this pretty well with their tabs-within-tabs settings.

**Comment by danieliser** [comment]
Most extensions use the edd_header_callback. What if you simply use the heading callback to close the table, create a new accordion heading and then open a new table? Effectively works immediately from looking at my extensions tab(15+ extensions enabled).

Its a bit hacky, but if you do that now and add a new callback say edd_accordian_section_callback that extensions could then begin migrating to it could definately work. To remove the empty table rows simply use a jQuery snippet.

The hacky part would purely be a holdover for the extensions to be able to migrate down the line, once they are all updated remove the hacks.

**Comment by danieliser** [comment]
I got it sectioned out ( no accordian JS ) pretty nicely with a couple small modifications. Still need to remove empty table rows but definitely an option.

**Comment by danieliser** [comment]
Alternativey set a new empty array $settings['extensions']['sections'] = array();

Then in your loop of the $settings['extensions'] array, call anything other than the sections sub array as you do now, then extensions can migrate to store their settings inside the sections sub array in the future. Show the sections first and then loop through the non sections below.

**Comment by pippinsplugins** [comment]
Great! Could you show an example of how you are setting up settings so far?

**Comment by danieliser** [comment]
Sure will create some feature branches and get a working test set up. My method would basically be a combination of ghost's above and a fallback for those who haven't updated their extensions yet.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by benjaminprojas** [comment]
I just pushed a PR to release/2.5 that implements the default WordPress method for adding in these settings section.  This is fully backwards compatible with the current plugins, but will allow for plugins to extend the individual sections.  In the plugin, you will need to update code as follows:

First, you will need to add a new function that registers the section:

```php
function eppe_add_settings_section( $sections ) {
  $sections['eppe'] = EDD_EPPE_PRODUCT_NAME;
  return $sections;
}
add_filter( 'edd_settings_sections_gateways', 'eppe_add_settings_section' );
```

Then you need to update your options using the new array key:

```php
function eppe_add_settings( $settings ) {
  $settings ['eppe'] = array( // key added here
    // options here
  );
  return array_merge( $settings, $eppe_settings );
}
add_filter( 'edd_settings_gateways', 'eppe_add_settings' );
```

Very simple.

**Comment by danieliser** [comment]
Very nice implementation.

**Comment by pippinsplugins** [comment]
Looks great @benjaminprojas 

It's tagged for 2.5, so we'll review it soon and see what else needs to be done.

**Comment by pippinsplugins** [comment]
Latest PR https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3829

**Comment by cklosowski** [comment]
PR #3829 has been merged into `feature/sub-sections` for testing.

**Comment by chriscct7** [comment]
![image](https://cloud.githubusercontent.com/assets/1324637/11410873/078b3f24-9399-11e5-8a36-b4bdb9669f53.png)

It'd be nice if those subsections were styled a bit more

**Comment by cklosowski** [comment]
I actually disagree, it would break normal from what us and other plugins are already doing for these:
Fraud Monitor:
![screen shot 2015-11-25 at 3 37 16 pm](https://cloud.githubusercontent.com/assets/1390124/11411136/80852bba-938a-11e5-90ad-af47574e09a2.png)

WooCommerce:
![screen shot 2015-11-25 at 3 37 11 pm](https://cloud.githubusercontent.com/assets/1390124/11411138/834bf496-938a-11e5-9a3a-2f98f59bbdfe.png)

**Comment by benjaminprojas** [comment]
I agree with @cklosowski. These subsections use the classes from WordPress core so it maintains consistency there.

**Comment by pippinsplugins** [comment]
Just for the sake of comparison, @chriscct7 do you have an example of the styles you'd like to see?

**Comment by chriscct7** [comment]
I mean its not perfectly what I was thinking of but like right now it looks like those are just "jump" links to something further down the already loaded page (like anchor links), and they're really small. Maybe put them in some sort of box with a white background and make the header for the page larger below it? I'm not really sure tbh but I think we could come up with something that makes the screen more consistent. One of the things I was noticing today is our UI is super inconsistent. In the customers screen, the tabs are on the right, yet on settings they're above, and because of that, to me, the little tiny links get lost when the tab starts with a header that draws your attention, skipping over the additional settings offered in the other subsections. I think it'd be interesting, as a sidenote, and soon as another ticket, if we moved the customer UI + the settings API to the same type of page, so that we have a consistent UI. Right now, I notice if I add a tab or two at the top it breaks a ton of the layout. If we moved both to something like https://cloud.githubusercontent.com/assets/870979/9839566/692da07e-5a3b-11e5-9746-4b6afa319c94.png the whole experience would be much more consistent, and decently styled.

We can say we're using WP core classes, and that's fine and should be encouraged, but WordPress core doesn't use tabs (unfortunately), they use a seperate menu item for each page. I think we should really look at how we can make the page look asthetically better. Right now, it sort of looks pretty boring.

Redux is a great counter example. Sure it might be super complicated, but one thing they do right is the experience looks and fees more alive. Yes we might not want to do like tab changing, but conditional logic for settings (yet another ticket coming soon) would be a nice feature. We could then have a Gateways Tab where when you turn on and off a gateway, all of the other options for that gateway are shown and hidden. For example, if taxes are off, does it make sense to show a ton of confusing tax settings when they won't be used? This could really help us simplify the experience, and let people get going faster.

Back to this page, I think what would be nice is moving to a system with side major tabs, like our customer page with text labels (for accessibility) like shown here: https://cloud.githubusercontent.com/assets/870979/9839566/692da07e-5a3b-11e5-9746-4b6afa319c94.png

and then if we implement conditional logic, do we really need new pages?

Just thoughts I had.

**Comment by chriscct7** [comment]
To follow up on side tabs like customer page, it makes adding alot more of those items (via extensions) easier since you don't have to worry about horizontal overflow. If our tools, settings, customers, and reports all used something like https://cloud.githubusercontent.com/assets/870979/9839566/692da07e-5a3b-11e5-9746-4b6afa319c94.png it'd make the whole experience a lot more connected. That's clearly not a 2.5 thing, but its something to think about.

**Comment by pippinsplugins** [comment]
While moving settings to one similar to the customers' UI has some definite merit, that is a much bigger change so I'd like to keep that as a separate discussion.

I will say that when I see these links at the top, I don't think of them as jump links. They've always felt like sections to me, though I can definitely see how they could get skipped over.

**Comment by pippinsplugins** [comment]
@cklosowski This is looking beautiful.

1. [ ] `Remove Data Uninstall` should be somewhere else. Not directly related to this issue, but the separation of settings has highlighted it. How about we move it to the `Misc` tab: https://cloudup.com/cJJIwJW79u4
2. [ ] Email settings are missing: https://cloudup.com/cKeZpYtybcO

Note: I'd like to have a major push to get all primary extensions owned by the core team updated with sub section support the same time as this goes out.

**Comment by cklosowski** [comment]
1) Fixed
2) No, there aren't any settings missing. I just compared against master. If it's the `from` and `name` fields, they are under the `Purchase Receipt` settings section, as they state they are for `purchase receipts`
3) Looking into it.

**Comment by benjaminprojas** [comment]
This is looking awesome @cklosowski, can't wait to see it in the wild!

**Comment by cklosowski** [comment]
@pippinsplugins take a look see if that fixes your notices. I added a new `wildcard` filter for the `tab & section` combination.

**Comment by pippinsplugins** [comment]
@cklosowski: `Fatal error: Can't use function return value in write context in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/easy-digital-downloads/includes/admin/settings/display-settings.php on line 33`

**Comment by cklosowski** [comment]
Ok. Will fix that in a bit.

**Comment by cklosowski** [comment]
@pippinsplugins that should fix the fatal error.

**Comment by SDavisMedia** [comment]
I love the grouping but one thing I noticed is that moving between the settings is very slow. Whether I click a main tab or a sub-section, it takes the better part of 10 seconds to load. I jumped back and forth between `master` and `feature/sub-sections` and it's like a toggle switch for speed.

**Comment by cklosowski** [comment]
@SDavisMedia do you see the same delay in `release/2.5`?

**Comment by SDavisMedia** [comment]
@cklosowski `release/2.5` is moving at the same speed as `master` for me.

**Comment by pippinsplugins** [comment]
@SDavisMedia I saw the slow performance earlier too: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3829#issuecomment-153233936

**Comment by benjaminprojas** [comment]
When @pippinsplugins had the issue before, I could never duplicate it.  If that helps at all... maybe it happens with additional plugins installed that I wasn't using? @cklosowski @SDavisMedia

**Comment by cklosowski** [comment]
I do'nt have many enabled, and I see a delay...but i'm digging

**Comment by pippinsplugins** [comment]
It's running fine for me right now. Definitely haven't a hard time reliably replicating the slowness.

**Comment by cklosowski** [comment]
Ok, there are some severe performance issues here, and it's due to the looping of the settings. I'm not sure how adding a single loop to this causes such an exponential increase in load times, but here's the time it took to run the foreach loop in `edd_register_settings()`:
```
release/2.5
0.130544900894
0.144529104233
0.12943315506
0.166022777557
0.148726940155
0.15305685997
0.142035961151
0.158468008041

feature/sub-sections
7.8086938858
6.6754219532
6.68370103836
5.96580386162
5.85934519768
5.84700298309
6.17121601105
6.01386499405
```

Need to figure out why this is so much less performant before we get this into `release/2.5`

**Comment by pippinsplugins** [comment]
Whoa, that's super severe. Good findings man.

**Comment by benjaminprojas** [comment]
Wow, crazy! I can try to look into this myself tonight as well (unless you beat me to it).

**Comment by cklosowski** [comment]
Ok, nailed it down. did 2 things to improve it.:
1) there were some left over variable assignments that ended up looping multiple times
2) Set the array of tabs/sections to a static so the apply_filters is ever only called once on all them.

With those two changes this is much more performant, matching `release/2.5`, please test it out and make sure though.

**Comment by benjaminprojas** [comment]
Awesome!

**Comment by pippinsplugins** [comment]
Found a bug that caused the `Extensions` tab to not work properly once a custom section was registered in an extension. Fixed with eda8d23

**Comment by pippinsplugins** [comment]
This has been merged into `release/2.5`

**Comment by mindctrl** [comment]
If taxes are enabled, you can't disable them. Unchecking the box and saving results in them still being enabled.

**Comment by mindctrl** [comment]
Same with "Display Tax Rate on Prices"... another checkbox.

**Comment by mindctrl** [comment]
Same with Enable Ajax on Misc tab.

**Comment by mindctrl** [comment]
So most/all checkboxes can be checked but not unchecked.

**Comment by pippinsplugins** [comment]
@cklosowski I've tracked this down to the `edd_settings_sanitize()` callback. It's looping through the registered settings sections now instead of looping through the settings within each section. Could you work on this today please?

**Comment by cklosowski** [comment]
Yep, I'll get that done today.

**Comment by pippinsplugins** [comment]
@mindctrl Could you give @cklosowski's PR a test?

**Comment by mindctrl** [comment]
Checkboxes from extensions that don't use sections yet can't be unchecked.

**Comment by pippinsplugins** [comment]
Example extension to test with?

**Comment by mindctrl** [comment]
I tested Content Restriction and Discounts Pro.

**Comment by pippinsplugins** [comment]
I just ran into a serious problem here.

Clicking save while on one of the sub sections completely wiped out the settings for a payment gateway extension.

**Comment by pippinsplugins** [comment]
Nevermind, #4072 solved it.

**Comment by pippinsplugins** [comment]
Scratch that, still happening.

**Comment by cklosowski** [comment]
@pippinsplugins @mindctrl Looking into the issues you're seeing.

**Comment by cklosowski** [comment]
Closing after some discussion with the team in Slack. We'll re-open if necessary.

**Comment by benjaminprojas** [comment]
@cklosowski mind sharing what the gist of the Slack discussion was about?

**Comment by cklosowski** [comment]
@BenjaminPRojas it was just them testing things out for me. We had a few filters not running for sanitization so saving checkboxes wast working for extensions not using subsections. Slack was just where we discussed as we tested.

**Comment by benjaminprojas** [comment]
@cklosowski thanks for the update! Good to know.  I appreciate the work you all have done on this!
