### ISSUE TITLE
Multiple types of taxes

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#2820]
Some countries, like particularly those in the EU, have different taxes depending on the type of good (like luxury ones). We should consider letting people add different type of tax levels, and selecting the appropriate one on the edit product page. 

Released: #2819. Furthers: #2805

As this will likely require a substantial overhaul (and lots of testing) of our taxes system, pegging 2.3

**Comment by bseddon** [comment]
This is functionality I added to our VAT extension and it was reasonably straight-forward to implement.  There are some specific requirements.  The EU has the idea of a rate types such as standard, reduced, super-reduced and parking.  However what is reduced in one country is not necessarily reduced in another.

So it is ideal to be able to create tax classes ('e-books' and 'software' say) to which a rate can be assigned for any country.  My extension treats the EDD tax rates set a an existing, built-in, class.  As noted above, the applicable class can be assigned tor each download.  

Usually, the standard rate applies but may be changed by a small number of countries.  For example, the e-books VAT rate for most EU countries is the standard rate (whatever that is) but in just three countries (Estonia, France and Luxembourg) a different rate applies.  So our extension assumes the standard rate (the EDD tax rate) for any additional tax class unless there is a value entered. This way only a small number of the values need to change and be maintained.  And it is obvious which are the oddballs.

It will also be necessary to assign to each rate, within each class, the applicable 'EU' name for the rate.  That is, have an extra drop down so the user is able to select, by country, the EU name.  This is necessary for the quarterly MOSS report.  Regardless of what a user calls the tax class, the name used on the MOSS report should be one of the prescribed rate types (standard, reduced, super reduced, etc).

Again, just using the EU rate types is not enough because the EU rate type for product A might be 'standard' in Italy but 'reduced' in Spain - even though the rate itself is the same.

**Comment by pippinsplugins** [comment]
Thanks for the feedback.

When we do this, we'll probably keep it pretty simple and straight forward and then allow for extensions like yours to handle more advanced requirements.

**Comment by chriscct7** [comment]
@easydigitaldownloads/core-devs  I think based on a lack of people really needing this, we should consider closing this out at least for now. I think realistically, the better thing to do here would be to keep the simple tax system we currently have and allow for it to be filtered to allow for more advanced use cases, as most people with more specific tax needs will likely be using an extension or a SaaS to do the tax rates.

**Comment by chriscct7** [comment]
Not sure why it's got it as a milestone change. It was already set to 2.9 a year ago

**Comment by pippinsplugins** [comment]
I agree with closing for now. We can re-open if additional demand shows up.
