### ISSUE TITLE
Download files don't work if outside /edd

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#285]
Currently download files fail to get delivered if the file is NOT in the /edd directory. While obviously it is best if files are stored here, user's should be able to use other folders if they wish, especially when they are uploading large files manually.

The problem has to do with how EDD converts a local file URL to a complete path.

**Comment by srsinfosystems** [comment]
We are using Amazon s3 extension with EDD plugin:
http://pix.toile-libre.org/upload/original/1518179551.png

So by this the flow is something like this:
1)Add new product form (frontend)
http://pix.toile-libre.org/upload/original/1518179786.png
--when you upload the file it is saved on the server in the uploads/edd folder
http://pix.toile-libre.org/upload/original/1518180001.png
--It is present on our server until the submit button is pressed to add new product.
http://pix.toile-libre.org/upload/original/1518180083.png
As you can see in the below screenshot: the files are removed from server. 
http://pix.toile-libre.org/upload/original/1518180159.png
New image URL is generated by plugin:
http://pix.toile-libre.org/upload/original/1518180269.png
So, in order to view the file uploaded, you need to check it on the amazon server.
