### ISSUE TITLE
_edd_log_price_id incorrectly being set to 0, causing exports to fail

### ISSUE THREAD

**Issue by bizzthemes** [easydigitaldownloads/Easy-Digital-Downloads#3020]
Export Customers in CSV is not working. Only exporting emails for all downloads is working.

**Comment by cklosowski** [comment]
Can you give some steps to replicate? Is it just the product specific exports that aren't working? I seem to be able to get a valid export when doing all of the `All Downloads``` options.

Do your products have variable pricing enabled? Just looking for exactly what isn't working. I've been able to get an export of customers from a specific product, but I'm seeing something odd with the different price options. Want to see if we're seeing the same thing.

**Comment by cklosowski** [comment]
Quick question, just to make sure, were any of your purchases made while in ```Test Mode```?

**Comment by bizzthemes** [comment]
It doesn't work for variable pricing options. I see it works for standard products without variations. No, all purchases were live, no Test mode.

Other notes, while we're at it:

1) By default, there should also be an option to export customers for product with all variations and not per variation only.

2) Products should also be sorted alphabetically, not by date as they're now.

**Comment by pippinsplugins** [comment]
I've replicated the bug.

**Comment by cklosowski** [comment]
Let's start with the actual bug and if I can get the "nice to haves" in, I will.

The main bug here is that the ```_edd_log_price_id``` post meta item is always being set to ```0```. We're going to have to do two things:
1. Fix the logging so that any new purchases log the correct price ID in the post meta for the ```edd_log``` entry
2. Write an upgrade routine that goes through all purchases and corrects this entry.

This is a pretty major bug actually, and I'm going to change the title of the issue to reflect the actual problem, not the symptom. @bizzthemes I'm going to create a separate issue for the enhancements to allow getting all price IDs or a single price ID and sorting the downloads.

Being that those are enhancements to the reporting page, and the actual issue you reported is a bad data issue (bug), they should be handled separate for speed of release.

**Comment by cklosowski** [comment]
Ok @pippinsplugins, I think this should do it.

I tested it out on my dev environment with 9500 payments, but only about 100 of those are in ```live``` mode so that's not an AMAZING stress test. We should push this on a staging of EDD site or something to see how it performs...

This includes getting the update done for all payments, accounts for payments with the mulit-price id purchase option enabled, as well as introduced resumed upgrades. This way if a store 'stalls' or hangs up, it's recorded the last step it was on, and will just replay from there.
