### ISSUE TITLE
Customer by Product export enhancements

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3025]
As suggested in the comments of #3020 by @bizzthemes, we should enhance the Customer Export when doing it for a specific product by:
1. Change to Chosen to avoid sort issue
2. Allowing an export of all price options in addition to a single price option.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Punting to 2.5 (the reports release).

**Comment by brashrebel** [comment]
Another very cool related feature that would be possible when switching to chosen's multi-select field would be the capability of selecting multiple downloads instead of only one. I believe the query args [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/reporting/export/class-batch-export-customers.php#L70) would need to be adjusted to accept an array instead of an integer but other than that, it would be simple I think.

The UI would be greatly improved and basically be the same as is currently in use for selecting downloads applicable to a discount code.

**Comment by pippinsplugins** [comment]
That would be excellent.

**Comment by cklosowski** [comment]
The problem with the multiselect, is it currently doesn't support the variable pricing, so it would only export all customers of the products selected, not the variable price levels.

Once #3175 is tackled it might be able to do that.

**Comment by cklosowski** [comment]
I'm going to merge this as is, once #3175 is completed, we can revisit further improvements. I don't think that is going to make 2.5 and I think this would be a great improvement to include for 2.5.
