### ISSUE TITLE
Add hidden field to settings API

### ISSUE THREAD

**Issue by evertiro** [easydigitaldownloads/easy-digital-downloads#3056]
The addition of a hidden field type to the settings API would be extremely useful for extensions (such as my GetResponse extension) that save API keys, allowing us to easily check on save for changes to the API key and clear transients so that users can access up-to-date API information without waiting for the transient to clear on its own. (Why do I suck at explaining things today?)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@ghost1227 Want to tackle this on?

**Comment by ghost1227** [comment]
already am

**Comment by ghost1227** [comment]
Ok... so adding a hidden field results in a tiny bug in which the Settings API still acknowledges it as a field, so we end up with a blank row, like so:

![screen shot 2015-02-04 at 11 37 45 am](https://cloud.githubusercontent.com/assets/36433/6045781/60f03fe8-ac62-11e4-9eb1-93d49b860d11.PNG)

I'm still researching, but the first thing that comes to mind is that rather than adding a true hidden field, we could add a 'hidden' parameter to the existing fields. If 'hidden' isn't passed in the options array, it does nothing. If it is, it appends the hidden field to the existing visible field. In this way, we don't get the extra row, but still have access to the hidden data for a given field.

Example:

```
/**
 * Text Callback
 *
 * Renders text fields.
 *
 * @since 1.0
 * @param array $args Arguments passed by the setting
 * @global $edd_options Array of all the EDD Options
 * @return void
 */
function edd_text_callback( $args ) {
    global $edd_options;

    if ( isset( $edd_options[ $args['id'] ] ) )
        $value = $edd_options[ $args['id'] ];
    else
        $value = isset( $args['std'] ) ? $args['std'] : '';
    
    $size = ( isset( $args['size'] ) && ! is_null( $args['size'] ) ) ? $args['size'] : 'regular';

    $html = '<input type="text" class="' . $size . '-text" id="edd_settings[' . $args['id'] . ']" name="edd_settings[' . $args['id'] . ']" value="' . esc_attr( stripslashes( $value ) ) . '"/>';
    $html .= '<label for="edd_settings[' . $args['id'] . ']"> ' . $args['desc'] . '</label>';

    if ( isset( $args['hidden'] ) )
        $html .= '<input type="hidden" id="edd_settings[' . $args['id'] . '][hidden]" name="edd_settings[' . $args['id'] . '][hidden]" value="' . esc_attr( stripslashes( $value ) ) . '" />';

    echo $html;
}
```

**Comment by chriscct7** [comment]
+1

**Comment by cklosowski** [comment]
So I know it's kind of a 'hack' but what if you just made sure to always register hidden ones at the bottom, it wouldn't solve the issue, but make it less apparent...?

**Comment by pippinsplugins** [comment]
@cklosowski With extensions registering settings, there's not really a good way to enforce that.

**Comment by pippinsplugins** [comment]
I'm not really opposed to supporting a hidden value on existing fields, but that seems like a different use case than a standard hidden field.

How about, instead, we just alter the API that renders the settings to add in a case for hidden fields?

**Comment by cklosowski** [comment]
@pippinsplugins hence the word hack. I know it's not a good answer. Was just stating a possible case.

**Comment by ghost1227** [comment]
@pippinsplugins Alter the API how? I've been digging but haven't found a way to do it. Since the actual fields are rendered by a WordPress core function, we can't really modify its behavior much. Hence, my suggestion regarding a hidden option for individual fields (since most all use cases for using a hidden field will have relevance to another visible field, that seemed safest).

**Comment by pippinsplugins** [comment]
@ghost1227 oh yeah . . .I forgot that the WP core functions set up the html.

**Comment by ghost1227** [comment]
lol

**Comment by ghost1227** [comment]
Any other suggestions? Or should I go ahead and implement my original suggestion?

**Comment by pippinsplugins** [comment]
@ghost1227 Try and get creative. I'm not really sure how we should handle this yet so I'd love to see possible options.

**Comment by spencerfinnell** [comment]
If you don't pass a label then the `<th>` isn't created and you could hide the `<td>` in the row if that's the first child element:

`tr > td:first-child { display: none; }`

https://core.trac.wordpress.org/browser/tags/4.1/src/wp-admin/includes/template.php#L1291

**Comment by pippinsplugins** [comment]
Oh hey, check that out. Nice catch @spencerfinnell !

**Comment by spencerfinnell** [comment]
Oh that's not entirely true. It still checks for `title` as a fallback. Back to the drawing board!

**Comment by ghost1227** [comment]
@spencerfinnell Nice try :stuck_out_tongue: I tried that too.

**Comment by ghost1227** [comment]
@pippinsplugins @spencerfinnell @cklosowski Any other bright ideas? I'm still stuck on my original idea...

**Comment by pippinsplugins** [comment]
Not yet, sorry.

**Comment by pippinsplugins** [comment]
If you need to get an update for an add-on out, just use an action for now.

**Comment by sunnyratilal** [comment]
PR: #6248 

The approach I've taken to solve this is to force a `hidden` class to be applied to the `<tr>` when WordPress is generating the HTML.  The rest is pretty standard.

**Comment by sunnyratilal** [comment]
Merged
