### ISSUE TITLE
Another rounding issue with product prices when prices are inclusive of tax

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3104]
We have an extra penny showing up due to rounding issues.

To replicate:

- Set tax rate to 20%
- Set prices inclusive of tax
- Create a Download with a price of 9.99
- Add item to the cart and select appropriate country / state to be charged 20% tax
- Final price should be 9.99 but is actually 10.00

![screen shot 2015-02-13 at 1 47 15 pm](https://cloud.githubusercontent.com/assets/1034109/6194129/ddee4bb8-b386-11e4-8855-c17cf343396f.png)

The issue was noticed via this [ticket](https://easydigitaldownloads.com/support/topic/price-calculated-incorrectly/).

**Comment by cklosowski** [comment]
I believe the issue lies in `edd_calculate_tax()`.

For a value of `9.99` it's returning that the tax amount should be `1.665`, which is then getting increased to `1.67` and then setting the `item_price` at the wrong amount putting us at `10.00` instead of `9.99`.

If we use the `edd_currency_decimal_filter()` function to take the decimal count for the shop, we'll get rid of this.

Does it seem right tot do the following before retuning from the `edd_calculate_tax` function?
```$tax = round( $tax, edd_currency_decimal_filter() );```

**Comment by pippinsplugins** [comment]
Yeah I think that is right

**Comment by cklosowski** [comment]
Ok verified sales record properly, and when sending to paypal that the amount is sent to them correctly as well.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@cklosowski I don't think the proposed changes in #3169 work actually. We used to round the taxes there, https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/ee46b2ca4e55e2f22d006844334eb1bb1c2dc615#diff-e1900e6f7d703ca91cbd7c62d0c28eee,  but it caused a problem when there are multiple items and quantities: #1881

**Comment by cklosowski** [comment]
Not sure where else we would round taxes...but in the tax calculation...but we can go back to the drawing board. This tells me we have some DEEP DEEP seeded issues with rounding that need to be resolved.

**Comment by pippinsplugins** [comment]
Oh I guarantee there are some deep, deep, deep issues with taxes. Welcome to my *favorite* API in EDD.

**Comment by chriscct7** [comment]
I think there's a very simple solution to this

All we need to do is when we calculate the item price exclusive of tax for use in the subtotal, instead of rounding it UP like we do now, we need to round in DOWN

Item price entered inclusive of tax: 19.95
Tax amount: 20%

Current:
    Subtotal: 16.625 rounded UP to 16.63 http://www.wolframalpha.com/input/?i=19.95%3D+x+*+1.2
    Tax:      3.326 rounded UP to 3.33 http://www.wolframalpha.com/input/?i=16.63+*+.2
    Total: 16.63+3.33 = 19.96 (too high)!

Proposed:
    Subtotal: 16.625 rounded DOWN to 16.62
    Tax:      3.326 rounded UP to 3.33
    Total: 16.62+3.33 = 19.95

Item price entered inclusive of tax: 19.95
Tax amount: 20%
Quantity = 2

Current:
    Subtotal: 33.25 (no rounding needed)
    Tax:      6.65 (no rounding needed)
    Total:    39.9 (no rounding needed)

Proposed:
    Subtotal: 33.25 (no rounding needed)
    Tax:      6.65 (no rounding needed)
    Total:    39.9 (no rounding needed)

**Comment by pippinsplugins** [comment]
Another report: https://easydigitaldownloads.com/support/topic/inclusive-taxes-rounding-up/

**Comment by Netzberufler** [comment]
I would change the function edd_get_cart_content_details() (again :D)

The function does use edd_get_cart_item_tax() to retrieve the tax and then use it to calculate the subtotal.
````
$tax        = edd_get_cart_item_tax( $item['id'], $item['options'], $subtotal - $discount );
if( edd_prices_include_tax() ) {
	$subtotal -= $tax;
}
````

Problem:
$tax = 1.665
$subtotal = 9.99 - 1.665 = 8.325

When the $details[$key] array is built both tax and subtotal are rounded to 1.67 and 8.33, which is one penny to much.

In order to fix that the $tax variable should be rounded first before the subtotal is calculated.
````
$tax        = edd_get_cart_item_tax( $item['id'], $item['options'], $subtotal - $discount );
if( edd_prices_include_tax() ) {
	$subtotal -= round( $tax, edd_currency_decimal_filter() );
}
````

As result:
$tax = 1.665
$subtotal = 9.99 - 1.67 (rounded tax) = 8.32

This can be combined with https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3165

**Comment by Netzberufler** [comment]
Btw: You can't round the tax in the tax function because it will distort subsequent results if you calculate them with rounded values.

For example: When you have 2 items with $9.99 and 20% tax you should get a tax of $3.33 ( 2 * 1.665). That should be correct since the included 20% tax of one item priced $19.98 is also $3.33.
In case you round the tax to $1.67 the cart will output a tax of $3.34 (2*1.67) with a quantity of 2 which is wrong.

Therefore rounding usually should happen at the end of computation right before the output.

**Comment by pippinsplugins** [comment]
@Netzberufler You're right, that does fix the issue. That's perfectly safe to do there too because we're already rounding the tax in the cart details array, we just forgot to round it before removing it from the subtotal.

Excellent catch.

**Comment by pippinsplugins** [comment]
Hmm nevermind, doesn't seem to resolve it.

**Comment by pippinsplugins** [comment]
Nevermind, yes it does.
