### ISSUE TITLE
Hide subtotal on checkout when prices are inclusive of tax

### ISSUE THREAD

**Issue by garubi** [easydigitaldownloads/Easy-Digital-Downloads#3165]
On EDD 2.2.8 configured with taxes as follows:
![taxes-config](https://cloud.githubusercontent.com/assets/10868669/6270190/71ecc2ec-b858-11e4-9064-f4162a66720e.png)
I apply a discount code at the checkout (for semplicity let sey -50%)

The total and the tax value is ok but the subtotal is wrong (so, really, it's just a display problem, it doesn't affect the amount payed on the purchase).

See this commented screenshot, it better than my english ;-)
![checkout3](https://cloud.githubusercontent.com/assets/10868669/6270753/569cfb70-b85c-11e4-9c78-2cbfed553f2f.png)

I started working on edd_get_cart_content_details() 
where I see that most of the calculation are done but I can't get it sorted: When I fix the subtotal issue that I get errors on the Total...

**Comment by pippinsplugins** [comment]
Actually it's correct. The subtotal is the amount of the items - taxes of the item.

The total is `100`. The tax is `9.02`, so the subtotal is `90.98`.

The subtotal does not include the discount.

**Comment by garubi** [comment]
The error IMHO is that the tax 9.02 is the 22% of €50: the discounted price.
So in Subtotal EDD is subtracting from the full price the tax calculated on the discounted price.

To me the correct subtotal should be €100 - €18,03 (22% of the full price)
then we apply the discount
then we show the tax on the discount price
then the total

what do you think?

**Comment by pippinsplugins** [comment]
Taxes are always after discounts. They cannot be calculated before discounts.

**Comment by garubi** [comment]
Ok, still I'm not 100% convinced I see you are pretty sure, soI think that you are right ;-)
Considering the EDD userbase if I'm the firt and the only one who broght up this issue it's very probably that I'm wrong, isn't it?
Maybe it could be related to the way we calculate VAT taxes here in Europe...

**Comment by pippinsplugins** [comment]
@garubi I'm more than happy to look at it further if you're confident it's a bug :)

For your store, are you needing taxes calculated before discounts?

**Comment by garubi** [comment]
@pippinsplugins I'm really not sure it's a bug, maybe it could be just the way we in Europe have to deal with VAT tax... or maybe I am just wrong ;-)

I'm now reading the issue #3186 to understand if it's related to this.

For our store we solved with a custom checkout template where we removed the subtotal row. Since we use an other software to issue the official and legal invoice, and the Total EDD display is ok, for the time being this is not a problem.

But I would more than happy if I could contribute to this issue. 
So in the next few days I'm going to ask and check with our financial consultant what he's thinking about this, and let you know.

Stefano

**Comment by pippinsplugins** [comment]
I've gone ahead and milestoned this for 2.4 to make sure we get some extra eyes on it.

**Comment by garubi** [comment]
Thank you @pippinsplugins , 
I think that this comment: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3186#issuecomment-76903334 helps clarify also the present issue:  we too here are calculating the tax "backward" (we too, as @Netzberufler are an European e-shop dealing with VAT).

**Comment by Netzberufler** [comment]
I also think it is a bug :) I have posted one possible solution to the forum, maybe some others can test it out: https://easydigitaldownloads.com/support/topic/license-renewal-wrong-subtotal-displayed/#post-453158

For me, the correct calculation should look like:
Item Price: 100€
Subtotal: 81,97€ ( 100€ - 22% of 100€)
Discount: 40,98€ ( 50% of 81,97€)
Taxes: 9,02€ ( 22% of Subtotal - Discount)
Total: 50€

I think there are two issues in the current implementation:

First Issue: The subtotal has to be calculated backwards from the item price by substracting the tax. This should happen before discounts are applied. The subtotal comes first, then the discount.
As result: subtotal = item price - 22% of item price

Second Issue: The discount is calculated from the item price including taxes (50% of 100€ = 50€). However, discounts are also coming before taxes are applied like the subtotal. Therefore the discount amount should also be calculated backwards by substracting the included tax. 

In order to fix that I would make a slight change to the function edd_get_cart_content_details() in /includes/cart/functions.php

Replace
```
if( edd_prices_include_tax() ) {
$subtotal -= $tax;
}
```
with
```
if( edd_prices_include_tax() ) {

$tax_subtotal = edd_get_cart_item_tax( $item['id'], $item['options'], $subtotal );
$subtotal -= $tax_subtotal;

$tax_discount = edd_get_cart_item_tax( $item['id'], $item['options'], $discount );
$discount -= $tax_discount;

}
```

**Comment by pippinsplugins** [comment]
The tax amount is corrected in d324992965dd083681ec88c08a63a3b95440967c

I don't think we can adjust the discount quite like that, but I can do more testing to find out for sure. We're too close to the release of 2.3 to include the discount fix in 2.3, but we will work on it for 2.4.

**Comment by Netzberufler** [comment]
I totally understand that it needs some testing. 

I am currently running some tests on my staging website and if it works fine I will try the fix on my live server. I will report here if I run into any problems.

Here is the code snippet with the rounding tax fix combined:
```
if( edd_prices_include_tax() ) {

	$tax_subtotal = edd_get_cart_item_tax( $item['id'], $item['options'], $subtotal );
	$subtotal -= round( $tax_subtotal, edd_currency_decimal_filter() );	

	$tax_discount = edd_get_cart_item_tax( $item['id'], $item['options'], $discount );
	$discount -= $tax_discount;

}
```

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@Netzberufler Did you ever get a chance to test it on your live server?

**Comment by Netzberufler** [comment]
Yes, it seems to work fine. We are using discounts only for license renewals and therefore there weren't a lot of purchases yet, but these have worked.

However, I am not sure if there are any possible side effects with some discount extensions since we are not using these. 

I have also slightly changed the code from above to avoid any 1cent rounding bugs by calculating the subtotal at the very end after the $details array is set up:

 ```
if( edd_prices_include_tax() ) {

	$tax_subtotal = edd_get_cart_item_tax( $item['id'], $item['options'], $subtotal );
	$subtotal -= $tax_subtotal;
			
	$tax_discount = edd_get_cart_item_tax( $item['id'], $item['options'], $discount );
	$discount -= $tax_discount;

}

$total      = $subtotal - $discount + $tax;

// Do not allow totals to go negatve
if( $total < 0 ) {
	$total = 0;
}

$details[ $key ]  = array(
	'name'        => get_the_title( $item['id'] ),
	'id'          => $item['id'],
	'item_number' => $item,
	'item_price'  => round( $item_price, edd_currency_decimal_filter() ),
	'quantity'    => $quantity,
	'discount'    => round( $discount, edd_currency_decimal_filter() ),
	'subtotal'    => round( $subtotal, edd_currency_decimal_filter() ),
	'tax'         => round( $tax, edd_currency_decimal_filter() ),
	'fees'        => $fees,
	'price'       => round( $total, edd_currency_decimal_filter() )
);
		
// Fix rounding bugs
$details[ $key ]['subtotal'] = $details[ $key ]['price'] - $details[ $key ]['tax'] + $details[ $key]['discount'];
```

I guess most Europan users with inclusive taxing do not really mind that issue, because the tax and total amounts are calculated correctly and everything works fine, only the subtotal is displayed wrong on the checkout page.

It would be great if you could just add a filter to the return of the $details variable in case you have concerns to change these in core. I totally understand that because the change could easily lead to some unexpected issues. 

At the moment I have to manually edit the file every time I update EDD and be able to hook into the function would simplify things a lot.

**Comment by pippinsplugins** [comment]
@cklosowski and I have just been discussing this and we believe the best solution would be to be adjust how the subtotal is displayed based on the "Base Region" selected in settings. If the store is in the EU, we adjust the subtotal to display as expected for EU users.

This can be done without adjusting any of the data, which then lets us avoid making risky changes that can (and have in the past) caused unforeseen consequences.

**Comment by Netzberufler** [comment]
Sounds like a good and much safer solution, I like it.

**Comment by pippinsplugins** [comment]
We don't have enough time to get this into 2.4 so I'm moving to 2.4.3.

**Comment by pippinsplugins** [comment]
@garubi @Netzberufler Is there a situation that either of you are aware of that would require that the subtotal be displayed? I was thinking of just hiding it automatically for stores in EURO countries. Any objections?

**Comment by pippinsplugins** [comment]
Punting to 2.4.4 due to time constraints.

**Comment by garubi** [comment]
Sorriso for the delayed answer.. I'm on holiday hiking on the alps and
can't  check the email or the web.
I have to check with our fiscal consultant. ..   but I'll be unable to
reach him until september.

But btw hiding it is what we have done here while waiting for a different
solution.  ;-)

Stefano
Il 17/Ago/2015 16:14, "Pippin Williamson" <notifications@github.com> ha
scritto:

**Comment by pippinsplugins** [comment]
:+1:

**Comment by Netzberufler** [comment]
Sorry, I was also on holiday.
I'm not sure if it is required to display the subtotal by any laws, but I would prefer if the cart would show it. 

Are there any reasons against adding a filter to the return of the edd_get_cart_content_details() function?

EDD could then use the safe way and hide the subtotal automatically, but it would still allow developers to hook into the function and change it in case they want to display the subtotal (like me).

**Comment by pippinsplugins** [comment]
We chose not to add a filter to `edd_get_cart_content_details()` because it's an extremely sensitive function. If an extension were to change something there, it could cause cascading effects.

**Comment by Netzberufler** [comment]
Sounds reasonable.

I guess I'll use the checkout_cart.php with own functions to display the subtotal as workaround then or stick with the solution that hides the subtotal completely. 

Wouldn't it be better to hide the subtotal by checking if inclusive taxing is activated with edd_prices_include_tax() rather than using the base country?
