### ISSUE TITLE
Adjust filter names for the From Email on purchase receipt and sales notification emails

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3211]
Right now, the `edd_purchase_from_address` From Email filter name is shared for Purchase Receipt emails, Sales Notifications emails, and the Test Purchase Receipt. 

They shouldn't all share the same filter name so at least one of them (not sure how much the test one matters) should be changed.

Note: The Sales Notification email should probably change because the current filter name makes no sense for it. However, it's also most likely the one people have been using in their own code. So backwards compatibility and all that good stuff...

**Comment by cklosowski** [comment]
@SDavisMedia I only see 3 uses, and the one you mention 'Sales Notification' is the only one that makes sense, so will remain at the same logic.

Since the other two are admin usage only, I'm inclined to just ignore backwards compat on them since, they are simply for testing, and notifying admins of sales.

**Comment by pippinsplugins** [comment]
:+1:
