### ISSUE TITLE
Version EDD API

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3337]
We should version our API.

Right now we use site.com/edd-api/{endpoints}
If we move to a system like site.com/edd-api/v{number}/{endpoints} we can improve our api iteratively without needing to worry about breaking things relying on our api (for example #3338 ).

We should alias the current api to site.com/edd-api/v1/{endpoints} and come up with a good system so that extensions and core can register the same endpoints across multiple versions easily.

The sooner this is in the better. Not only can EDD core use it, but also extensions wishing to register an action to a specific version endpoint could utilize it.

**Comment by chriscct7** [comment]
Actually, now that I think of it, revisions might be better.

The problem with versions is it becomes a big problem quickly to iterate or add new methods. Like if #3338 becomes the only change we do for 2.4, does that constitute version 2 of the api? I don't think it does but its a needed improvement that would get delayed till we have enough to push as a v2. Instead I think we could do something like revision numbers, so specific functionality is available from a specific revision forward. Maybe for example, instead of v1, v2, etc, we use EDD's version number. Thoughts?

**Comment by cklosowski** [comment]
Let me think on the `Version vs Revision` decision. There are pros and cons to each side of these.

**Comment by chriscct7** [comment]
Yeah. Let's talk it over at Loop

**Comment by chriscct7** [comment]
A third option would be instead of doing global numbers, we could version each endpoint.

So like /edd-api/v1/sales would pull version 1 of sales
           /edd-api/v2/earning would pull version 2 of earnings

That might be a really appealing option. It lets us version each endpoint without an extension having to wait for an EDD core release to go out, and it lets us version each endpoint individually.

**Comment by chriscct7** [comment]
If we did that, we don't even necessarily have to do /edd-api/{num}/{endpoint}

We could do /edd-api/sales/?version=2 where version tells you which version of the api to use. By default it always could use the latest version, and then people could use that query arg to change to an older version and set it there.

**Comment by cklosowski** [comment]
I side we table this for an in-person discussion we have at Loop.

**Comment by pippinsplugins** [comment]
Agreed, let's talk on it more in person.

@chriscct7 Note, please don't add `Needs Unit Tests` to an issue until it actually has code written for it. A unit test without the code is silly.

**Comment by chriscct7** [comment]
Fair enough

**Comment by pippinsplugins** [comment]
We'll need to work with @mps to get the EDD iOS app updated at the same time as this goes out, or shortly afterwards.

**Comment by mps** [comment]
@pippinsplugins just let me know :+1:

**Comment by pippinsplugins** [comment]
@cklosowski @chriscct7 I have a working prototype ready for you guys to look at.

First, this moves all API classes into an `api` folder.

There are now three primary files:

- class-edd-api.php - This is the main class that sets up the API, processes the queries, validates the user, etc. Much the same as it was.
- class-edd-api-base.php - This is the main class that all API versions extend. This is itself an extension of `EDD_API`.
- class-edd-api-v1.php - This is v1 (current) of the API. It is an extension of the `EDD_API_BASE` class. This class does not contain any changes at all and is only here in order to maintain consistency with file/ folder structure for future API versions.

API versions look like this:

- `/edd-api/v1/sales` - this version 1
- `/edd-api/sales` - this is version 1 or whichever version is set as the default. The default is set to the latest version during install or by the `EDD_API_VERSION` constant
- `/edd-api/v2/sales` this is version 2 when it exists. If a non-existent version is called, EDD falls back to the default version.

This is full functional at this time (I think) but is not considered complete.

Thoughts?

**Comment by pippinsplugins** [comment]
Oops, addendum.

Now just two initial classes:

- EDD_API - same as always plus versioning
- EDD_API_V1 - version 1 of the API
- EDD_API_VX - version X of the API

**Comment by pippinsplugins** [comment]
We need lots and lots of unit tests for this now :)

I'd love to hear additional feedback on the methods I've used for doing this.

**Comment by pippinsplugins** [comment]
API Versioning has been merged into `release/2.4`

**Comment by pippinsplugins** [comment]
Closing as complete.

**Comment by pippinsplugins** [comment]
Oops, need more unit tests.
