### ISSUE TITLE
Update customer email when user email is updated

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3364]
If user that is connected to a customer account updates their email, the customer email does not get updated. Nor do the payments attached to the customer.

We should update the customer and payments when the user account email is changed.

Ticket: https://wordpress.org/support/topic/bug-when-user-changed-email

**Comment by chriscct7** [comment]
Also for name?

**Comment by pippinsplugins** [comment]
Yes.

**Comment by chriscct7** [comment]
And I assume you also want the reverse as well? Change email on EDD Customer page changes the WordPress user email for the customer?

**Comment by pippinsplugins** [comment]
Yes.

**Comment by chriscct7** [comment]
There's a couple more potential issues I want to consider and there's a minor conflict issue I need to fix. Should have this done within next 48, prob within next 24

**Comment by cklosowski** [comment]
@chriscct7 how are we coming on this? I'd like to try and get 2.3.8 out this week.

**Comment by pippinsplugins** [comment]
I don't think this is a 2.3.8 issue. It could have some larger implications. Let's punt to 2.4.

**Comment by chriscct7** [comment]
After spending quite a bit of time on it, I would like to second the move to 2.4. I've got a list of possibilities and potential issues I'm still running down. I think this is something though that I can have sorted out and done this weekend, and then we can play around with and test my proposal with Loop if that's agreeable. I do echo the concern that this can't be a point release even though its a bug, because the implications if something goes wrong here are far reaching and potentially catastrophic.

**Comment by cklosowski** [comment]
Yep, i'm 100% good with that. Thanks @chriscct7. Appreciate the due diligence on it.

**Comment by pippinsplugins** [comment]
Things that have to be updated when user email is updated:
- file download logs have to have their email updated
- payment records need their email updated
- customer records need their email updated

Any others?

**Comment by mintplugins** [comment]
Might be a related bug here. I have a customer who mistyped their email so it created a new "customer" but not a new "user". The user id is 299 for both purchases. But the customer email is different (because of the typo). Because of that typo, the customer doesn't see their purchase in their account. I also appear to have no way of adding that purchase to the customer's account because I can't fix the typo in the email address. If I try, I get this error:

"WordPress database error:  [Duplicate entry 'user@domain.com' for key 'email']

:(

**Comment by cklosowski** [comment]
@mintplugins I've seen this before, what I typically do is go into the payment for the wrong customer, update it to attach to the correct customer via the Admin Payment Details screen.

Then that will update the payment to be associated with that customer, and move over all the records, allowing you to delete the customer record with the incorrect address, then allowing you to associate a user with the correct customer.

We're working on a method to merge customers in a future release.

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs would love some testing on this.

**Comment by cklosowski** [comment]
To be clear, this is a 1 way change? Just going User -> Customer?

**Comment by cklosowski** [comment]
If that's the case, this is looking pretty solid.

**Comment by cklosowski** [comment]
There are a few notes from @chriscct7 on the PR you may want to peek at @pippinsplugins

**Comment by muesliq** [comment]
> @cklosowski We're working on a method to merge customers in a future release.

Any news on that? When a customer mistypes his email and is not a new customer I cannot correct his email address and thus not send him the download he paid for.

**Comment by cklosowski** [comment]
@muesliq it's still something we plan to incorporate but do not have a timeframe for.

**Comment by muesliq** [comment]
Thanks. See also #6043. I think customer account management needs some consideration.
