### ISSUE TITLE
Re-evaluate the payment details organization

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#3501]
Back in #2625, @elliott-stocks had suggested some re-ordering of payment totals, at the same time that @pippinsplugins and I were shifting things around inside the sidebar. I think it's time we regroup, look at the payment details screen and see if we can re-evaulate some of our organization to make this a better experience that looks less confusing to end users.

**Comment by elliott-stocks** [comment]
Thanks for creating a new ticket for this @cklosowski.

From my point of view I think the main points we need to change are -

* Display subtotal
* Display discounted amount next to the discount code

I also feel because the values are by default editable, it's not always easy to quickly read them. In the example I provided previously some of the values where just text, which I personally found easier to read (probably because of the amount of editable values in the page). What are your thoughts on adding a toggle button to enable/disable edits? By default (maybe an option to control default) we could show them as just text, click a edit button would change them to inputs.

**Comment by cklosowski** [comment]
We could look at the solution we had for customers, where you have to click to enter an editable mode.

**Comment by pippinsplugins** [comment]
Not major, punting to 2.7

**Comment by pippinsplugins** [comment]
Closing as wontfix for now. Its scope is too broad. All for making improvements here, but let's keep each improvement small and focused instead of vastly generalized.
