### ISSUE TITLE
Download Details widget doesn't display unless settings have been modified

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3661]
When adding the Download Details widget to a sidebar, if you don't change any of the settings and leave everything at defaults, it doesn't display. You must change at least one setting for it to show. I think we just need to set a default instance.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
@mindctrl this works fine for me...maybe the fix from dan in #3778 took care of this, but by default, we don't show up unless a download ID is specified, or the current item being viewed is a download (since the default selection is 'current'). Can you test again and close if this is not needed now?

**Comment by pippinsplugins** [comment]
This works for me as well. Closing as fixed. Re-open if you disagree.
