### ISSUE TITLE
Bitcoin Transaction ID (long string)

### ISSUE THREAD

**Issue by cryptoapi** [easydigitaldownloads/Easy-Digital-Downloads#3668]
When save long Bitcoin Transaction ID, it looking bad.
<?
edd_set_payment_transaction_id( $payment_id, $tx );
?>

Bitcoin Transaction ID example - 1090b68a4457fe077b32b6e50e096f5acf1ffe6553685a36fa8c015e6393b0c1
![11](https://cloud.githubusercontent.com/assets/8633086/9047832/7c3147fe-3a2c-11e5-85b0-a19109234ebc.PNG)

https://gourl.io/bitcoin-easy-digital-downloads-edd.html

**Comment by mindctrl** [comment]
Possible solution:
```
.edd-order-payment-key span {
    word-break: break-all;
}
```

It would look like this instead:
![image](https://cloud.githubusercontent.com/assets/1254870/9047959/766abce8-3a03-11e5-8710-a58c5abd5fc0.png)

**Comment by cryptoapi** [comment]
Can you add it directly to css file of EDD plugin ?

**Comment by mindctrl** [comment]
Yes, whatever fix we go with will go there. Just dropped it here as a note.

**Comment by cryptoapi** [comment]
I tested style. Need to use 'edd-order-tx-id', not 'edd-order-payment-key'
This work -

.edd-order-tx-id span {
    word-break: break-all !important;
}

**Comment by pippinsplugins** [comment]
We'll improve it.

**Comment by cklosowski** [comment]
I actually like the idea of targeting all the spans, not just this one, that would prevent this from sneaking up on other fields. Will look into this now.

**Comment by cklosowski** [comment]
oh sorry, not now, this is for 2.5...it can wait a bit

**Comment by pippinsplugins** [comment]
@topher1kenobe want to tackle this?

**Comment by cklosowski** [comment]
going with `break-word` on this one. `break-all` makes our keys wrap too, and I think it's a better UX to have the full word drop to a new line when it's too long. This will apply to anything with the `.edd-admin-box-inside` class, so that means any extensions adding long data will automatically get this. I also standardized the classes on anything that has `edd-admin-box-inside` so that this class is the last one, for sanity.

![screen shot 2015-09-28 at 8 21 45 pm](https://cloud.githubusercontent.com/assets/1390124/10154619/9ef805f2-661e-11e5-908b-37108e7555c0.png)

**Comment by pippinsplugins** [comment]
Looks good.
