### ISSUE TITLE
Add filter to disable `edd_items_in_cart` cookie.

### ISSUE THREAD

**Issue by dannyvankooten** [easydigitaldownloads/Easy-Digital-Downloads#3761]
I appreciate that this cookie is there to prevent caching issues with common hosts, but it is a little hard to disable right now.

Right now, it makes it impossible for me to serve anything from cache to visitors who have something in their cart. We're running a caching configuration that is specifically tailored to EDD so we do not need this cookie at all, so an easy way to disable it would be much appreciated.

Related #3688 #3172

**Comment by chriscct7** [comment]
We could introduce a constant called EDD_USE_COOKIE similar to our EDD_USE_PHP_SESSIONS one and set it to default true if not already defined, and then let people define the constant as false in their wp-config file if they don't want it. This would allow for the couple people who have this case (who almost certainly are always going to be developers who custom tailor caching solutions) to easily disable the cookie with the added benefit of not using a filter since that filter would be called incredibly frequently on sites with many concurrent users (thus causing filter overhead).

**Comment by pippinsplugins** [comment]
I like the of a constant as it's easier to ensure it's running early enough.

@dannyvankooten any objections to a constant?

**Comment by dannyvankooten** [comment]
Not at all! :+1:

**Comment by cklosowski** [comment]
Ok, just pushed up some changes to our session class. You should be able to avoid the cookie with the following in your `wp-config.php`
`define( 'EDD_USE_CART_COOKIE', false );`

**Comment by retlehs** [comment]
thanks y'all!
