### ISSUE TITLE
Report graphs not showing sales for days with sales

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3828]
We've had several reports of this now. The report graphs just drop to zero and don't show sales after a certain date.

Example:
![image](https://cloud.githubusercontent.com/assets/1254870/10077492/7877b490-62ae-11e5-9382-c20b4536388a.png)

You sometimes get different graphs, though still not accurate, by doing a custom range report.

Reported [here](https://secure.helpscout.net/conversation/124248887/17567/) and [here](https://secure.helpscout.net/conversation/114735444/15361/). @pippinsplugins has some tickets too.

**Comment by pippinsplugins** [comment]
Another ticket https://secure.helpscout.net/conversation/123721941/17518/

**Comment by pippinsplugins** [comment]
I suspect these issues are related to changes we made to the `EDD_Payment_Stats` class.

**Comment by pippinsplugins** [comment]
Another ticket: https://secure.helpscout.net/conversation/122031514/17277/

Another hint: checking the box to exclude taxes seems to improve it.

**Comment by cklosowski** [comment]
@mindctrl @pippinsplugins can anyone reliably replicate this locally?

**Comment by cklosowski** [comment]
I've replicated and have a possible fix.

**Comment by cklosowski** [comment]
Ok I did some digging, I'm not 100% positive we have a bug. I'm waiting for some feedback, but I think we just have some super stale transients that aren't getting refreshed here.

The reason I say this is, I fixed up some code, then commented out the transient for the earnings on a site experiencing this and it worked, however the sales counts were still off. So I commented out the request to the transients of the sales counts, and those came back too.

The reason the 'tax' options sometimes makes it look different is because the earnings graph has 2 transients, one with and with without taxes, so if the without taxes hasn't been requested since the transients have been cleared (any or all) then it'll show up correctly.

**Comment by cklosowski** [comment]
Ok, we need to do something about our transients...I'm looking and we don't preface any of our MD5'd ones...we should do that so we can debug easier...also, some might not be getting their expiration correctly.

**Comment by cklosowski** [comment]
Ok, I've added a proper prefix to our stats transients...since a PHP `md5` will return a 32 character string [source](http://php.net/manual/en/function.md5.php#refsect1-function.md5-returnvalues) and WordPress only allows up to a 40 character transient name [source](https://codex.wordpress.org/Transients_API#Using_Transients), we have to be careful on length.

To accommodate for this we've added `edd_stats_` to preface the transient name, which is 10 characters..meaning we had to shave some characters off the `md5` of the arguments. For this, I simply did a `15` character substring of the `md5` sum. this leaves us with a pretty low rate of collision, as according to some math a `4` character md5 substring causes a 50% possibility of collision at 300 entries. Being that we're going almost 4x the number of characters, that should exponentially reduce our risk of collision while still remaining pretty safe.

According to the Birthday Attach problem [source](https://en.wikipedia.org/wiki/Birthday_attack), I think we're going to fall into the range that:
If we generated `6.1 × 10^8` (or `610,000,000`) hashes, we'd have a `1%` chance of a collision. Given that we delete these every hour, I'd call this a safe method for now.

**Comment by pippinsplugins** [comment]
Looks good to me.

**Comment by pippinsplugins** [comment]
Pretty sure we can close this now. @cklosowski @mindctrl ?

**Comment by cklosowski** [comment]
yeah i'm good with it. if you guys are.

**Comment by mindctrl** [comment]
@pippinsplugins looks good to me.

**Comment by cklosowski** [comment]
Thanks guys.
