### ISSUE TITLE
Re-instate payment email and name fields

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3885]
In order to accommodate #3755 we need to support the ability for a payment to have a different email address and name than the customer. This allows a customer to purchase something on behalf of another person, and have all emails for download links sent to the proper email address.

When we introduced the customer interface we've made the customer the canonical link to a payment, however it is possible to have a payment have a different name and email than the customer (think amazon and buying a gift). We'll need to add back in a way to edit the name and email address on file for a payment, yet remain in tact with the customer record. Updating the payment email _*should not*_ update the customer record, and same goes with updating the customer, it _*should not*_ update the payment's email address.

**Comment by pippinsplugins** [comment]
During our last meeting we decided to not do this. @cklosowski were you able to log the new issue for the new plan? I'm not finding it.

**Comment by cklosowski** [comment]
I thought we were still supporting this, on top of our new plan.

**Comment by pippinsplugins** [comment]
I don't recall deciding that. I recall that we decided to nix this change completely and simply make it so that payment records can have different email addresses than the associated customer record.

@mindctrl @sumobi @chriscct7 @topher1kenobe @SDavisMedia @ghost1227 any of you remember?

**Comment by cklosowski** [comment]
That's what this is for, allowing the email on a payment to differ from the customer.

**Comment by mindctrl** [comment]
We decided not to do this in the meeting. 

Right now updating the email on a payment involves changing the customer record. You either change the email of the customer who bought it, or you create a new customer record if 'ownership' is changing hands. It's easy to understand and makes sense. Introducing a new field for updating the email address separate from the customer record is going to be confusing. Especially so since the Customer dropdown shows an email address with the customer name. Two fields with email addresses that don't match makes my head spin.

In my experience it's an edge case to want the payment email to not match the customer record. It makes sense to just change the customer record.

**Comment by cklosowski** [comment]
:+1: closing out then, thanks guys, I had gotten them confused apparently.

**Comment by pippinsplugins** [comment]
The issues that this was intended to solve are largely taken care of through #3914
