### ISSUE TITLE
Make EDD's about page compatible with Admin Menu Editor

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3934]
Let's see if we can take a different approach to the about page to avoid conflict with [Admin Menu Editor](https://wordpress.org/plugins/admin-menu-editor/).

**Comment by cklosowski** [comment]
I assume this is what we're talking about? 
![screen shot 2016-02-25 at 4 16 21 pm](https://cloud.githubusercontent.com/assets/1390124/13337861/2509ebf6-dbdb-11e5-926d-7e3121558765.png)

What's our goal? To shorten the titles? Make our own menu subset?

**Comment by pippinsplugins** [comment]
Goal: remove them.

**Comment by SDavisMedia** [comment]
@cklosowski :point_up:

**Comment by cklosowski** [comment]
@pippinsplugins @SDavisMedia :boom:

**Comment by cklosowski** [comment]
Currently there isn't a way to set our menu items as 'blacklisted' due to there being no filter on this array:
```
        $this->menu_url_blacklist = array(
            //WP RSS Aggregator 4.7.7
            'index.php?page=wprss-welcome' => true,
            //AffiliateWP 1.7.8
            'index.php?page=affwp-getting-started' => true,
            'index.php?page=affwp-what-is-new' => true,
            'index.php?page=affwp-credits' => true,
            //BuddyPress 2.3.4
            'index.php?page=bp-about' => true,
            'index.php?page=bp-credits' => true,
        );
```

I've emailed the developer looking to a filter added here for us, even offering to throw a PR that way if need be. Going to leave this on 2.5.10 for now, but if we get close I'll punt until we hear back from the dev.

**Comment by cklosowski** [comment]
Ok, got some feedback from the developer and his suggestion was to move the part of our removing the admin pages, into the same method that runs on `admin_menu` since `admin_head` is too late in the game for those plugins to hook.

This will make it more compatible across multiple menu editor plugins.

**Comment by pippinsplugins** [comment]
@cklosowski Were you able to test and see if that change fixes it or does it still require that they do an update as well?

**Comment by cklosowski** [comment]
This does not require they make any updates. This is something they suggested we do as it will fix the issue for all menu editors.

**Comment by pippinsplugins** [comment]
Great, so have you confirmed it resolves the problem by installing their plugin?

**Comment by cklosowski** [comment]
Yes, I've installed their plugin and this fix makes it so our admin pages are not part of their configuration.

**Comment by cklosowski** [comment]
Oh, and they are still accessible.
