### ISSUE TITLE
Extension updates not shown if license key is missing

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3935]
In Software Licensing 3.4 (https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/190) we made it so updates show up for all plugins regardless of license status.

Our `EDD_License_Handler` class, however, is causing this to not happen for EDD extensions that do not have a valid license key entered in settings.

To fix this and make it so updates always show, we need to remove this:

```php
		if ( 'valid' !== get_option( $this->item_shortname . '_license_active' ) )
			return;
```

**Comment by pippinsplugins** [comment]
Related to #3889

**Comment by pippinsplugins** [comment]
We also need to remove
```php
if ( empty( $data['license'] ) )
            return;
```

**Comment by om4james** [comment]
Thanks for this @pippinsplugins. I was happy to see in the Software Licensing v3.4 changelog that updates should now show even without a license key.

This is how WooThemes do things with their WooThemes Updater plugin - they show that there's an available update for a premium plugin/theme, in order to encourage you to add your license key so that the update can be downloaded/installed.

Also, I noticed with the 3.4 SL release, the `EDD_SL_Plugin_Updater` included in the software licensing addon is now out of sync with this one (https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/EDD_SL_Plugin_Updater.php). Not sure if that's a problem?

As you pointed out, `EDD_SL_Plugin_Updater::api_request()` needs to be updated to remove the empty license data check.

Looking forward to seeing these changes implemented in EDD so this enhancement works correctly.

**Comment by pippinsplugins** [comment]
@om4james The class distributed with EDD core is slightly different than the default one. After this, however, it will likely be identical.

**Comment by om4james** [comment]
Hi @pippinsplugins, I'm trying to test these changes.

I've put the latest `EDD_License_Handler` file (v1.6.2) in my plugin.

My EDD store is running EDD 2.4.9 and Software Licensing v3.4.2.

The outbound `get_version` HTTP request is running with an empty license key, however EDD SL v3.4.2 is responding with this response:

`{"new_version":"","sections":"","license_check":"","msg":"No license key provided"}`

Is there a new version of Software Licensing in development that resolves this issue?

I would have thought the software licensing addon should still respond with the latest version number, and some kind of message instructing the user to activate their license key in order to receive the update.

Feel free to add me to https://github.com/easydigitaldownloads/EDD-Software-Licensing/ if you'd like me to help you test/investigate.

Thank you!

**Comment by om4james** [comment]
Hi @pippinsplugins,

After testing further, I now realise that a valid license key still has to be specified in the update checks.

However in order to download the zip file update, the license key has to be activated otherwise this response is received:

`Your license has not been activated for this domain, please activate it first.`

So change in SL v3.4 means that the new versions are shown in the dashboard (even if the specified license key hasn't been activated).

In other words, PR #3946 could be:
`Don't require an active license key to run update checks`
instead of
`Don't require license key to run update checks`

Is that interpretation correct?

Are there any plans to improve this even more so that the pending updates can be shown in the dashboard even without a license key being specified?

That way people will see the pending update, along with a message that tells them to activate their license before they can download the update.

James

**Comment by pippinsplugins** [comment]
@om4james Your interpretation is correct, though the goal was to show updates even without a license key, so looks like we still need to make a change in SL.

**Comment by pippinsplugins** [comment]
@cklosowski We need to look at Software Licensing and track this down though I feel we can wait until after beta 1.

**Comment by cklosowski** [comment]
sounds good.

**Comment by pippinsplugins** [comment]
@cklosowski Let's hit this first thing after Christmas please.

**Comment by pippinsplugins** [comment]
@cklosowski Could you go ahead and work on this next please?

**Comment by pippinsplugins** [comment]
Extension with new version available but no license key:
![screen shot 2015-12-31 at 11 25 58 am](https://cloud.githubusercontent.com/assets/1034109/12066668/57a5a5ba-afb1-11e5-8f64-c7c50a8038a2.png)
Extension with update available and valid license key:
![screen shot 2015-12-31 at 11 26 33 am](https://cloud.githubusercontent.com/assets/1034109/12066675/652f9a88-afb1-11e5-8a0c-c9a8432be6f5.png)

**Comment by pippinsplugins** [comment]
I'm going to add a message about needing to activate the license key on ones that don't have it.

**Comment by pippinsplugins** [comment]
Plugin without valid license key and update available:
![screen shot 2015-12-31 at 11 44 04 am](https://cloud.githubusercontent.com/assets/1034109/12066831/d7a70e14-afb3-11e5-8540-3ea86066bc5c.png)

**Comment by pippinsplugins** [comment]
Changed message to `Enter valid license key for automatic updates.`

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs This is now all merged into `release/2.5`. Could I get some testing on it please?

**Comment by SDavisMedia** [comment]
All good on my end. :+1:

**Comment by om4james** [comment]
Hi @pippinsplugins,

I just wanted to let you know that these changes are working great for us.

Our premium plugin now shows update notifications in-dashboard even without a license key entered, but the customer has to activate their license key before they can actually install the pending update.

James

**Comment by pippinsplugins** [comment]
@om4james Glad to hear it!
