### ISSUE TITLE
array php

### ISSUE THREAD

**Issue by maxrossi** [easydigitaldownloads/Easy-Digital-Downloads#3968]

**Comment by pippinsplugins** [comment]
@maxrossi we love contributions from the community and would love to hear about the issue indepth. However, since no description was provided and a very generic title was given, I'm going to close this as `invalid`. If you wish to expand on the issue, please update the description and/or leave a comment below for assessment.

**Comment by maxrossi** [comment]
Sorry Pippin, it was my fault with GitHub interface, I didn't want to add an issue...
