### ISSUE TITLE
Updating Customer email does not update linked User email.

### ISSUE THREAD

**Issue by shazahm1** [easydigitaldownloads/Easy-Digital-Downloads#4067]
This might be related to #3997... not sure. But in the admin when editing a customer email address, the linked WP user email address does not get updated.

**Comment by pippinsplugins** [comment]
We currently update customer email when user email is updated but not the other way around: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3364

**Comment by cklosowski** [comment]
@pippinsplugins I'm having a hard time remember, but didn't we make a conscious decision to only do `user -> customer` and _*not*_ `customer -> user` changes? There was a reason we left it out, I just can't remember.

**Comment by pippinsplugins** [comment]
I'm not remembering a specific reason either.

**Comment by pippinsplugins** [comment]
Let's go ahead and milestone this for 2.5.8

**Comment by pippinsplugins** [comment]
Thinking on this a bit more, I don't think we should do this.

Updating a user account's email makes it potential for that user to lose log in access to the site (for example if they need to reset their password). Since customer records are not the "base" for a customer's access to the site, it feels wrong to just assume that we should update the user account when updating the customer. There are also cases when a customer's email is not the same as their user account, such as when a different email is entered on checkout by a customer that is logged in.

**Comment by pippinsplugins** [comment]
I propose `wontfix`.

Anyone else have an opinion?

**Comment by michaelbeil** [comment]
I agree with @pippinsplugins recent sentiments.

**Comment by SDavisMedia** [comment]
Same here.
