### ISSUE TITLE
edd_price() Show Default Variable Price

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/Easy-Digital-Downloads#4070]
Right now `edd_price()` always displays the lowest price if you are using variable pricing. Would it make more sense to show the selected default price option price instead?

**Comment by pippinsplugins** [comment]
Good catch. Yes, I think it would make more sense to show the default price option, or the lowest if no default is saved.

**Comment by spencerfinnell** [comment]
Just a note of another customer confused by this. Glad to see it in 2.5.8! :) I'll try to get a PR out if I can.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by kyletorrington** [comment]
Hi Pippin. Yes, please can this issue be sorted out asap. At the moment, I'm asking my customers to mention in the additional information field on checkout what add on products they want due to this issue (as my add on items are naturally cheaper than the main product purchase). Any idea when a fix will be implemented?

**Comment by pippinsplugins** [comment]
@kyletorrington It's on our todo list for v2.5.8

**Comment by pippinsplugins** [comment]
@mindctrl could you please give this a once over?

**Comment by kyletorrington** [comment]
Thanks for the attention to this issue everyone. Appreciate it.

**Comment by mindctrl** [comment]
@pippinsplugins looks good here.

**Comment by pippinsplugins** [comment]
Thanks @mindctrl, merging and closing.
