### ISSUE TITLE
Forced downloads: Nginx symlinks caused an issue (with fix)

### ISSUE THREAD

**Issue by jsonUK** [easydigitaldownloads/Easy-Digital-Downloads#4109]
Hi,

The **X-Accel-Redirect** on Nginx appears to be wrong when using forced downloads on a symlinked web root.

I am using **version 2.4.10** (latest).

I use Capistrano for deployments on a Debian box - my folder structure looks like eg.:
`/var/www/example.com/current/htdocs -> /var/www/example.com/releases/20160101221139/htdocs`

`includes/process-download.php` on line `211`:
```php
// We need a path relative to the domain
$file_path = str_ireplace( $_SERVER['DOCUMENT_ROOT'], '', $file_path );
header( "X-Accel-Redirect: /$file_path" );
```

PHP reports the following:
`$_SERVER['DOCUMENT_ROOT'] = /var/www/example.com/current/htdocs`
`$file_path = /var/www/example.com/releases/20160101221139/htdocs/wp-content/uploads/2015/11/example.zip"`

`strireplace` needs the absolute path to remove the string.

2 ways I can think of solving this:
1) Adding `realpath($_SERVER['DOCUMENT_ROOT'])`
2) or swap for `ABSPATH` (defined in wp-config.php).

Below is an example fix:
```php
// We need a path relative to the domain
$file_path = str_ireplace( realpath($_SERVER['DOCUMENT_ROOT']), '', $file_path );
header( "X-Accel-Redirect: /$file_path" );
```

Which ever you think is best :)

Cheers,
Jason

> Winter is coming... That means I will require more coffee.

**Comment by pippinsplugins** [comment]
Excellent, thanks @jsonUK 

I suspect this is the cause of some of the download issues we've seen with nginx in the past. We'll get this taken care of asap.

**Comment by davekiss** [comment]
Finally concluded this yesterday too, but my issue is just a tad different because my uploads live outside of the document root. The issue [also appears in EDD Software Licensing.](https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/269)


My downloads are breaking because EDD and EDD Software Licensing both [resolve a realpath to the plugin file](https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/5a1a85810464c44bb3049ed1a57fe863c5d7a0b2/includes/classes/class-sl-package-download.php#L247) through my shared, symlinked `uploads` folder which exists outside of the document root.

```php
// $file_path looks like this BEFORE line 247
"/srv/www/example.com/releases/20160121135535/web/app/uploads/edd/2015/01/awesome.zip"

// $file_path looks like this AFTER line 247 executes
"/srv/www/example.com/shared/uploads/edd/2015/01/awesome.zip"
```
However, the [nginx block tries to resolve a path through the document root, which is not symlinked](https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/5a1a85810464c44bb3049ed1a57fe863c5d7a0b2/includes/classes/class-sl-package-download.php#L264)

```php
// $_SERVER[ 'DOCUMENT_ROOT' ] looks like this
"/srv/www/example.com/releases/20160121135535/web"
```

So, when the nginx block runs, `str_ireplace( $_SERVER[ 'DOCUMENT_ROOT' ], '', $file_path );` does not find an intersection between the two strings and ends up returning an invalid filepath.

```php
// here is what is ultimately running and failing
$final_file_path = str_ireplace(
  "/srv/www/example.com/releases/20160121135535/web",
  "",
  "/srv/www/example.com/shared/uploads/edd/2015/01/awesome.zip"
);
```

I commented out [line 247](https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/5a1a85810464c44bb3049ed1a57fe863c5d7a0b2/includes/classes/class-sl-package-download.php#L247) and it works, but obviously that's not the best fix for everyone. I think in my scenario, neither adding `realpath()` to the document root nor switching to `ABSPATH` would correct the issue.

**Comment by cklosowski** [comment]
@davekiss That makes sense. We have some other issues with symlinked resources within EDD as well that we're trying to resolve.

thanks for this detailed findings.

**Comment by pippinsplugins** [comment]
@cklosowski Could you look at this more? If we can fix this, it should prevent a large number of support tickets as more and more customers are using nginx.

**Comment by cklosowski** [comment]
@jsonUK could you test this branch for me? Let me know if it works, I went with the `realpath` method here. I think it leaves us less likely to hit issues with modifications to the `ABSPATH` constant.

@davekiss I tried to implement a filter for your `realpath` issues slightly higher, and like you said it's not something that will ultimately be a good solution for the vast majority, and after talking with @pippinsplugins about it, we're just concerned about the risk of affecting all the other server configurations with a change in that section of the download process, since that section is used universally.

If you want to open up a separate issue for that use case of a symlinked doc root with a symlinked uploads directory we can look into something in the future.

**Comment by davekiss** [comment]
@cklosowski what is the filter that you are referring to?

**Comment by davekiss** [comment]
@cklosowski @pippinsplugins just pinging to bring this issue back around if you'd like to investigate. My uploads live outside of the document root since each deploy is a new release directory. Commenting out the `realpath` line is still the only fix for me that works on nginx to resolve the download path correctly. EDD's nginx issues may still have something to do with that php/nginx config flag that specifies how to resolve symlinks.

**Comment by pippinsplugins** [comment]
@davekiss do your manual file downloads fail as well or just the updates through Software Licensing?

**Comment by cklosowski** [comment]
@davekiss I remember us discussing this. The reason you are having this problem is that the `realpath` function in PHP is cached, and when you change a symlink, PHP doesn't update it's path to the new `realpath`, it keeps using the cached version, which was replaced/removed. Have you tried adding a restart of the PHP service to your scripts for deployment?

**Comment by davekiss** [comment]
@pippinsplugins only software licensing updates fail now. I can't really remember what the difference is in the process though. I seem to remember in the past having to comment out the same line in the core plugin class as well (`process-download.php`)

@cklosowski The following is the last step in deployment: `sudo service php7.0-fpm reload`

**Comment by cklosowski** [comment]
@davekiss can you do a `restart`? A `reload` doesn't kill the parent process, just the child workers and reloads configurations. It leaves the caches in tact, since the primary process never was touched.
