### ISSUE TITLE
Remove "Status" column from Discount Codes list

### ISSUE THREAD

**Issue by mgibbs189** [easydigitaldownloads/easy-digital-downloads#4157]
Instead of showing the `Status` column, what if we just highlight Active discount codes (like on the plugins listing page)?

<img src="http://i.imgur.com/6XIOAca.png" width="279" height="171" />

If you like the idea, I could submit a PR.

**Comment by pippinsplugins** [comment]
Ooh, I rather like that idea!

**Comment by mgibbs189** [comment]
@pippinsplugins Great, I'll submit a pull request

**Comment by pippinsplugins** [comment]
:+1:

**Comment by chriscct7** [comment]
I like the idea, but before we merge this, I'd like to do some user testing
on the idea. I wonder how intuitive this is going to be for non-developers
and non-WordPress power users. My concern stems that there might be a
significant portion of EDD users who get their websites with EDD perhaps
already installed, or that in some organizations there are people who would
just use EDD and not have to deal with (or even have access to plugins). I
wonder if it's really intuitive for those users that the background is blue.

My solution to test this theory is WordCamp Miami is coming up in a few
weeks, which I'll be attending and speaking at. During WCMIA, I can grab
some users in the happiness bar to test the intuitiveness.

**Comment by chriscct7** [comment]
Basically the question would be: If a person has never seen the plugins
menu page, how intuitive is the blue background

**Comment by mgibbs189** [comment]
@chriscct7 We'd need to ask the WP design team, but I'm assume it's pretty intuitive for them to go this route for the plugins page.

For users not familiar with this color coding, the learning curve is really low. Users who see the blue background can over over the Discount Code to see a "Deactivate" link. Common sense suggests that if the link is "Deactivate", then the discount must currently be active.

If the background isn't blue, then it's inactive or expired. For expired Discount Codes, there just won't be an "Activate" link (or they can look at the Expiration Date column).

**Comment by mgibbs189** [comment]
@chriscct7 User testing for WCMIA would be cool. I'd be happy to contribute, just let me know if you need anything (e.g. a PR to some user testing branch).

**Comment by chriscct7** [comment]
@mgibbs189 There wasn't a user test on or since it was added 8 years ago in WordPress 2.5. It was just a cool thing they wanted to do to make it easier to distinguish: https://core.trac.wordpress.org/ticket/6067

Before background colors, it used to be that the color of the text of the plugin name was color coded active: https://core.trac.wordpress.org/ticket/6019

Since 2.5, the colors have been updated to match the default WordPress color schemes, including a change from grey to green in 2.8, green to blue in 3.0/3.1 and an MP6 change of the shade of blue in 3.8, but whether or not it made/makes intuitive sense hasn't actually been tested simply because at this point there's an established precedent for having it. It's something that maybe could be tested for core as well.

If you could submit a pr for it, I can check it out and get some people to test it at WCMIA.
If the user has access and has seen the plugins page, matching will make sort of intuitive sense, but if you can't/never seen the plugins page, it might not be that intuitive. For example, a typical user might wonder why the active ones aren't for example green and deactivated ones red? This is actually how WordPress originally added it before it was changed to match the default color schema.

**Comment by cklosowski** [comment]
I agree, some user testing here might be good, and it cannot be guided. We'd need to have to ask the user to find discounts codes, and identify an active, inactive, and expired discount code, without our help. We'd need to have a configuration already setup and ready for people to look at, but I fully support the idea of showing them the two setups.

I think ti's a great concept, just concerned of the different context between Discounts and Plugins, as they are slightly different.

**Comment by cklosowski** [comment]
Milestoning for 2.6 so we can make sure we're paying attention to it.

**Comment by cklosowski** [comment]
With the advanced timeframe for 2.7 (as we work on faster iterations), we still need to get some user testing done here, so i'm going to punt to 2.8 for now.

**Comment by sunnyratilal** [comment]
I've opened a PR for this (#6174). It would be good if we can somehow get some user testing done to see if this is worth merging.

**Comment by pippinsplugins** [comment]
<img width="1431" alt="screen shot 2017-11-13 at 12 06 42 pm" src="https://user-images.githubusercontent.com/1034109/32741242-23870736-c86b-11e7-8877-542dc535880a.png">

I really like this, though looks like we have lost the alternating row colors.

**Comment by cklosowski** [comment]
going to punt. i've added support for the expired and inactive ones so it looks like this...but I think we'll wait until we have some more 'requests' for this. I think that concept that it's not quite as intuitive is a valid one:
![image](https://user-images.githubusercontent.com/1390124/36913610-c1525942-1e07-11e8-9dd7-92eddbddf8aa.png)

**Comment by sunnyratilal** [comment]
@JJJ has already done this in `release/3.0`. We don't have a `Status` column on any of the list tables anymore.
