### ISSUE TITLE
FES 2.3 will not run under PHP 7.02

### ISSUE THREAD

**Issue by WPExpert** [easydigitaldownloads/Easy-Digital-Downloads#4158]
Fatal error: 'continue' not in the 'loop' or 'switch' context in ../wp-content/plugins/edd-fes/classes/admin/downloads/class-download-table.php on line 102

**Comment by pippinsplugins** [comment]
@WPExpert We track extension bug reports through their own dedicated repositories. FES is a private repository but I am tracking the issue for you and we will have it fixed.

**Comment by WPExpert** [comment]
FWIW I recently had a problem with Redux claiming it was PHP7 compatible, when it wasn't. However, they very quickly fixed it...

`On 1 January 2016 at 22:43, Kevin Provance <notifications@github.com> wrote:
When you contract them, mention it's a PHP 7.0 issue, and he should update Redux to version 3.5.8.12, which addresses this.

​Thank you so much Kevin.​`

Then again later...

`​From: Dovy Paukstys <notifications@github.com>
Date: 5 January 2016 at 04:46
Subject: Re: [redux-framework] [1] wp_remote_get() failed. [2] Fatal error: (#2783)
To: reduxframework/redux-framework <redux-framework@noreply.github.com>
Cc: Terence Milbourn <admin@wpexpert.support>

Pushed a bunch of fixes for this that should suppress the issues from here on. Thanks for the feedback.`

So. long story short, I hope that's maybe also the solution for FES 2.3

**Comment by chriscct7** [comment]
FES's PHP7 issues don't come from Redux. FES bundles a forked version of Redux where I already fixed the issues they just pushed a release for among other bugs. We're also actually moving away from Redux next major release (see https://trello.com/c/rtKjV1tB/126-fes-settings-to-be-in-edd-settings), where we've also fixed additional PHP 7 issues. It's a bit harder for us to fix all at once, since I work primarily on Windows which doesn't have a pre-compiled build for PHP 7.

By the way, I'd love to have a beta tester for FES (who tests pre-release builds of FES) on PHP 7. If you're interested, please consider filling out our quick post FES 2.3 survey, and when we start beta testing the next release we can get you in: http://www.chriscct7.com/fes

**Comment by WPExpert** [comment]
Done!​​

**Comment by chriscct7** [comment]
Thanks!

On Mon, Jan 11, 2016 at 12:48 PM, Terence Milbourn <notifications@github.com
