### ISSUE TITLE
Tracking info not sending

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4511]
while preparing to update tracking data and usage tracking plugin we found that pings were not being sent for those opted in. For example one of my sites has a last checkin time of:
GMT: Fri, 06 Nov 2015 05:05:20 GMT (`1446786320`)

**Comment by cklosowski** [comment]
After a little investigation, might just be a small subset of sites. Going to punt until we can investigate further.

**Comment by pippinsplugins** [comment]
This was caused by incorrect logic in the send_checkin() method. First, it required that the last send date be recorded, meaning if that failed for whatever reason, additional check ins would _never_ be attempted. Second, the date logic was wrong.

Looks like there is also a problem on the receiving end but that's separate.
