### ISSUE TITLE
Cache key is too short in EDD_Payment_Stats::get_earnings()

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/easy-digital-downloads#4618]
I am using the `edd_stats_earnings_args` filter with a meta query, since my arguments are getting added to the end of the array they get cut off in the cache key. I end up with the same results as if my filter was not there. If I bypass caching, I get expected results.

Option keys can be 55 characters I think. Serializing adds a lot of extra characters, but changing substr to take 45 characters should help.

I will also fix my filter, but still, I think this is worth changing.

**Comment by Shelob9** [comment]
For the record this is what I am doing:

```
	add_filter( 'edd_stats_earnings_args', function( $args ){

		$args[ 'meta_compare' ] = '!=';
		$args[ 'meta_key' ] = '_edd_payment_total';
		$args[ 'meta_value' ] = '0.00';
		$args = array_reverse( $args );
		return $args;
	});
```

The array_reverse() is my workaround to make sure my custom args get factored into the caching.

**Comment by cklosowski** [comment]
@Shelob9 We're sub-stringing the MD5, which is a 32 character string, not he serialized string itself. The reason for the cut is that these are stored in Transients, so the maximum limit of characters it can take is 45 characters per the codex (https://codex.wordpress.org/Function_Reference/set_transient#Parameters).

Since our transients use `edd_stats_` as a prefix (9 characters) which allows us to remove them on uninstall as well as clear transients easier in case of some overly aggressive hosts, we're left with a usage 36...

I think the point I'd like to see here is roughly `32` to avoid any possibility of conflict, which is actually the length of an MD5 hash.

**Comment by Shelob9** [comment]
@cklosowski Then maybe the better solution to avoid my workaround is to do an array_merge or something so the filtered keys are always on top. Not sure... Will revisit tomorrow.

**Comment by cklosowski** [comment]
Or, we can just not substring. By not sub-strining, it'll avoid the situation all together :) Since 32 + 9 is still less than the 45 character limit set fourth by the Transient API and there's less chance of a collision in the uniqueness of the keys.

**Comment by cklosowski** [comment]
Let me know if that change set works for you @Shelob9

**Comment by pippinsplugins** [comment]
PR looks good. Merged.
