### ISSUE TITLE
Select box for customers has the wrong internal label

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4689]
![image](https://cloud.githubusercontent.com/assets/1324637/16129394/9ec5274a-33d2-11e6-9d78-b813004cdf83.png)

"Downloads" should be "customers"

**Comment by cklosowski** [comment]
We'll have to fake that placeholder like we did in other areas. Nice find.

**Comment by cklosowski** [comment]
Ok this is a larger change thanks to Chosen. I updated our outputted scripts to support searches for Countries, States, and Customers. Our `select` type supports options of adding a `data` element with `search-type` and we use that as a wild cart search for `edd_vars[search-type]`.

This will work 100% with customers and downloads right now. Since States and Countries don't have a helper wrapper it's up to each instance of the country or state search to add the elements. I've done this for the view order details at this point.
