### ISSUE TITLE
average earnings data doesn't account for fees

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#4708]
"`edd_get_average_monthly_download_earnings` incorrect when fees present due to `EDD_Download()` earnings property" ~ @cklosowski 

As shown here:

![2016-06-22 at 10 01 am](https://cloud.githubusercontent.com/assets/2359131/16275946/3e70c140-3861-11e6-880c-a4fe3a12ee1d.png)

That's 2 purchases of a $10 item with a $1 fee. $11 \* 2 for $22. The average earnings shows $20, though.

**Comment by chriscct7** [comment]
Adding to 3.0 release as related ticket #6859 caused by the same root issue, has a pr (#6969) which also fixes this issue (once totals are re-done using the tool). We're running the recalculate functions anyway in the 3DD migration routine, so merging of the PR will also resolve this issue out as well.

**Comment by chriscct7** [comment]
Closed with #6969 as well.
