### ISSUE TITLE
Update MasterCard Logo

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4796]
MasterCard has announced they are changing their logo. We need to update the one we include in EDD. The new one looks like:
![image](https://cloud.githubusercontent.com/assets/1324637/16846430/6b0d5942-49ba-11e6-8b7a-d39ba7a68e84.png)

The name "MasterCard" is no longer camelcased, but on websites should be displayed "mastercard."

**Comment by cklosowski** [comment]
@SDavisMedia don't we have an open issue to work on the cc payment icons anyway? #4238?

**Comment by pippinsplugins** [comment]
Is the change already official or planned?

**Comment by cklosowski** [comment]
![screen shot 2016-07-14 at 9 03 01 am](https://cloud.githubusercontent.com/assets/1390124/16846568/c6936284-49a1-11e6-8db9-99e7448056da.png)

It's live

**Comment by chriscct7** [comment]
It's already in effect on most of their properties

**Comment by SDavisMedia** [comment]
Yea I was just gonna say that, @cklosowski. See, I took forever on the other issue for a reason. :)

I'll have to find some good icons with an update MC logo ASAP.

**Comment by SDavisMedia** [comment]
For reference: https://www.mastercardbrandcenter.com/us/getourbrand/index.shtml?pageId=dl_0340&expertVisible=false&staticPage=yes

They need to update their assets.

**Comment by sunnyratilal** [comment]
They are releasing updated brand assets on September 30 so we still got a while.
![image](https://cloud.githubusercontent.com/assets/1525554/16894902/1ffb19cc-4b5d-11e6-97b1-ad166d84fbc6.png)

**Comment by chriscct7** [comment]
Ironically that banner uses "Mastercard" which is not either their old
brand "MasterCard" or their new one "mastercard."

**Comment by lalunecreative** [comment]
I'd be willing to volunteer to create some new icons for you guys. It wouldn't take me long. I'm assuming you want something in the same sizes as before until you can get another solution. They'll be the updated versions of the logos for 2016. Mind if I make them square to get rid of the bleed problem from this ticket? #4238 

Ideally they would be .png files since those look better for retina screens as well.

**Comment by SDavisMedia** [comment]
@lalunecreative I'd love it if you took a stab at it! However, I do think they should remain rounded at the corners. The current icons could very will be rounded and transparent as well. The fact that they are not is just an oversight.

Since you're considering PNG, could you keep them rounded and roughly the same size?

**Comment by lalunecreative** [comment]
I should be able to run them through some compression, if it's still not low enough I'll just use gif.

**Comment by lalunecreative** [comment]
Done. Where should I drop them?

**Comment by michaelbeil** [comment]
You could create a PR that adds them to `/templates/images/icons`.
