### ISSUE TITLE
edd_log_user_in() don't need $user_pass

### ISSUE THREAD

**Issue by turtlepod** [easydigitaldownloads/easy-digital-downloads#4801]
I don't get why you need $user_pass.
Currently it's practically used for nothing (correct me if i'm wrong),
excerpt some dev probably actually use the $user_pass args and save the plain text password.

master branch:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/login-register.php#L109

current stable:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/2.6.4/includes/login-register.php#L109

It feels like a backdoor for some ext.
I recommend to simply remove it.

NOTE: you don't need user password to log user in.

**Comment by chriscct7** [comment]
It needs to be there to preserve backwards compatibility. It's been there
since basically the beginning of EDD (4/12/2012).

It's not a security risk as a plugin that has the ability to hook in there
could also use the other WordPress hooks on insert user and change password
to get the plain text passwords for all users, and it wouldn't rely on edd
that way and thus work for all wp users. Plus if they wanted to they could
just wp_authenticate anyways.
