### ISSUE TITLE
Variable pricing reports

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#4889]
Reports should be provided for each pricing option of a download (i.e. sales and earnings of each variable price).

For example:
Download A has three pricing options Lite, Pro, Ultimate.  We don't know how many customers purchased each respective option unless each plan was a separate download.

**Comment by chriscct7** [comment]
IMO this is something that should of the highest priority in EDD. I hesitate to even call it an enhancement over a bug, because this is something that's so incredibly expected to be there.

The majority of EDD users at some point use variations, but right now there's no way to tell how many sales you have of any of the variations. This basically means that if you want to run a business on EDD, you should not use variations because you won't be able to get the statistics and reporting you're going to want. 

Right now if you do use variations, you can't answer common, basic business questions such as

-  "is my levels of pricing underpriced/overpriced"
-  "should I offer a higher/lower option"
- "does one version of a product sell better than others (to emphasize"
-  "do all versions of this product sell equally?"
-  "who are the customers that bought the most expensive version of this product (to reward)"
-  "who are the customers that bought the least expensive version (to upsell)"
-  "who are the users who bought a version we're discontinuing (to notify)"
-  "should we discontinue this version (for lack of sales)"

and the list goes on.

**Comment by thomasgriffin** [comment]
+100000 - the lack of this feature is why I'm having to build our own analytics and insights addon.

**Comment by jaredatch** [comment]
Yes, please! As someone who just started using EDD early 2016, I was a bit shocked that I can't easily answer questions similar to what @chriscct7 posted.

This is needed and would be killer! 💥

**Comment by michaelbeil** [comment]
I would really like to see this 2.7.

**Comment by pippinsplugins** [comment]
Due to our current data storage, it may be necessary for us to build this alongside #4678

**Comment by cklosowski** [comment]
We really need #4678 to do this properly. I'm going to put that in 2.7 and put this in 2.8. Just due to size constraints.

**Comment by sunnyratilal** [comment]
Implemented in:
- https://github.com/easydigitaldownloads/easy-digital-downloads/commit/5c6210cc1e6c7005d2b3b1b160fc4a901e37abf8
- https://github.com/easydigitaldownloads/easy-digital-downloads/commit/40738b6bc3bb5966e03d8a678dee438418a3bafd
- https://github.com/easydigitaldownloads/easy-digital-downloads/commit/f04cc989e3c23d68d071083d45d17bdcd36850dd

As part of #6298.
