### ISSUE TITLE
Typo in tracking admin notification

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/easy-digital-downloads#4905]
```
Opt-in to tracking and our newsletter and immediately be emailed a 20%% discount to the EDD shop
```

Shouldn't it be `20%` and not `20%%`?

**Comment by cklosowski** [comment]
Actually just realized, that is supposed to be there @slaFFik Since this is in a `sprintf` the `%` needs to be escaped and the way to do that is an additional `%`.

![screen shot 2016-08-26 at 9 48 43 am](https://cloud.githubusercontent.com/assets/1390124/18013320/552355b2-6b72-11e6-811b-85af0479ab5b.png)

![screen shot 2016-08-26 at 9 48 47 am](https://cloud.githubusercontent.com/assets/1390124/18013329/58b903e8-6b72-11e6-8dbb-d76a35b2b5e1.png)

**Comment by slaFFik** [comment]
Oh, I didn't know about such escaping of `%`. 
Then great. Because of this issue on github I learned something new :)
