### ISSUE TITLE
Price range shows default price instead of lowest price

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4968]
When showing a price range, the default price option is getting shown in the range instead of the lowest and highest options.

Reported here: https://secure.helpscout.net/conversation/253304396/42793/?folderId=180505

**Comment by cklosowski** [comment]
I'm not sure this is a bug @pippinsplugins, I believe this is an incorrect usage of functions by the theme. The same behavior displays on Vendd as well...but it's because Vendd is using `edd_price` not `edd_get_lowest_price_option` when variable products are in place.

If someone calls `edd_price` we should be returning the default price point.

![screen shot 2016-09-22 at 9 41 49 am](https://cloud.githubusercontent.com/assets/1390124/18757521/1912b1a2-80a9-11e6-9feb-da8ebf992f77.png)

![screen shot 2016-09-22 at 9 41 42 am](https://cloud.githubusercontent.com/assets/1390124/18757522/1d6cdd2c-80a9-11e6-8572-f329c09a80c4.png)

```
<?php if ( edd_has_variable_prices( get_the_ID() ) ) : ?>
	<a class="product-price-wrap" href="<?php the_permalink(); ?>"><span class="product-price"><?php _e( 'Starting at: ', 'vendd'); edd_price( get_the_ID() ); ?></span></a>
```

**Comment by cklosowski** [comment]
This is the logic inside of `edd_price` that we're focused on now:
```
		if ( false !== $price_id && isset( $prices[$price_id] ) ) {

			$price = edd_get_price_option_amount( $download_id, $price_id );

		} elseif ( $default = edd_get_default_variable_price( $download_id ) ) {

			$price = edd_get_price_option_amount( $download_id, $default );

		} else {

			$price = edd_get_lowest_price_option( $download_id );

		}
```

You'll see that we left the lowest price in there for backwards compatibility. When we released default price options, if a customer hadn't gone in and set a default, we had to fall back to something, which was lowest price. Anything created after that update always has a default price option, so that last clause was never there for functionality, but compatibility.

**Comment by pippinsplugins** [comment]
As long as `edd_price_range()` properly shows lowest and highest, I agree. Maybe reach out to the theme dev to let them know?

**Comment by spencerfinnell** [comment]
@cklosowski behavior was introduced in #4070

I think it should be adjusted in the theme -- if you're prefixing with a "Starting at:" then you should call `edd_get_lowest_price_option()` directly.

**Comment by cklosowski** [comment]
Thanks @spencerfinnell I knew it was wrapped in there somewhere Appreciate that detective work. @pippinsplugins `edd_price_range()` works as expected. I think it's just this case of using the wrong function. I'll get an issue opened up on Vendd, and work with the customer on getting in touch with that theme developer.

**Comment by cklosowski** [comment]
I've reached out to the theme developer via my easy digital downloads email address, I'm going to de-milestone this, and mark as a wontfix, but leave open so I can track the progress until it's been resolved on that end.

**Comment by cklosowski** [comment]
After over 2 years this hasn't come back up, closing.
