### ISSUE TITLE
record_fees clears fees in the session

### ISSUE THREAD

**Issue by ayvazj** [easydigitaldownloads/easy-digital-downloads#4987]
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/370d71d60a090ee167acc7ade2ce71114ea53cde/includes/class-edd-fees.php#L336

Calling $payment->save(); calls record_fees which then clears the fees associated with the session.  If the payment fails the fees are lost.

**Comment by pippinsplugins** [comment]
We should only clear the fees if the status is `complete`, `publish`, `failed`, or `revoked` I think.

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by SDavisMedia** [comment]
The fix is working for me.

Replicated on `master` by adding a product to the cart, proceeding to checkout, and having a discount (negative fee) automatically applied by RCP Member Discounts ... then refreshing the checkout page after running the following in Debug Bar Console (where `22` is the ID of my product):

```php
$p = new EDD_Payment();
$p->add_download( 22 );
$p->save();
```

I lost the fee after refresh on `master`. The fee stuck after refresh on `issue/4987`. :+1:
