### ISSUE TITLE
Payment date is not included in the payment history export

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4994]
The payment history export does not include the date even though a date column is present.

Looks like we need to look at `$payment->post_date` in: 

- https://github.com/easydigitaldownloads/easy-digital-downloads/tree/master/includes/admin/reporting/class-export-payments.php
- https://github.com/easydigitaldownloads/easy-digital-downloads/tree/master/includes/admin/reporting/export/class-batch-export-payments.php

**Comment by tomusborne** [comment]
I can confirm this. 

Went to report my monthly taxes tonight and tried to run it through my system only for it to fail due to no dates being output.

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by mintplugins** [comment]
Working great here. One thing I noticed is that the "status" column is "publish" instead of "Complete" (which is what I chose to export on the user screen). Is that a separate issue or could we/should we change that here?

<img width="150" alt="screen shot 2016-10-04 at 2 23 27 pm" src="https://cloud.githubusercontent.com/assets/1638128/19086979/5945f36c-8a3e-11e6-9a46-375f4856f393.png">
