### ISSUE TITLE
payment icons display for non-active gateways

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5134]
To replicate:

1. Enable 2Checkout
2. Check the box to display its icon on checkout (verify that it's there)
3. Deactivate 2Checkout, which means its icon checkbox will not longer be available to deselect in the settings
4. The icon will still show on checkout

I saw the same thing with Payza. Must be a missing check in core.

**Comment by pippinsplugins** [comment]
I don't think this is something to be changed in core.

The icons registered in core are not directly tied to individual gateways. The icons registered for 2Checkout and Payza are gateway specific mainly because they are included with those gateways.

It makes sense for those icons to only be registered if the gateways are enabled, but that should happen (if at all) in those gateways.
