### ISSUE TITLE
No-transient issue caused by W3TC causes update checks on every admin page

### ISSUE THREAD

**Issue by webzunft** [easydigitaldownloads/easy-digital-downloads#5294]
A lot of EDD users, especially those with the Software Licensing enabled use your class from https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/EDD_SL_Plugin_Updater.php.

This class is great (especially after a recent fix for duplicate requests), but there is one issue I see a lot with my own implementation and I bet it is happening here as well.

A lot of users requests updates on every admin page impression because transients are returning null due to an usage of the W3 Total Cache plugin.

It basically happens when "Object Cache" in W3TC is enabled and the problem is described in many threads, e.g. https://wordpress.org/support/topic/w3-total-cache-transient-admin-issue/.

A solution I believe might work would be to not use the Transient API. Maybe set an option like `edd_last_update_check` with the timestamp of the last check in it and then check and update it based on the expiry time. It can also be just an exception when Object Cache is enabled in W3TC, but I searched for months after the source why some users have a very slow backend after enabling our plugins and also generate plenty of calls to our store, while others don’t.

Since you actually use this class as an integration example for customers, I wanted to get your feedback before implementing my own hack to solve it in time.

**Comment by shazahm1** [comment]
I was experiencing the same issue with my commercial addon for my plugin. My site was be bombarded with update checks with sites running W3TC.

I ended writing a replacement upgrade check class which interfaced with WP REST API endpoints I wrote.

My replacement class, you can found here (which is a drop in replacement for the EDD-SL Plugin Updater):

https://github.com/Connections-Business-Directory/Connections/blob/develop/includes/admin/class.plugin-updater.php

Here's the link to my WP REST API endpoints required for my plugin updater class:

https://github.com/shazahm1/EDD-SL-Plugin-Update-REST-API

Instead of using transients, I use the option API, the same way WP core does to save its plugin updates meta using the same timeouts for the option, set using a time stamp (more or less). This prevents the double hit from the filter being run twice and limits update checks to only occur when needed.

I did a heck of a lot of testing before deployment and it has had a net positive effect. Unfortunately this does not and can not fix the users who have not updated so I still get a bunch of unnecessary updates checks but they are much more manageable now.

Oh, there is one issue... EDD-SL does have some logic to deal with licensing for WP multisite which I have not yet implemented in my plugin updater.

Not saying you should use my code as a solution, but maybe there's bit and pieces you'll find useful / or not.

Hope this helps!

**Comment by pippinsplugins** [comment]
It's definitely an issue we've run into several times.

I don't think there'd be any significant issues with switching to the options API in place of transients, though I'd rather see a fix that allowed transients to work as expected with W3TC. I've never been able to identify why they don't work properly.

Going to milestone this for shortly after 2.7 so we can get it looked at.

Note: we'll need to update the class included in core and the sample class distributed with Software Licensing.

**Comment by webzunft** [comment]
Thanks for your replies.

I would also like to get this fixed by W3TC, but there are a lot of threads for over two years about this and he rarely replies. So even if we found a fix in W3TC here, I don’t think it will be applied soon, hence we need to think about one on our end.

**Comment by shazahm1** [comment]
Maybe throw a performance compatibility issue or something if W3TC with Object Caching enabled. Or some how some other "silent" just works solution. Hoping for W3TC to fix it seems like a lost cause. Honestly, even though I invested the time to dev my own solution, I would still rather rely on the EDD-SL plugin updater. One of the motivating factors in making sure it was a drop in replacement, that was I could switch back.

**Comment by pippinsplugins** [comment]
We'll definitely fix the issue on our end, was mostly just voicing my frustration that a standard feature is broken by W3TC :)

**Comment by pippinsplugins** [comment]
PR submitted that should fix it: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5302

@easydigitaldownloads/core-devs could I please get some eyes and testing on this?

**Comment by SDavisMedia** [comment]
Everything is working well for me on `issue/5294`. :+1:

**Comment by sunnyratilal** [comment]
Tested and working all good here.

**Comment by webzunft** [comment]
I tested it with my own plugin and Software Licensing and that worked as well.

**Comment by pippinsplugins** [comment]
Thanks guys! This will get deployed for EDD core later today and in an update to Software Licensing later in the week.

**Comment by pippinsplugins** [comment]
Merged.

**Comment by pippinsplugins** [comment]
Note: the update for Software Licensing that includes this change has just been released.

**Comment by webaware** [comment]
@pippinsplugins transients auto-expire (with an object cache) or are purged ex-EDD (with a transient delete plugin). What cleans up these options e.g. when a licence changes, or plugin is deactivated?

(yes, I can add to my fork of this class, but it looks like you're creating more work for yourself down-track if you don't incorporate some means of cleanup in this class)

**Comment by webaware** [comment]
Further: code is currently using `json_encode()` / `json_decode()` which is fine if you're ignoring elements like `sections`. If, however, you're using those elements (I am) then those functions break the structure by converting the `sections` element from an array to an object. `serialize()` / `unserialize()` don't suffer that fault.

**Comment by pippinsplugins** [comment]
@webaware at the moment, nothing. They're not cleaned up but will need to be in the future.

Right now we chose the lesser of two evils:

1. Killing site performance for some sites
2. Leaving some data behind

**Comment by webaware** [comment]
@pippinsplugins perhaps in the short term at least, prefix them all with something. I can add a feature to my [Delete Expired Transients](https://en-au.wordpress.org/plugins/delete-expired-transients/) plugin to deal with it. It's bound to be very minor, perhaps not something worth burdening the updater class with, so I can bundle it in to my cleaner and perhaps other cleaner plugins can do the same.

I already handle NextGEN Gallery transients-in-options and old-style WooCommerce sessions. No drama to add another specific one, perhaps just for manual runs like the WooCommerce sessions one.
