### ISSUE TITLE
Dashicons is a large dependency for one icon

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/easy-digital-downloads#5331]
As far as I can tell dashicons are only being enqueued to show the padlock on the checkout form. That is a 28.6 kB file for one icon. I think it would make sense to use an inline svg, or maybe add a cut down version of dashicons to main stylesheet.

**Comment by samikeijonen** [comment]
I have a big PR on front-end stuff which includes this. Juat

**Comment by samikeijonen** [comment]
I have a big PR on front-end stuff which includes this. Juat

On Jan 3, 2017 12:06 AM, "Josh Pollock" <notifications@github.com> wrote:

As far as I can tell dashicons are only being enqueued to show the padlock
on the checkout form. That is a 28.6 kB file for one icon. I think it would
make sense to use an inline svg, or maybe add a cut down version of
dashicons to main stylesheet.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5331>,
or mute the thread

**Comment by samikeijonen** [comment]
Ups... Just need time to finish it.

**Comment by Shelob9** [comment]
@samikeijonen That's good to hear. I de enqueued it on our site. I used a PNG icon instead.

Question: Should I open issues in other plugins that are doing this (I think it was EDD Recurring and AffiliateWP that I saw, but will have to check) or is that part of your plan?

**Comment by samikeijonen** [comment]
Here is the PR: #5177.

> Should I open issues in other plugins that are doing this (I think it was EDD Recurring and AffiliateWP that I saw.

I'd say yes if they are using Dashicon in different place than in EDD Core. Naturally AffiliateWP is a different story:)

**Comment by sunnyratilal** [comment]
Closing as this was fixed in #5166
