### ISSUE TITLE
Payment mode fieldset is missing legend tag.

### ISSUE THREAD

**Issue by mikemcalister** [easydigitaldownloads/easy-digital-downloads#5339]
On the checkout page, the payment method box is missing a `<legend>` tag on the 'Select Payment Method' title. The other `<fieldset>` tags on the checkout have proper legend tags, but the payment mode does not. For any given `<fieldset>` there should always be one associated `<legend>` tag.

This is the markup for the payment method fieldset: 

<img src="https://d3vv6lp55qjaqc.cloudfront.net/items/0X2a422Y0G1e1G213v2W/Image%202017-01-03%20at%202.12.36%20PM.png" />

and this is the markup for the rest of the fieldsets: 

<img src="https://d3vv6lp55qjaqc.cloudfront.net/items/0I2Y233R0g0J0l0b1D2e/Image%202017-01-03%20at%202.12.59%20PM.png" />

Anything we can do to ensure this is consistent across the checkout page? Thanks in advance!

**Comment by pippinsplugins** [comment]
We'll get this taken care of soon after 2.7. Thanks!

**Comment by pippinsplugins** [comment]
The `legend` should always be the top-most element in a fieldset. Doing that here would require that we move it outside of the `edd-payment-mode-wrap` div, which could cause unexpected changes.

@mikemcalister do you, as a theme dev, have a preference here? @SDavisMedia same question to you.

**Comment by SDavisMedia** [comment]
My preference is to just introduce the unexpected changes. It could sting for a second but sooner or later, we'll need to correct it. 

`.edd-payment-icons`, `#edd_payment_mode_select`, and `#edd_payment_mode_submit` really deserve to be in their own div on the same level as `#edd_purchase_form_wrap`. Then with properly structured HTML in all of them.

That's my vote.

**Comment by pippinsplugins** [comment]
I'm fine with that.

**Comment by ghost1227** [comment]
@SDavisMedia when you have a moment, can you ping me on this issue (unless you just want to fix it yourself). I'm far from an optimal frontend dev, I'd trust your guidance much more than my own limited knowledge on something like this.

**Comment by mikemcalister** [comment]
Sorry for the delay here. I agree with Sean though, that this is going to have to be corrected for consistency. It would be better to fix it now than have more users create workarounds that need to be removed later. Thanks folks!

**Comment by ghost1227** [comment]
@mikemcalister all good!

**Comment by SDavisMedia** [comment]
@ghost1227 I'll explain in a little more detail what I think should happen. See the current markup below:

<img width="726" alt="screenshot 2017-03-06 09 59 05" src="https://cloud.githubusercontent.com/assets/2359131/23622448/91147218-0253-11e7-87b4-c8c45fbc1a91.png">

Take note of `#edd_purchase_form_wrap` and its child elements. This is the _correct_ structure. The fieldset's (`#edd_checkout_user_info`) first child element is a legend. That's good and that's what we want for all fieldsets. Also note that this fieldset is inside of a div (`#edd_purchase_form_wrap`) that is a direct child to the form element. This just keeps things organized.

The problem is that the fieldset for the payment method switcher (`#edd_payment_mode_select`) does not follow this structure. For one, its first child element is not a legend. The legend should really be `Select Payment Method`, but that's currently deeper into the markup and wrapped in spans. No good. Not only that, that fieldset is closely related to its two adjacent siblings. So it would make a lot of sense to wrap them in a new div all together, so that div can be a sibling to `#edd_purchase_form_wrap`.

So what needs to be done is pretty straightforward. 1) Make sure fieldsets have legends as their first child. 2) Gather up "loose," related elements and put them in one container, just like the purchase form is.

**Comment by ghost1227** [comment]
@SDavisMedia based on what you commented, i think that PR does what you're looking for. Looks correct on my end and everything works as expected.

**Comment by SDavisMedia** [comment]
That's looking perfect to me. :+1:

**Comment by SDavisMedia** [comment]
@spencerfinnell

**Comment by pippinsplugins** [comment]
Please test with and without ajax enabled (will have to use the filter to disable it).,

**Comment by SDavisMedia** [comment]
Actually no. The gateway switcher actually isn't switching the purchase form for me at all. For example, no CC form shows up when I switch to Stripe.

And no, it doesn't appear to work with AJAX disabled.

**Comment by SDavisMedia** [comment]
Good call. It's not working for me with AJAX disabled. @ghost1227

**Comment by SDavisMedia** [comment]
Turns out the checkout not working when AJAX is disabled was introduced with EDD 2.7. It is not related to this issue.

**Comment by mintplugins** [comment]
Confirmed AJAX does not work on EDD2.7.

**Comment by pippinsplugins** [comment]
@SDavisMedia @mintplugins ok so are we good to go here from your perspectives then?

**Comment by SDavisMedia** [comment]
@pippinsplugins yes :+1:
