### ISSUE TITLE
Problems with the custom taxonomies of EDD

### ISSUE THREAD

**Issue by colomet** [easydigitaldownloads/easy-digital-downloads#5420]
Related: github.com/Yoast/wordpress-seo/issues/ #[5266](https://github.com/Yoast/wordpress-seo/issues/5266) #[6539](https://github.com/Yoast/wordpress-seo/issues/6539) and #[6538](https://github.com/Yoast/wordpress-seo/issues/6538).

From yoast plugin:
_Worth nothing on part of the issue here is that EDD should not set a width on the primary column. The standard in WP is to set a width on all columns except the primary one._

**Comment by SDavisMedia** [comment]
We do need to find a better way to handle this. It's a super tight space but right now our columns are defined to take all of it. That's not a flexible approach.

**Comment by SDavisMedia** [comment]
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/css/edd-admin.css#L855

**Comment by rahilwazir** [comment]
Why the width is set for each column in the first place?

If we see columns for posts or products (WC) it displays just fine, except it eats up `n` character from the word `Description`

![woocommerce](https://cloud.githubusercontent.com/assets/1818941/26027930/45b2d6b2-3830-11e7-8f0b-bb4b159be5e9.png)

It's only because of the extra **Image** column.

Some EDD addons have added custom columns to the `download_tag` and `download_category` taxonomies, like EDD Points and Rewards.

![points_rewards](https://cloud.githubusercontent.com/assets/1818941/26027963/d8492ef4-3830-11e7-979c-64ac5aa80092.png)

**Comment by SDavisMedia** [comment]
I'm proposing that we just stop the defined widths here. They don't add much benefit, but they hurt a _lot_ when other plugins modify the table... which they should be able to do in pease.

Yoast has already made [great adjustments](https://cl.ly/2p1w1s1T0u2u) that help with the aforementioned "conflict." But really, we just need to get out of the way and let the table flow. WordPress itself defines a couple of column widths, but that's fine.

Our Points & Rewards extension defines some widths, so we can get that removed as well. There's nothing wrong with the final result:

<img width="865" alt="screenshot 2017-08-04 10 10 36" src="https://user-images.githubusercontent.com/2359131/28979104-52a635a4-78fd-11e7-877a-2d4f259c23a7.png">

Sure, the Description column can end up skinny and tall if the term has a description. But if you don't want to see it, you can just go up to the Screen Options and disable the display.

So yea... let's get out of the way.
