### ISSUE TITLE
Fees that are taxed are being counted twice in the tax total

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5549]
For example, with simple shipping:
$5.00 product
$2.00 shipping
10% tax rate

Expected: $7.00 + $0.70 = $7.70
Actual: $7.00 + $0.90 = $7.90

![screen shot 2017-03-07 at 9 56 34 am](https://cloud.githubusercontent.com/assets/1390124/23668071/232e79c2-031d-11e7-8993-b61681777934.png)

**Comment by SDavisMedia** [comment]
The interesting thing here is that the issue is corrected in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4833. With the cart configuration above, you can checkout `issue/4833` and see the correct amount.

With that, I think it's best either you or @pippinsplugins have a dedicated session with me over issue 4833. It's stuck in place right now because it reveals some deeper problems. I need help mapping those problems out so we can get issues created and tackle everything at once.

**Comment by cklosowski** [comment]
Interesting @SDavisMedia.

Have you tried merging `master` back into your branch to see if EDD_Cart has made your information clean up?

**Comment by SDavisMedia** [comment]
@cklosowski I have not, actually. I'll do that and let you know if it's still fixed. 😳

**Comment by SDavisMedia** [comment]
Merging master broke it but I'm pretty sure it's because I made some important adjustments to functions that were also changed thatnks to EDD_cart. Kinda feeling like I need to do `issue/4833` again now. But it would probably make more sense to fix whatever's happening here first. :/

Carry on, unless you disagree.

**Comment by pippinsplugins** [comment]
@SDavisMedia @cklosowski could I please get a test on this?

**Comment by cklosowski** [comment]
Seems to fix it for me @pippinsplugins.

**Comment by SDavisMedia** [comment]
Looking good for me as well. :+1:

**Comment by ghost1227** [comment]
@pippinsplugins Since this is the last issue for release, I ran a quick test too. All good here!

**Comment by pippinsplugins** [comment]
Unit tests are failing.

**Comment by pippinsplugins** [comment]
@cklosowski I can't find any reason these tests are failing. See anything?

**Comment by sunnyratilal** [comment]
@pippinsplugins Looks like Travis was having issues fetching WordPress - I've restarted the build

**Comment by pippinsplugins** [comment]
@sunnyratilal :+1:

**Comment by pippinsplugins** [comment]
@cklosowski looks like your change did it, though I think that fix implies there's an underlying bug in the code if setting price ID to 0 was necessary.

**Comment by cklosowski** [comment]
The bug is in that we manually added the price ids to the post meta instead
of the interface which sets a dfault price id. If we set that in the setup
method of the tests we'd be fine.

**Comment by pippinsplugins** [comment]
Let's get the PHP7 fix included in the PR then merge it in.

**Comment by pippinsplugins** [comment]
Merging into master then will get PHP7 fixed there.
