### ISSUE TITLE
Subsites receive usage tracking discount when network site opts into tracking

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5587]
When using a multisite install and having EDD network activated, opting into usage tracking on the network site causes the creation of each subsite to generate a usage tracking discount.

**Comment by cklosowski** [comment]
Thinking on this, I think it needs to be done within the EDD Site's server side that collects data, not the client side. We'd still like to receive the data from the child sites, however, we should limit it so that if the subsite has the same base domain and email address then we don't generate a code for it. Does this seem logical @pippinsplugins @SDavisMedia?

If that's the case, then all the work is done in the server side, not EDD Core.

**Comment by pippinsplugins** [comment]
Yes, I agree.

**Comment by SDavisMedia** [comment]
No issues with here. :+1:

**Comment by cklosowski** [comment]
Cool, going to close this here and make an issue in our Usage Tracking server side plugin.
