### ISSUE TITLE
edd_has_user_purchased() needs to stop searching once valid item is found

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5605]
The `edd_has_user_purchased()` loops over a user's purchases and then sets `$return` to `true` when it finds a purchase of the specified download ID / price ID. The final return value, however, can be incorrect because the function doesn't stop looping over once it has found a valid result, allowing it to potentially return `false` when really it should return `true`.

For example, a customer purchases Price 1 of Product ID 200 and then later purchases Price 2 of Product ID 200. Calling `edd_has_user_purchased( $user_id, 200, 1 )` could return false instead of true because the function first finds the valid purchase of price 1, setting `$return = true` but then also finds the purchase of price 2, setting `$return = false`.

To resolve this, we should break out of the foreach loops as soon as we have found a matching purchase.

**Comment by pippinsplugins** [comment]
Note: this change is also necessary so we can ensure the return value is always passed through the new `edd_has_user_purchased` filter added in #5511.

**Comment by SDavisMedia** [comment]
The function continues to work as expected for me on `issue/5605`. :+1:

However, I do find it strange that I couldn't replicate an issue. On `master` with a variable pricing product, I purchased price ID 1 and price ID 2, then ran the following:

```php
$me = get_current_user_id(); 
$purchased = edd_has_user_purchased( $me, array( 62 ), 1 );
var_dump( $purchased );
```

`$purchased` always returned `true` when based on the logic, it should have returned false... since the value I passed for the price ID to check would not match my purchase of price ID 2 when its reached in the loop.

So not sure what I'm missing in replication. But yes, `issue/5605` works as expected.

**Comment by SDavisMedia** [comment]
Eh... I think `edd_has_user_purchased()` needs an improvement. Take this example:

```php
$me = get_current_user_id(); 
$purchased = edd_has_user_purchased( $me, array( 62, 29 ), 3 );
var_dump( $purchased );
```

This is the same scenario as above but I have added an additional single price download (`29`) to check for, which I have purchased, and I have _not_ purchased price ID 3 of the original product (`62`).

_Because_ I passed a price ID to `edd_has_user_purchased()`, this conditional evaluates as true but then returns false because I have not purchased price ID 3 of download ID `62`. I _have_ purchased download ID 29, though.

Is `edd_has_user_purchased()` supposed to check for all download IDs passed in the array and return true if _any_ of them have been purchased? Because if so, the aforementioned scenario breaks it. If the functions is supposed to check if _all_ of the download IDs have been purchased, ignore me.

**Comment by pippinsplugins** [comment]
@SDavisMedia I agree but that's going to be a separate change. I'd actually like to eventually completely remove this function and replace it with a better one that looks at the customer record instead of the user record. I'd also like to make it a _lot_ more flexible and efficient.

**Comment by SDavisMedia** [comment]
@pippinsplugins sweet dealio! Then everythings working as expected for me on `issue/5605`. :+1:
