### ISSUE TITLE
Download history report improvements

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5617]
While the download history report is useful, I feel the following data/columns would improve it further:

- Browser User Agent
- ~Download/File Size (if available)~
- Purchase/Order IP (this is useful for finding customers sharing download links)

**Comment by cklosowski** [comment]
I see no issues with Browser User Agent and Purchase/Order IP.

We're not currently storing the file size however in any logs so we'd have to find a way to store that, and use it going forward with backwards compatibility for download history that contains files downloaded before the addition of this meta.

According to PHP Docs the results of a `filesize` call are stored in the local filesystem cache, so there isn't a major performance hit there (at least after the first time it happens), but there is some concerns on 32bit servers that serve files over 2GB in that it will throw unexpected file size results thanks to 32bit integers. I think for now, simply getting the UA and Purchase/Order IP into the report would be a good start.

**Comment by cklosowski** [comment]
The real major concern here is hitting filesize on external files. I think it'd work great for locally delivered files, but for things like S3 and URLs it would actually be a performance hit because before we deliver a file, we have to download it to the server via a stream and calculate the size before delivering it to the requested user...who then has to download it again. This is where the major concern of file size comes into play.

Imaging clicking to download a 500MB file from a site running EDD, but before EDD Delivers it to you, it has to download it, calculate the file size, record it, and then send you to the 500MB file. We've now hit 1000MB of S3 traffic for no other reason than a log entry.

**Comment by davidsherlock** [comment]
Almost finished this and will submit PR soon:

![screenshot 2017-11-02 02 03 28](https://user-images.githubusercontent.com/22668877/32306226-0afa1fca-bf72-11e7-8581-d1d9e051b0b1.png)

Added support to all required classes and functions, including download logs to make it easy to spot malicious intent.

**Comment by cklosowski** [comment]
I'm not sure why this exists on the payment (as shown in the screenshot) this is supposed to be for the file download logs.

**Comment by davidsherlock** [comment]
Why not? It's used by Stripe and various other fraud protection systems as a parameter and thus is useful to store at payment level.

**Comment by davidsherlock** [comment]
As a side note, the following library is required to parse and provide 'friendly' user agent strings: https://github.com/tobie/ua-parser

**Comment by cklosowski** [comment]
This ticket is for file download logs. Of which a single payment can have
many file download logs.

Adding in a user agent for the payment is not in the scope of this issue.
If you are now logging the user agent if the purchase that's a separate
issue. If you are showing the user agent of the file download logs what
agent do you show? All? Last one? First one?

The data becomes endless as it's a many to one, and therefore should exist
withing it's own data set.

On Nov 1, 2017 7:13 PM, "David Sherlock" <notifications@github.com> wrote:

Why not? It's used by Stripe and various other fraud protection systems as
a parameter and thus is useful to store at payment level.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5617#issuecomment-341297714>,
or mute the thread

**Comment by davidsherlock** [comment]
@cklosowski, I understand what you are saying but I am recording the user agent at the time of purchase as a separate data point (_edd_payment_user_agent). File download "logs" user agents are recorded independently for each download attempt.

I will open a separate ticket to avoid confusion, I get your point of clarification here.

**Comment by cklosowski** [comment]
@davidsherlock Thanks, it's not that I'm opposed to the idea, but making sure we keep scope in mind is important for historical and testing reasons.

**Comment by cklosowski** [comment]
@davidsherlock is there another UA parser we can look for? This one, while useful, will increase the EDD package size by 9% alone (492kb). EDD without all the languages included is only about 5.4MB.

**Comment by davidsherlock** [comment]
Not that I am aware of, the largest part of the UA parser is the `spyc-0.5` folder (111kb).

I will spend time tomorrow searching for something lightweight, I agree the size is a bit OTT.

**Comment by davidsherlock** [comment]
Found a more lightweight solution: https://github.com/donatj/PhpUserAgent

**Comment by davidsherlock** [comment]
This is a good solution, going to fork it (since it's only 1 function) and modify it for our needs.

**Comment by davidsherlock** [comment]
Will finalize the code tomorrow, but here is what it looks like so far:

![Uploading Screenshot 2017-11-02 03.20.31.png…]()

**Comment by cklosowski** [comment]
Feel free to open a PR and preface it with WIP. Will make it easier to
follow and grok the changes.

**Comment by sunnyratilal** [comment]
Merged.
