### ISSUE TITLE
API returns incorrect earnings stats for "today"

### ISSUE THREAD

**Issue by jonmarkhall** [easydigitaldownloads/easy-digital-downloads#5648]
Calling the stats API with the following parameters results in incorrect output (tested with v2.7.7):
https://example.com/?edd-api=stats&key=XXXXXX&token=XXXXXX&type=earnings&date=today. The amount returned reflects only partial sales for the day.

Reason: in includes/payments/class-payment-stats.php, stats are grouped by hour (in addition to date) if the date range is "today" or "yesterday" (line 293):

```
if ( $range == 'today' || $range == 'yesterday' ) {
	$grouping = "YEAR(posts.post_date), MONTH(posts.post_date), DAY(posts.post_date), HOUR(posts.post_date)";
}
```

In includes/api/class-edd-api.php, only the first of these hourly totals is used (line 1403):

`$earnings['earnings'][ $args['date'] ] = $results[0]['total'];`

**Comment by sunnyratilal** [comment]
Hi @jonmarkhall, I've just tested this and it works great when a `date` parameter is passed but there is still a bug when just querying `earnings` without any `date` parameter attached to the query.

i.e.
`http://edd.dev/edd-api/v2/stats?key=e1ece414628526bd5c80de414a0c1d8b&token=78784af9e4c54235e298a91c4cd505f4&type=earnings&date=today` works perfectly 👍 

**but**
`http://edd.dev/edd-api/v2/stats?key=e1ece414628526bd5c80de414a0c1d8b&token=78784af9e4c54235e298a91c4cd505f4&type=earnings` displays incorrect data for `today`

Would you be able to make the changes to the PR to get it working for the main `earnings` query too please?

Also, could you change the branch so that we receive the PR because with the current PR, we can't merge it in to our repository - you have it to set it to merge into `master` of your forked repo.

Thanks!

**Comment by jonmarkhall** [comment]
@sunnyratilal I wasn't able to reproduce the issue with omitting the date parameter. If no date is specified, stats are calculated by EDD_Payment_Stats::get_earnings(), whereas stats with a "today" date parameter are calculated by EDD_Payment_Stats::get_earnings_by_range(); the issue was caused by the latter method.

My bad about the PR, should be done properly now - #5656.

**Comment by sunnyratilal** [comment]
@jonmarkhall Thanks for the PR - just tested and it's all good.

The reason I was having the issues without the `date` parameter was due to caching of the API response data.
