### ISSUE TITLE
Discounts with multiple exclusions can be applied to excluded products

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#5684]
When a discount code has multiple downloads excluded, the code can be applied on the checkout when an excluded item is in the cart. The total amount isn't reduced, but the discount code is attached to the payment and counted as being used.

Steps to reproduce:
- Create new discount code, add multiple items to the Exclude Downloads list.
- Add one of the excluded items to the cart.
- Apply the discount code. Note that the code is applied.
- Complete purchase.

When viewing the payment details, you can see the code attached to the payment. The discount code's uses count is increased as well.

When a discount code has only one exclusion, it is properly blocked from being applied.

**Comment by sunnyratilal** [comment]
PR opened at #5910

**Comment by SDavisMedia** [comment]
I'm not sure this is a bug. Either that or I'm misunderstanding how it _should_ work. I'm on `master`.

Let's say your store has 3 products: **Product A**, **Product B**, and **Product C**. Each one costs $100.

You create a 50% discount code has two exclusions: **Product A** and **Product B**.

You add all three products to you cart and apply your discount code of 50%. The discount is applied to the cart (which I believe we are saying is a bug here?), but the cart is only reduced by $50... which is 50% of the only eligible product: **Product C**. The cart goes from $300 to $250.

Isn't that the intended behavior? `issue/5684` changes this behavior and blocks the discount completely, instead of allowing it to apply to products that _aren't_ excluded.

To be sure I wasn't misunderstanding the description of the bug, I tested purchasing just **Product A** and **Product B** with the discount. The discount is blocked, as expected.

**Comment by sunnyratilal** [comment]
@SDavisMedia You are correct - I need to fix the logic here.

The bug was that the discount was being attached when it should have been blocked, i.e. in your case, trying to purchase **Product A** and **Product B**.

**Comment by sunnyratilal** [comment]
@SDavisMedia I've fixed up the logic

**Comment by SDavisMedia** [comment]
@sunnyratilal I'm reluctant to get into testing the issue branch because I actually can't replicate the issue you all are describing.

Discount config:
<img width="636" alt="screenshot 2017-07-30 10 52 00" src="https://user-images.githubusercontent.com/2359131/28755688-31476d92-7515-11e7-9112-6a6a5817a3b1.png">

Just those two items in the cart:
<img width="754" alt="screenshot 2017-07-30 10 53 13" src="https://user-images.githubusercontent.com/2359131/28755699-5101ee32-7515-11e7-8a32-093314b4e732.png">

Additional item in the cart that is not excluded:
<img width="749" alt="screenshot 2017-07-30 10 54 08" src="https://user-images.githubusercontent.com/2359131/28755704-6da6e2fe-7515-11e7-92a8-0e71c23d881c.png">

----

You're getting different behavior?

**Comment by sunnyratilal** [comment]
@SDavisMedia Firstly, apologies for the confusion here.

I'm getting the same behaviour but the screenshots you've provided **is** the intended behaviour.

Let me try and explain the bug at hand:

I have a discount code configured like so:
![image](https://user-images.githubusercontent.com/1525554/28755746-94cd3d9e-7559-11e7-9eea-eaf8a93844fd.png)

The bug is presented here:
![image](https://user-images.githubusercontent.com/1525554/28755759-d966251a-7559-11e7-945f-dcb12d4d67cf.png)

I've added only one of the excluded downloaded to the cart and then applied the discount code. Albeit the total hasn't been adjusted, the discount is still attached to the payment which subsequently increases the discount usage count.

It should be noted that even on `master`, when **both** the excluded downloaded are added to the cart, the correct error is displayed.

The correct behaviour (on `issue/5684`) is like so:
![image](https://user-images.githubusercontent.com/1525554/28755780-1350ce38-755a-11e7-98d9-c7e5127d5c12.png)

**Comment by SDavisMedia** [comment]
Ah! Reading John's steps incorrectly. My mistake! `issue/5684` fixes the reported bug and your second logic adjustment keeps the expected behavior in place. All good here. :+1:

**Comment by pippinsplugins** [comment]
@sunnyratilal only item I see is regarding whitespace. We like code that _breathes_ so please leave whitespace in tact :)

**Comment by SDavisMedia** [comment]
This is good to merge now. https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5910
