### ISSUE TITLE
file included twice

### ISSUE THREAD

**Issue by cdillon** [easydigitaldownloads/easy-digital-downloads#5762]
includes/misc-functions.php is included twice in Easy_Digital_Downloads::includes()

**Comment by chriscct7** [comment]
@cklosowski Just a note, the second misc-functions.php was added during a change to the Amazon payment gateway and it was deliberately placed above the inclusion of the Amazon gateway. This is the one that has been removed. Someone might want to test to ensure that gateway file doesn't need misc functions to be declared before it is included since that class self-instantiates upon inclusion.

**Comment by cklosowski** [comment]
@chriscct7 that makes sense. I'll do that. I confirmed it looked like things _were_ working just fine, but better safe than sorry.
