### ISSUE TITLE
Add inline docs for why edd_payment_meta filter is applied twice

### ISSUE THREAD

**Issue by ericnicolaas** [easydigitaldownloads/easy-digital-downloads#5838]
It strikes me as odd and misleading that the `edd_payment_meta` filter is applied twice: 

* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-edd-payment.php#L594
* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-edd-payment.php#L1036

The result is confusing for 3rd party developers, since the filtered data included when the filter is called from `EDD_Payment::insert_payment()` is an empty array.

I found this because the EDD Taxamo integration is hooking into `edd_payment_meta` and firing notices because the data is coming through empty. See https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/blob/master/taxamo-edd-integration.php#L478

**Comment by cklosowski** [comment]
@ericnicolaas This exists twice as a form of backwards compatibility

Pre `EDD_Payment`, all payments were created with the `edd_insert_payment` function, and this call was made:
```
// Record the payment details
edd_update_payment_meta( $payment, '_edd_payment_meta',         apply_filters( 'edd_payment_meta', $payment_meta, $payment_data ) );
```

This exists in two places because they are run at two specific points during the process. If we only run it on line 1036, then the data cannot be filtered as it previously was during inserting (at the appropriate time), and if we do not filter on 1036, it causes a problem with saving meta when updating a payment that already exists ( See #5490 )

**Comment by cklosowski** [comment]
:+1: Good idea @ericnicolaas I'll alter the title of this and get an issue in to comment the Backwards Compatibility notes.
