### ISSUE TITLE
Variations of searched for downloads attached to bundles not saving

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5874]
Reported by [a customer](https://secure.helpscout.net/conversation/397168536/63004/?folderId=448801) and replicated by me. Here's how to replicate:

1. Make sure you have more than 30 downloads in your store
2. Make a download that is not one of the first 30 alphabetically have variations
3. Create a bundle download and attach variation of the previous download ( you will need to search for it because it won't be in the select dropdown )
4. Save the bundle download

You should observe that your selection no longer shows in the product select input for the bundle download. Something like [this](https://cloudup.com/cFZ17UzocKl).

**Comment by sunnyratilal** [comment]
@brashrebel I've tried with a store of over 200 downloads but can't replicate this.

**Comment by SDavisMedia** [comment]
@sunnyratilal This was fixed in 2.8.1. It happened to be discovered right before 2.8.1 was released. @cklosowski fixed it on the spot and released it. https://github.com/easydigitaldownloads/easy-digital-downloads/commit/bf53d07bf852dabd26e23cb8900813376c5095c7

Neither of us made the connection to @brashrebel's issue. Oops! This issue can be closed.
