### ISSUE TITLE
Cart recovery requires login when it could be smoother

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5926]
Currently, if you are recovering a cart and are logged out, you are required to login - even if guest mode is enabled. 

@pippinsplugins suggested that we only require login if the email entered on checkout is different than the one attached to the cart recovery payment record. 

The arose out of [this ticket](https://secure.helpscout.net/conversation/407870291/64228/?folderId=749231), where the customer noticed that they have to login (guest mode enabled), if they cancel while at paypal and then immediately try and checkout again.

**Comment by SDavisMedia** [comment]
- [ ] update this doc once enhancement is made: http://docs.easydigitaldownloads.com/article/1926-login-to-complete-payment

**Comment by cklosowski** [comment]
@pippinsplugins @mintplugins What if a payment was `started` while logged in?

**Comment by pippinsplugins** [comment]
As long as the email entered still matches the account, I don't see any reason it's an issue. If they haven't verified their account, they'll just be asked to verify it after completing the purchase.

**Comment by cklosowski** [comment]
So that works, I tested out logged out, with guest mode, cancelling at PayPal and coming back to checkout using both the same AND different email and it all works.

The only time this catches the message if the payment was `started` while the user was logged in.

**Comment by cklosowski** [comment]
I'll see if I can get the email address matching involved.

**Comment by cklosowski** [comment]
Ok, this fix does a couple of things:
1) The notice that displayed when visiting a cart recovery now only shows if the following criteria are met:
1a) Guest checkout is disabled, and the user is logged out
1b) If 1a is met, the User ID on the payment is greater than 0 (wasn't a guest checkout)
2) Upon submitting a recovered payment:
2a) `is_user_logged_in() && ! $same_user`
2b) `! is_user_logged_in() && ! $same_email`

**Comment by cklosowski** [comment]
The above logic checks should allow this work flow:
1) Start purchase with logged in user
2) Get to PayPal and cancel
3) Go to Payment History in admin and copy the Recovery URL for the pending payment
4) Go to incognito browser and paste Recovery URL
5) Complete checkout...
5a) With a different email address than originally used on payment (should fail)
5b) With the same email address than originally used on a payment (should succeed)

**Comment by SDavisMedia** [comment]
Not sure why this one working as expected excites me so much. But ... :tada:

I tested exactly what you mentioned here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5926#issuecomment-322308289

I also tested starting a guest purchase while logged out/incognito, ditching the purchase, then using the recovery URL to continue to logged out/incognito purchase. The error is thrown if the email is different. The purchase process continues if the email matches. :+1:

Only one gripe, if it's possible to do something about it. When the purchase is blocked because of the emails not matching, it's now an EDD error down by the purchase button. Is there any way we can still use the notice for logging into the account, which provides a link and login form?

**Comment by cklosowski** [comment]
@SDavisMedia i'll see what I can do about that.

**Comment by cklosowski** [comment]
Ok after a long discussion between @mintplugins @SDavisMedia and I, here is where we're going to go with this iteration of improvements.

1) The login form at the top of the page will not show at this point. Since we want to allow a logged out use to recover a payment while logged out, but using the same email address, we don't need to show that.
2) If the user visits a recovery URL while logged out and tries to purchase with a different email, an error message is thrown (since we don't have a GREAT way of presenting the login form at this time, we're going to avoid showing it, but this case is the rarity of the support requests, which is point 3)
3) If the original payment was made in guest mode (no user ID), and the recovery is attempted while logged out, we simply don't care about the email address at this point, and process the payment
3a) Still to confirm here is that if a different email is used during the recovery checkout of a guest purchase, does that email address create a new customer, or attach this 2nd email address as an additional email to the customer generated during the first 'abandoned' checkout.

**Comment by SDavisMedia** [comment]
All of that is correct. The biggest "what to do?" here is the 3a scenario. Everything else is on point.

**Comment by mintplugins** [comment]
Awesome. 

I think for 3a, perhaps for security purposes it should become an entirely new customer.

**Comment by cklosowski** [comment]
As a note here...Auto Register will auto attach a new user ID to the payment, even if they cancel at PayPal...so there is a case where the person might have a login without realizing they have a login (realized as my other test site had auto-register enabled)

**Comment by cklosowski** [comment]
Just ran through and verified that the existing customer (from the abandoned purchase) remains the customer on the recovered purchase, the email address is not added to the customer record, and only exists on the purchase data (`_edd_payment_user_email `), so we'll need it to create a new customer with the email address provided at checkout, not re-use the customer.

**Comment by mintplugins** [comment]
This looks really good to me for both guest mode and non-guests. It only shows me the message that I need to login if I had a user account, logged out, and entered a different email at checkout. Otherwise I went straight to paypal. 

As a guest, it just makes a new customer if I cancel and return and enter a new email address. Very smooth now. 👍
