### ISSUE TITLE
FES Variable prices, exclude price

### ISSUE THREAD

**Issue by zeromajstor** [easydigitaldownloads/easy-digital-downloads#5966]
Hi,

I dont know if this is the right place to post but since FES is hasn't got is topic I decided to post here. For example if you use variable prices for product and you have options for example (Gold, Bronze, Silver). If vendor types price for Gold and Bronze and leaves Silver on 0.00 $, how to make it that option Silver doesn't show up on website (in product details), so its not available for purchase. 

What I am trying to say is that there should be a way not to show variable option if vendor didn't input any price for that option or he typed 0.00$ as price (he doesnt want to sell that option for example).

Maybe I miss it somewhere to turn that option or it can be done by adding some code to functions.php?

Thank you

**Comment by cklosowski** [comment]
@zeromajstor This repository is used for tracking EDD Core development issues only. For issues with FES please submit your requests to:
https://easydigitaldownloads.com/support

**Comment by zeromajstor** [comment]
This is related to EDD, not FES necessary I just wrote it since it is using it also. EDD also has variable pricing.

**Comment by cklosowski** [comment]
Since EDD core supports things like $0 price options at it's core, and many users use this feature it's really something that should be included in FES to prevent the case you have above, which is why I suggest that it goes into the FES queue.

It's not a feature that I think will be added to EDD Core as it could create some confusion.

This can already be done in EDD Core via a filter that is run just prior to outputting the variable pricing options for the purchase links:
`$prices = apply_filters( 'edd_purchase_variable_prices', edd_get_variable_prices( $download_id ), $download_id );`
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/template-functions.php#L254

**Comment by zeromajstor** [comment]
Cant some code like that be done also for FES then, since FES is also using EDD core options/settings?
