### ISSUE TITLE
Existing user can not purchase if used a different email before

### ISSUE THREAD

**Issue by webzunft** [easydigitaldownloads/easy-digital-downloads#5968]
I am the admin of my site and just wanted to make a purchase.
On the checkout, I received the `The email address %s is already in use.` error when using my WP user email address, which is also set in `wp_users`.

Looking into [edd_checkout_check_existing_email](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/70f807ee026ac1a9406d356ffd937251a03371a7/includes/process-purchase.php#L186) and logging the output, I saw that `$customer->email` is actually different from the email address used. Checking further, I noticed that I must have used a different email once for a purchase and there is an entry in `wp_edd_customers` with the same user ID, but that different email address.

I didn’t check further, but suspect that you are changing the customer’s email address when he enters a different one in checkout, which I think should not be possible when a logged in user visits the checkout. Can anyone reproduce the problem or is it one on our end only?

Update: I just found two entries in `wp_edd_customers`with the same user IDs. I guess this is a bug, but since the account was created more than two years ago, it might have been fixed. Maybe someone can confirm this.

**Comment by cklosowski** [comment]
@webzunft Yes we've done some work to fix that. What you are seeing is intentional in that we do not allow two customers to have the same email address, and a customer can have multiple email addresses. 

If a user is logged in and uses multiple email addresses on multiple purchases, those email addresses are then assigned to their customer record in EDD. If another user tries to use that same email it will throw this error.

This is an intentional data pollution protection, so that you cannot have the same email address on purchase records belonging to different customers, which was causing some major issues in the past.

We see this often from Admins who try and make a guest purchase using the same email address as their existing account/customer. When testing logged out purchases, you need to use an email address that is not already in use.

**Comment by webzunft** [comment]
thanks @cklosowski 
I am sorry if I didn’t make myself more clear, but this is in fact the same user.
I was logged in as user id #1 and this is also the user that `EDD_Customer( get_current_user_id(), true );` returned. I understand what you are doing here and why, but in this case it was the identical user and not another one.

**Comment by cklosowski** [comment]
Ok that wasn't clearly stated...but you did also state that you have two customers with the same user ID, yes? This was a bug that was fixed...if you clean up that user ID assignment to just the customer you want to have that user ID does it resolve it?

**Comment by webzunft** [comment]
Yes, I had (already cleaned it) two EDD Customers with the same WP User ID and if this bug is fixed then everything is fine now. Thanks!

**Comment by cklosowski** [comment]
:+1: @webzunft yep, we made quite a few improvements to the 'customer detection' to try and resolve issues like this going forward in:
#5579 
#5926 
#5646 
#4739
#3881

Those are just some of the updates that have happened regarding customers, that improve the relation detection.

If you continue to see issues please let me know

**Comment by webzunft** [comment]
I just checked for duplicate `user_id` entries in `wp_edd_customers` using `SELECT * FROM wp_edd_customers group by user_id having count(*) > 1` and only found some with `-1` and `0`. All older, but no higher IDs, so I think there is no issue for me anymore.
