### ISSUE TITLE
[downloads] Pagination not working with custom EDD_DISABLE_ARCHIVE as true

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#6025]
I have the EDD_SLUG 'add-ons' but I want a cool archive page adding some shortcodes and more info so I create a page with the post_name 'add-ons' to override my theme archives page

But it does not works, so I disable the downloads archive (EDD_DISABLE_ARCHIVE to true) and yes, issue happens here, the [downloads] shortcode can not paginate

To let you check it there is the full config:

* Create a page with the post_name 'add-ons' with the [downloads] shortcode as content
* define( 'EDD_SLUG', 'add-ons' );
* define( 'EDD_DISABLE_ARCHIVE', true );

I found this issue with a custom slug, but creating a page with post_name as downloads and disbabling archive issue happens too

**Comment by cklosowski** [comment]
@rubengc pagination is showing just fine for me with the configuration above.

What are your arguments for the `[downloads]` shortcode?

**Comment by rubengc** [comment]
Hi @cklosowski

I just forgive to say permalink structure is set to %postname%

And the unique arguments i passed to this shortcode are buy_button and price with "no" as value

**Comment by cklosowski** [comment]
Ah, ok, I had assumed the pagination just wasn't showing. My apologies.

**Comment by sunnyratilal** [comment]
Tried to replicate but unable to.

**Comment by cklosowski** [comment]
@sunnyratilal I was able to replicate it. Loop back with me tomorrow and we can try and get you to replicate.

**Comment by sunnyratilal** [comment]
After working with @cklosowski on this one, we found that there isn't a way for the above configuration to work because of the way WordPress initialises the query.

It checks if a post type has an archive very early in the query set up process; there isn't a way for us to modify the query to _force_ the page to work.  In terms of the query hierarchy, `archive` comes before `page` hence it bails before it even loads the page content. 

Once the query is testing whether this is a post type archive, it will immediately trigger a 404 because the archive page has been disabled.

@cklosowski and I spent a fair amount of time trying to come up with a solution but unfortunately there isn't one.

**Comment by cklosowski** [comment]
They key point in the problem is the EDD_SLUG being the same slug as the
page URL. Since WP identifies it as the custom post type slug that negates
the page slug from showing pagination. If you make the page any other slug
than the one that matches the EDD_SLUG it will work.
