### ISSUE TITLE
Tax settings fail to be helpful on responsive displays

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6034]
When on mobile, the Tax settings start to get extremely difficult to manage. It was proposed in #5644, but it's just too large of a page to tackle and I think will take some restructuring.

**Comment by nosegraze** [comment]
Here's an example of how it could look using the built-in responsive table layout in core. The one problem is that the toggle doesn't work because the tax rates are a table within a table, which causes the JS to trigger twice. It adds and removes the `is-expanded` class on the same click. We had this problem in RCP too.

![edd-tax-rates](https://user-images.githubusercontent.com/6324272/34556878-12735ad8-f130-11e7-96ed-777ad0f234e3.png)

**Comment by pippinsplugins** [comment]
@nosegraze you mean the expand / collage toggle on individual rates does not work? I think I'd opt to not collapse the rates.

**Comment by nosegraze** [comment]
@pippinsplugins Yes that's what I meant. Here's an alternative where they're all expanded:

![edd-tax-rates-expanded](https://user-images.githubusercontent.com/6324272/34612306-20617052-f221-11e7-9159-eeee59604391.png)

**Comment by pippinsplugins** [comment]
That looks good, let's go with that version.

**Comment by nosegraze** [comment]
PR: #6288

**Comment by pippinsplugins** [comment]
PR looks great, merged!
