### ISSUE TITLE
Generate a negative payment on refund a purchase

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#6073]
Hi

When an user makes a purchase, EDD handles all the movements of this purchase based on the payment status, but on refund a payment EDD should generate a new payment history in negative for some reasons:

1 - To meet the most common invoicing law requirements (if you already has been registered an invoice, you need also register the refund with a negative total)
2 - To let other extensions process the new payment generation, like increase counter on advanced sequential order numbers or create a new entry on EDD Comissions to request the amount to the comissioners
3 - To get more exact payment totals

**Comment by chriscct7** [comment]
I strongly disagree with this idea. It's going to break a heck of a lot of things, from how gateways and other extensions work, but also it doesn't solve any of the issues presented:

> 1 - To meet the most common invoicing law requirements (if you already has been registered an invoice, you need also register the refund with a negative total)

Any standard payment gateway (Stripe, PayPal, Authorize, etc) issues a refund receipt, and those that do not (of which I can't currently think of any that don't) can easily be generated by the end user. I can't actually think of any eCommerce system, WordPress or not, that actually issues negative orders for refunds, probably for the aformentioned reason of how many bugs it would cause. This would require not just simple changes but substantial rewrites to significant parts of EDD core that expect payments to be positive integer totals, to extensions like Software Licensing that would have to try to figure out and find negative orders to adjust license statuses with, to gateways that'd have to realize to negate negative payment totals and then treat those as refunds, which means literally every gateway for EDD that has built in refund support would have to be updated. The backwards compatibility issues on this would be a nightmare.

> 2 - To let other extensions process the new payment generation, like increase counter on advanced sequential order numbers or create a new entry on EDD Comissions to request the amount to the comissioners
This step is only required because of 1. Plus then logically you'd have to also go back and post-issue new orders of negative totals for existing sales, which means that your invoices not only would not be sequentially ordered, but to do it properly you'd have to issue either out of sequence, or re-number already issued payments. Both of which imo are absolute nonstarters. And there really isn't a benefit to this number anyways.

> 3 - To get more exact payment totals

This method isn't any more exact than the current method employed.

**Comment by chriscct7** [comment]
If someone else has an opposing viewpoint, feel free to reopen but this seems completely out of the realm of possibility without breaking a ton of existing addons and core code, and it's unclear if there's any gain out of this (per above).
