### ISSUE TITLE
remote download urls are not protected. 

### ISSUE THREAD

**Issue by selul** [easydigitaldownloads/easy-digital-downloads#6099]
When using files which are hosted on a remote server, the download url is not protected and is doing just a simple redirect on download. 

this is happening because here https://github.com/easydigitaldownloads/easy-digital-downloads/blob/0275eb5756e5708fefaa1ba5846aef115f999eb1/includes/process-download.php#L202-L206
the redirect param is set to true for all remote urls. 

I think it should use either the `download_method` value or have a filter applied to this argument for hiding the original url.

**Comment by pippinsplugins** [comment]
This is intentional. External files cannot be protected since the files do not live on the same server as EDD.

Protecting the external file would require copying the file to the local server and then delivering it to the customer. While this is certainly possible, it would be extremely prone to failure due to limitations on server resources. Small files would work okay but large files would inevitably fail.

**Comment by chriscct7** [comment]
@pippinsplugins didn't you mean to also close this?

**Comment by chriscct7** [comment]
Closing per comment above
