### ISSUE TITLE
Earnings report not showing for today view unless you click fresh reports

### ISSUE THREAD

**Issue by scottrpaterson** [easydigitaldownloads/easy-digital-downloads#6161]
EDD version: Version 2.8.11

Today view on Dashboard is correct: 
![yuufxjk](https://user-images.githubusercontent.com/11578353/32629039-20a1d62c-c555-11e7-874d-668ac75a407d.png)

But in the Reports, Today view is showing as 0.
![gxjqikc](https://user-images.githubusercontent.com/11578353/32629058-328d61f8-c555-11e7-8644-7da0f7b64995.png)

Yesterday, and all other reports view show correctly. The today view will show if you click "Refresh Reports", but does not show otherwise.

**Comment by scottrpaterson** [comment]
This appears to be fixed in EDD Version 2.8.12

**Comment by cklosowski** [comment]
@scottrpaterson it's possible that the Reports list was cached, we cache that data in a transient, by the MD5 hash of the arguments passed in. I'll close this out as 'invalid' for now, feel free to continue discussion if you see this happen again.

It specifically can happen if the reports have been run (the dashboard widget and graphs pull slightly differently data sets, due to their detail) and you visit again, you could be getting that cached response, until you refresh reports, which kills the transient.
