### ISSUE TITLE
Address Line 1 should be required by default if taxes are enabled

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#6230]
Currently if taxes are enabled you can leave the Address Line 1 field blank on checkout, while City/Zip/Country are required. I feel like Address Line 1 should be required by default.

**Comment by cklosowski** [comment]
Street address isn't used to calculate tax. Just state and country. Zip is
required by the gateway.

Any address based taxes (as far as I'm aware) are for when a business is
located at a specific address and must charge an additional tax, but that
is not based on the customers address.

By that motion city wouldn't be required but I think it has to be due to
some tax filing laws so you can report to municipalities about tax data.


On Dec 13, 2017 7:05 AM, "Phil Johnston" <notifications@github.com> wrote:

Currently if taxes are enabled you can leave the Address Line 1 field blank
on checkout, while City/Zip/Country are required. I feel like Address Line
1 should be required by default.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6230>,
or mute the thread

**Comment by mintplugins** [comment]
Closing. Customers can require it using this library snippet:
https://github.com/easydigitaldownloads/library/blob/a83764451d28a0388ff00dc079824a620db26f6b/checkout/required-fields.php
