### ISSUE TITLE
Ignore "pending" purchases in discount code usage computing

### ISSUE THREAD

**Issue by hor-net** [easydigitaldownloads/easy-digital-downloads#6235]
If I set the "Use Once Per Customer" flag and a user use it in a purchase but does not complete it, the code is considered as used and the customer cannot use it anymore. 
I have to delete the "pending" purchase to allow the user to use the discount code once again.

**Comment by cklosowski** [comment]
This behavior is intentional. A `pending` payment could still be completed. In the case of using an offsite payment gateway like PayPal, the user could have completed the payment action, EDD is just waiting for PayPal to inform the site that the payment has completed.

There is no guarantee that this notification (called an IPN at PayPal) will be instant, and sometimes has technical delays, so payments are not marked as completed for 10s of minutes, even hours in some cases.

If we ignored `pending` payments, it would allow users to use the discount code more than once ,while a valid payment is pending due to a delayed webhook or IPN call.

If a user simply went to PayPal and does not want to complete that exact payment they can:
1) Return to the site and provided the site allows them to see their purchase history 'resume' the pending payment
2) Wait for the payment to become 'abandoned' at which point they will be able to use the discount again
3) Use a different email address to purchase
