### ISSUE TITLE
Hardcoded 'Checkout' text should use 'Add to Cart text' variable

### ISSUE THREAD

**Issue by scottbuscemi** [easydigitaldownloads/easy-digital-downloads#6340]
There's hardcoded "Checkout" verbiage on the add to cart button, when instead it should be using the "Add to Cart text" option that's entered on the Settings > Misc > Button Text page.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/6470a151af276b5d2f23200d7b0535dedd200af8/includes/template-functions.php#L191

**Comment by cklosowski** [comment]
That is not the 'Add To Cart' button. that is the one that shows after a user has clicked Add To Cart or visits a page displaying the button and the item is already in the cart.

Using the Add to Cart text here would be extremely confusing since it would show 'Add to Cart' after adding to the cart.

![screen shot 2018-02-01 at 9 50 39 am](https://user-images.githubusercontent.com/1390124/35691316-65d5de24-0735-11e8-94ae-c4af8b7ef8a1.png)

![screen shot 2018-02-01 at 9 50 44 am](https://user-images.githubusercontent.com/1390124/35691319-68e5540a-0735-11e8-8fab-356f2372afbb.png)

**Comment by scottbuscemi** [comment]
Could this still be something that's editable in the backend or filterable?

**Comment by SDavisMedia** [comment]
@scottbuscemi the entire `edd_get_purchase_link()` function is filterable but that's probably not the most reliable way to edit just that string right now. I like this request. I'll chat with the crew about it.

For now, if you're not willing to use the `edd_purchase_download_form` filter or override the function, I suggest using the [Say What? plugin](https://wordpress.org/plugins/say-what/) and creating a Text Change for the `Checkout` string. That'll change the button text as well as checkout text in the cart widget.

**Comment by SDavisMedia** [comment]
At a minimum, the `Checkout` strings throughout the plugin need context. @cklosowski would you rather make an enhancement here that allows us to easily control that button text (kinda seems odd that we don't since other similar buttons have it) or just add some context so plugins like **Say What?** can target it?

**Comment by cklosowski** [comment]
I'd say it should be an option to configure, with the default being `Checkout` as it currently exists hard coded. I see no problem with. We should indicate that it is by default used to display after adding an item to the cart.
