### ISSUE TITLE
Add action hook above short code download list 

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6376]
Issue #6363 currently add's action hooks before and after the loop, but these hooks appear _within_ the product grid, rather than out with causing problems if you want to add a search box or similar above the download list.

I propose we add a new action hook alongside these before the download list to allow easy third-party integration. This is useful for instances such as my own where I am building AJAX filters and search functionality for EDD that I want to appear above the grid.

I propose we use the following hook name:

```
<?php do_action( 'edd_downloads_list_before', $atts ); ?>
```

I will submit PR for this.

**Comment by davidsherlock** [comment]
PR Submitted #6377

**Comment by SDavisMedia** [comment]
@davidsherlock Not sure if you're meaning to imply that the hooks added in #6363 are bad but they're completed unrelated to your needs here, from what I understand. They'll serve a separate purpose for those who need them.

I like your proposal, though. I imagine no one would be against it. But I do have one suggestion and one consideration:

**Suggestion:** Let's add a pair instead of just the top one. So `edd_downloads_list_after` below the `edd_downloads_list`.

** Consideration:** Based on your current placement, these hooks would be unavailable if no downloads are found. But in that scenario, `No {whatever} found` will still be output on the page. I think it would be beneficial to add them outside of the `$downloads->have_posts()` conditional so the hooks are available whether there are downloads found or not.

**Comment by cklosowski** [comment]
I agree with both @SDavisMedia on the Suggestion and Consideration.

These should be a pair, as well as appear if there are download or not, allowing consistency in the output of things like a search box.

**Comment by davidsherlock** [comment]
Before I edited my post I proposed two hooks, but reverted back to one for some reason.

I will re-submit a commit with two hooks out with the condition.

**Comment by SDavisMedia** [comment]
@davidsherlock can you go ahead and update this PR when you get a chance?

**Comment by pippinsplugins** [comment]
I don't like the use of `list` here. In most cases, `[downloads]` results in a grid, not a list, so saying `list` is a bit of a misnomer.

**Comment by SDavisMedia** [comment]
@pippinsplugins before I adjust it, would you rather the hooks match the markup, which is `edd_downloads_list`, or match how the output is typically displayed?

In my opinion, "grid" is the misnomer. Though the output is displayed like a grid (in most cases), but I'd say it's more of a list than it is a grid. The grid display is nothing more than CSS trickery. Change the CSS and you lose your grid. You never lose the fact that it's a list, though.
