### ISSUE TITLE
Completed Sales count is wrong if new Customer is created with same email

### ISSUE THREAD

**Issue by webzunft** [easydigitaldownloads/easy-digital-downloads#6378]
I just made a mistake trying to use the _New Customer_ link in the _Customer Details_ section of the payment edit page using the same email the current client already entered.

This didn’t result in a new user being created, no warning was given either.

What I noticed though was that on the Customer page, the count for _Completed Sales_ went up. It still only shows that single purchase he made under _Recent Payments_.

I know for sure that the _New Customer_ option must be related to this since I had the previous version of the Customer page still opened as well.

EDD is up to date.

**Comment by SDavisMedia** [comment]
@webzunft I tried replicate what you described but got slightly different behavior. I can confirm that using the _New Customer_ UI from a purchase record and adding an email address that belongs to another customer results in the payment record being assigned to the already-existing customer. I'm actually curious if that was intentional or not. It seems logical to me. Thoughts, @cklosowski ?

As for the _Completed Sales_ counts and _Recent Payments_ on the customer records, everything actually looks good there to me. On Customer A, the Completed Sales count decreased by one and the payment row was removed from Recent Payments. On Customer B, Completed Sales count increased by one and the payment row was added to Recent Payments. So again, this actually looks correct to me.

Go to the Tools tab for both customers and recount stats. Does anything update after that?

**Comment by webzunft** [comment]
Thanks, @SDavisMedia . I was actually using the email address from the client of that purchase, not from some other client. I know, it doesn’t make sense. Was an accident :)

**Comment by SDavisMedia** [comment]
@webzunft Ha! I see now. I definitely replicated the Completed Sales count going up in that scenario. That's wrong, and probably preventable. Using the _Recount Stats_ tool for that customer definitely fixes it, though.

We'll look into what kind of adjustments should be made here, if any. Thanks for the report!

**Comment by cklosowski** [comment]
If I'm reading this right, a new customer was created with the email address that belongs to an existing customer? If so that's a bug we need to prevent on submission. @SDavisMedia @webzunft is that correct?

**Comment by SDavisMedia** [comment]
@cklosowski No new customer is actually being created. To replicate what's happening, just:

1. View the customer record for your admin account and take note of the Completed Sales count
2. Now go to one of your recent payment records and click the **New Customer**
3. Use _the same email address that already belongs to your customer record_ when you fill out the new customer form (so probably your admin address email... doesn't matter if you use your primary or one of your secondary customer record emails... I tried both)
4. Save payment
5. Revisit your customer record... Completed Sales count has increased by 1
Note: Using Recount Stats will fix it.

Rare. Super edge case. But it originates from the fact that you can add a new customer to a payment record using an email address that already belongs to the customer associated with the payment record... and it affects the customer's stats.

**Comment by cklosowski** [comment]
Ok, so for me this seems like we should be even preventing the customer attachment. What's occurring is we cannot create a new customer, we are finding an existing one, and attaching the payment to that one (unintentionally by the admin).

We should stop this from occurring and simply warn then before saving that a customer exists with that email, either attach it to that customer or simply tell them to create a customer with a new email address.

IMO, we're just assuming too much on the EDD side, instead of throwing a warning to the user of what is about to happen.

**Comment by SDavisMedia** [comment]
@cklosowski I definitely agree. 👌

**Comment by SDavisMedia** [comment]
@cklosowski replicated again on `master` and confirmed that the warning displays on `issue/6378`. But I think the warning should be changed.

Instead of:

`A customer with the email address email@email.com already exists. Please go back and use the dropdown to assign this payment to them.`

It should read:

`A customer with the email address email@email.com already exists. Please go back and use the "	Assign to another customer" link to assign this payment to them.` (or something similar)

The dropdown you referenced isn't part of the visible UI until that link is clicked. Besides that, all is well in my tests. :+1:

**Comment by cklosowski** [comment]
Ah, right, i'll get that updated.

**Comment by cklosowski** [comment]
updated @SDavisMedia

**Comment by SDavisMedia** [comment]
@cklosowski Golden. 👌
