### ISSUE TITLE
When no tax rate is entered, number_format() expects parameter 1 to be float, string given	

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6407]
If a site owner enables taxes and selects the country and state/province, but does _not_ enter a tax rate, the following warning is shown on checkout:

```
number_format() expects parameter 1 to be float, string given
```

I've seen this reported a few times.

**Comment by pippinsplugins** [comment]
Example configuration that will trigger the error:

![image](https://user-images.githubusercontent.com/1034109/36952300-a0063ede-1fd3-11e8-87be-c3ac98175884.png)

**Comment by SDavisMedia** [comment]
Replicated on `master`. On `issue/6407`, I can't break it. All additional Tax Rates rows properly use the fallback rate (I believe that's intentional). If the fallback rate is empty, 0% tax is added at checkout. Whether that should happen or not is debatable, I believe. But it doesn't break any functionality that I can find. :+1:
