### ISSUE TITLE
Script Loading Optimisation

### ISSUE THREAD

**Issue by Basilakis** [easydigitaldownloads/easy-digital-downloads#6465]
Hey,

I have been working on a project and now we have moved on the part of speed.
I have noticed that your paypal JS and Stripe are loaded on all pages and not only check-out page ( or if they needed somewhere else, where the short-code is loading them ).

Is there any particular reason for that?

**Comment by pippinsplugins** [comment]
@Basilakis This is related to the Stripe / PayPal add-ons and not EDD core so this should be opened up in each of those respective repositories.

For Stripe, the scripts are loaded on every page because that's what Stripe instructs us to do in order to ensure the Radar system has the best possibility of detecting fraud.

**Comment by JeroenSormani** [comment]
Sorry to comment in here instead of in the respective repo, but I was dequeueing Stripe without knowing that @pippinsplugins.

Reference to loading stripe.js on each page: https://stripe.com/docs/stripe-js/v2#including-stripejs

Which refers to the [Radar page](https://stripe.com/docs/radar) that mentions the following:
> To use Radar, your website or app must use Checkout, **Stripe.js and Elements**, or our mobile SDK integrations for iOS and Android when processing card payments.

I'm not sure if the 'Stripe.js and Elements' part means that both those must be used in order to have Radar active.. (sure sounds like it, but doesn't make sense)
I've contacted Stripe support to verify and will post back here when I hear back.

**Comment by Basilakis** [comment]
@pippinsplugins 

```
function gmt_edd_stripe_js_checkout_only( $override = false ) {
	wp_dequeue_script( 'stripe-js' );
	if ( ( function_exists( 'edd_is_checkout' ) && edd_is_checkout() ) || $override ) {
		wp_enqueue_script( 'stripe-js', 'https://js.stripe.com/v2/', array( 'jquery' ), null );
	}
}
add_action( 'wp_enqueue_scripts', 'gmt_edd_stripe_js_checkout_only', 200 );
```

That works for stripe, but paypal cant find the relative files ( yes, I do not care for fraud payments, I prefer quick site.

**Comment by cklosowski** [comment]
We have an open issue for Stripe to make this an option to disable on every page.

While not recommended by Stripe, we'll make it an option:
https://github.com/easydigitaldownloads/edd-stripe/issues/288

For PayPal you can look at unhooking:
`add_action( 'wp_enqueue_scripts', 'eppe_after_purchase_form' );`

Since these are customizations and not part of EDD Core i'm closing this issue so they can be handled in their respective repositories.

**Comment by JeroenSormani** [comment]
Stripe's response:
> This simply means that you need to use the Stripe API to take the card details, as opposed to manually entering the card details into the dashboard (which should be avoided in any case). Checkout, Stripe.js and Elements, and the mobile SDK integrations for iOS and Android are all part of the Stripe API. 
> 
> 3rd party integrations are usually built around Stripe.js/Elements. 
> 
> The statement essentially is saying, as long as you use Stripe how it's meant to be used, Radar is helping protect your business :-)
>
