### ISSUE TITLE
API key logs should be visible in export and deleted.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6501]
## Enhancement Request
When deleting a user, EDD should clear any API Log requests associated with that user's API Keys
![screen shot 2018-04-10 at 12 40 53 pm](https://user-images.githubusercontent.com/1390124/38579637-7aef7dd0-3cbc-11e8-8e89-c4da6bca8d3c.png)

### Justification or use case
[GDPR](#6216 )

**Comment by cklosowski** [comment]
Since API keys are associated with users, when the erase comes in, we should just delete the API access logs, along with the user.

**Comment by SDavisMedia** [comment]
Showing up in the exporter just fine: 
<img width="888" alt="screenshot 2018-05-21 16 49 25" src="https://user-images.githubusercontent.com/2359131/40335130-f88e56c4-5d16-11e8-9422-d905e3d5bbf8.png">

Eraser working fine as well, though I didn't quite understand [your comment](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6501#issuecomment-390798345) until now. I tested with a customer who _wouldn't_ be anonymized during the eraser because the single payment record attached to the customer has a `pending` status and I wanted to see what would happen to the API request logs in that scenario. As I now realize is expected, the API request logs _associated with that customer's user account_ have been deleted.
<img width="701" alt="screenshot 2018-05-21 17 07 41" src="https://user-images.githubusercontent.com/2359131/40335620-7fadfac2-5d19-11e8-9292-8cc9ecb66b39.png">

All goody on my end for both the exporter and the eraser. :+1:
