### ISSUE TITLE
Inactive discount codes show as "Active" within discount table view

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6534]
**Bug Report**
When switching a discount code from "Active" to "Inactive", the table still display's the discount code as "Active".

**Expected behavior**
The table should show the discount code as "Inactive".

**Actual behavior**
Discount code remains as "Active", confusing the site owner.

**Steps to reproduce the behavior**
1. Create a new discount code and set it to "Active"
2. Within the table set it to "Inactive" 
3. The discount code continues to show as "Active"

**Comment by SDavisMedia** [comment]
This stopped working in 2.9. Everything before was fine. I haven't had any luck tracking down the culprit, though.

**Comment by cklosowski** [comment]
So the root cause of this is that `status` and `post_status` are attempted to be used interchangeably.

We have `EDD_Discount::update_status` which updates the `post_status` column, but then we also have `EDD_Discount::setup_status` which is using `$this->get_meta`.

We need to pick one, as we're ending up with mixed results with `status` being `inactive` from meta, but the `post_status` being listed as `Active`.

**Comment by cklosowski** [comment]
@sunnyratilal let me know what you think here.

**Comment by sunnyratilal** [comment]
After discussing with @cklosowski, this will be fixed in 3.0.

**Comment by sunnyratilal** [comment]
Issue has been fixed in 3.0.
