### ISSUE TITLE
EDD_SL_Plugin_Updater Could not create directory. Windows Server

### ISSUE THREAD

**Issue by liquida** [easydigitaldownloads/easy-digital-downloads#6540]
### Actual behavior
When I try to update a plugin in a wamp server the plugins returns an error 

Could not create directory. quadmenu-pro/lib/ReduxCore/assets/css/vendor/jquery-ui-bootstrap/images

PHP Version:  7.1

EDD Version (or branch): 
EDD_SL_Plugin_Updater  version 1.6.14

WordPress Version: 4.9

**Comment by liquida** [comment]
The issue have been described here https://generatepress.com/forums/topic/getting-could-not-create-directory-error/

**Comment by cklosowski** [comment]
This is something we track in Software Licensing, not in the main EDD Repository.

On that note, this is a bug in the Windows File system that we are aware of and looking for a solid solution for. 

The thing could be avoided if this WordPress Core trac ticket is resolved: https://core.trac.wordpress.org/ticket/38231

We submitted it so that the proper file name the Software Licensing defines is used, instead of the querystring'ed name.

Another user has come up with a solution that is working for him, but hasn't been rolled into Software Licensing yet until it can be fully tested with as many configurations as possible: https://gist.github.com/spivurno/d7a93ab4920c4fa88bad0e5177b45ba1
