### ISSUE TITLE
Notice when activating on PHP 7.2

### ISSUE THREAD

**Issue by jfarthing84** [easydigitaldownloads/easy-digital-downloads#6604]
### Expected behavior
When I activate the plugin, I expect it to activate without errors.

### Actual behavior
When I activate the plugin, I get the following notice:

> PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/web/app/plugins/easy-digital-downloads/includes/emails/class-edd-email-tags.php on line 211, referer: https://example.com/wp-admin/plugins.php?plugin_status=all&paged=1&s

### Steps to reproduce the behavior
1) Use PHP 7.2
2) Attempt to install the plugin

### Information (if a specific version is affected):
PHP Version: 7.2.5

EDD Version (or branch): 2.9.3

WordPress Version: 4.9.6

**Comment by SDavisMedia** [comment]
Thanks, @jfarthing84. At this point, now that your full install is completed, you should be good to go. Sorry about that but thanks for reporting!

@cklosowski I replicated the behavior on a fresh install. After install, [the variable](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/emails/class-edd-email-tags.php#L208) that `count()` is used on is an array. I guess there's an issue with the order of operations during the install because once the EDD install is completed, `edd_get_email_tags()` is an array with all the email tags.

**Comment by sunnyratilal** [comment]
I think it's because `edd_load_email_tags` is hooked on to `init`. Going forward, we've introduced `edd_loaded` action in 3.0 which is where functions like these should be hooked onto.  It may be worth changing the milestone to 3.0 and hook it on to `edd_loaded` which _may_ fix the issue.

The quicker fix is to just alter line 208 of `class-edd-email-tags.php` to `$email_tags = (array) edd_get_email_tags();` but that still leaves the issues that `edd_get_email_tags()` does not return the  array we expect on activation.

**Comment by pippinsplugins** [comment]
Let's do a quick fix on this since the timeframe on 3.0 is still unknown.

**Comment by cklosowski** [comment]
We could just update `class-email-tags.php::37` to be:
`private $tags = array();`

That would type case it to be an array out of the default status. As @sunnyratilal said that won't fix the list of email tags on activation.

What do you think of that solution @sunnyratilal? That would cause us to just always have `array()` instead of `null` on the variable, even if has not yet been populated and will forego some type casting issues if someone tries to add a tag earlier than Core has already converted it to an array.

**Comment by cklosowski** [comment]
@sunnyratilal mind chiming in here if we need both yours and my resolution for this?
