### ISSUE TITLE
post_date no longer defined nor accessible on EDD_Payment

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6631]
The `post_date` field is no longer accessible on EDD_Payment, resulting in PHP notices for any old code (like Software Licensing) that is still referencing that field for the purchase date.

>>>Undefined property: EDD_Payment::$post_date
>>>wp-content/plugins/easy-digital-downloads/includes/payments/class-edd-payment.php:360 |

**Comment by sunnyratilal** [comment]
We need to backfill all of the `WP_Post` args in `EDD_Payment`.

**Comment by sunnyratilal** [comment]
`post_date` was added by @JJJ in `7411e6c3da6095869987d91f880a69a5548a8218`.

We should backfill the rest of the `WP_Post` params too.

**Comment by sunnyratilal** [comment]
We don't need to backfill these vars; I misunderstood this issue.

`EDD_Payment` does not extend `WP_Post` so it doesn't need to support the `WP_Post` class vars; the issue existed because when setting up the object, the payment was fetched from the `wp_posts` table so it had access to a `WP_Post` object which was used to fill in the `EDD_Payment` instance variables.

**Comment by pippinsplugins** [comment]
Only certain fields need to be backfilled, just those that were referenced often, like post_date.

**Comment by sunnyratilal** [comment]
The `post_date` reference was made internally by `EDD_Payment` when it used the `WP_Post` object from the database; we didn't make `post_date` available as a public class variable.

**Comment by pippinsplugins** [comment]
Not quite, sorry. It was used by other plugins. I noticed this problem through Software Licensing. See https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/ef8f46d7044eeb9642a61b73987dcd5b807d7871/includes/classes/class-sl-license.php#L273
