### ISSUE TITLE
Many query with edd_has_user_purchased function

### ISSUE THREAD

**Issue by hamedmoody** [easydigitaldownloads/easy-digital-downloads#6661]
Hi
i want to check if current user has been purchased or not in my template.
when i use edd_has_user_purchased function run many extra same queries.
![image](https://user-images.githubusercontent.com/9475089/41434664-c3407668-7031-11e8-82e2-5cbd2ac3d701.png)
In this case i have 46 query from each query.
it is not good

**Comment by cklosowski** [comment]
@hamedmoody could you provide a little more detail of what type of page you are seeing this on? Is it a product list, custom template, account page?

The context might help explain more about why you are seeing so many.

**Comment by hamedmoody** [comment]
First i use "blackbox debug bar" for debug.

I use "edd_has_user_purchased" function in my single post page that check that current user purchase this download or not.
I use below code:
`$hasPurchae = edd_has_user_purchased( get_current_user_id(), $course->get_download_id() );`
this line run once and run above 46 repeated queries.

**Comment by cklosowski** [comment]
Thanks for the details I'll look into it.

**Comment by cklosowski** [comment]
@JJJ @sunnyratilal possibly something we can be sure to test with EDD 3.0 work?

**Comment by hamedmoody** [comment]
Thanks
i saw a bug in new version after update.
i use extra field in payment form (Phone, address). this fields save in _"edd_payment_meta".
but after update to new version and after complete payment with calling `edd_update_payment_status($payment, 'publish');` function this fields deleted. before publish exists in database and just after calling above function in gateways plugin this fields is gone. i installed prev version

**Comment by sunnyratilal** [comment]
@cklosowski Yeah; `edd_has_user_purchased()` is being refactored for 3.0 and will be a lot more efficient.

**Comment by cklosowski** [comment]
@hamedmoody That's going to be something related to 3.0, not this, but keep in mind, that this is a 100% refactor of the EDD Codebase for 3.0, expecting things work function 'as is' right now isn't likely due to it still being in a very early beta. You should be following the development closely and the goal is that if you are using the `EDD_Payment` class and helpers that you should be in an ok state. However, calling post meta directly has been deprecated since we released `EDD_Payment`, where we added a wrapper method so that when the custom tables were introduced, your could would continue working.

**Comment by ashleyfae** [comment]
Closing this as the function performs _much_ better in 3.0.
