### ISSUE TITLE
Changes to receipt template for 3.0

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6678]
EDD 3.0 does not support `get_post()` for new orders that are inserted into the database.

We will attempt to automatically update overridden template files but if that is unsuccessful due to permissions, a notice with a link to a doc needs to be displayed telling site owners how to update.

**Comment by sunnyratilal** [comment]
Merged; keeping issue open so that a doc gets written.

**Comment by DrewAPicture** [comment]
@cklosowski Based on Sunny's last comment, it seems like all that's left here is making sure we have documentation. What exactly are we documenting? How to modify the template? And is this replacing existing docs with new ones or generating complete new ones?

**Comment by cklosowski** [comment]
The biggest concern is that people who have made custom templates are likely going to have `get_post` calls in their templates while trying to load `orders`. Since this isn't supported we'll have to notify people of the change sin the templates that they likely copied or based off our default ones.

We could probably get a blog post together for plugin developers and theme developers that will help them understand where to look for these changes.

**Comment by ashleyfae** [comment]
See https://3.basecamp.com/4226849/buckets/12407027/todolists/3181435287
