### ISSUE TITLE
3.0 reports: Exclude gateways in charts that don't have sales

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6763]
### Expected behavior
Charts under `Reports > Payment Gateways` should not show gateways that have never had sales (maybe because they've never been enabled).

We can't simply remove gateways that are disabled, because they may have been enabled before and had sales, and they may still be processing webhooks for renewals after being disabled. But if a gateway has 0 sales/earnings we can exclude it from the charts.

### Actual behavior
They're showing in this screenshot, even though I've never had PayPal or Amazon enabled:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/1254870/42656589-54c1c074-85e5-11e8-84e0-d4249549736e.png">

**Comment by sunnyratilal** [comment]
This is actually more difficult to do because the labels and the data are separate.

@mindctrl The easiest solution is just having a strikethrough for the label of the payment gateway and not have a segment in the pie chart.  Otherwise the calculations need to run twice once for the chart and the other time to determine the visible labels.

**Comment by mindctrl** [comment]
@sunnyratilal ah yes, you're right. I think a strikethough works for now and if we need to revisit later we can.

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/8ee85c0a0b7b6bcbcd1ebe88025819904c371e75.
