### ISSUE TITLE
3.0: Text overlapping in Order Extras box

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6787]
Latest `release/3.0`. The `Subscription TXN ID` text label collides with the link. Not sure if we need to update here, Recurring, or both.

![image](https://user-images.githubusercontent.com/1254870/43081988-eb93c776-8e60-11e8-8d45-d867ca8da4c7.png)

**Comment by SDavisMedia** [comment]
So when the Order is for a subscription, this problem presents itself with the `Subscription TXN ID` label. When it's not a subscription, the label is `Transaction ID` (EDD core). The latter doesn't produce the same display issue, but it does make me dislike the inconsistency, using `TXN` in Recurring but `Transaction` in core.

I'm bringing this up here because the above display issue that @mindctrl is pointing out is due to CSS. Using `white-space: nowrap;` on the labels to avoid multiple lines of text. As you all probably know from the other recent issue, I'm against that for this exact reason. Not only is the content being boxed into a space, but the content isn't even the true length that I think it really should be (using `Transaction` instead of `TXN`, which is a Recurring problem, not EDD core).

I understand the dilemma, and I do appreciate the new design here with the labels and their values having sort of a center anchor. But I think the labels, while keeping with the same overall [new] design, should be able to span multiple lines. And if that's simply too unappealing for this overall design, I think it's worth it to look into the design approach again.

**Comment by mindctrl** [comment]
I see this on non-recurring transactions:

![image](https://user-images.githubusercontent.com/1254870/43211039-a0b65c42-8ffe-11e8-8515-93fe9d2ffcc7.png)

**Comment by SDavisMedia** [comment]
For what [John reported](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6787#issuecomment-407797324), that output comes from using `esc_html()`. https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/orders.php#L649

Does it have to be escaped there?

**Comment by sunnyratilal** [comment]
It doesn't have to be escaped; it can be removed. I wrapped it in `esc_html` only because WPCS was giving a warning.

**Comment by sunnyratilal** [comment]
Merged.
