### ISSUE TITLE
3.0: Individual item amounts need to be enterable when creating manual orders

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6789]
When manually creating an order record, the individual item amounts (subtotal, tax, discount, and total) need to be enterable. Right now the amounts are all calculated automatically, which will work most of the time, but in cases where an admin needs to define custom amounts this will be a limitation.

The order adjustments feature does get close to providing the necessary flexibility, but not quite since those adjustments are order-specific, not order-item specific.

**Comment by sunnyratilal** [comment]
Just for future reference, after a discussion on Slack this morning with @JJJ, @pippinsplugins and @cklosowski we agreed upon the following:

1. Add an `Override` button that converts the text into inputs allowing the prices to be overridden.
2. The `Override` button is only displayed if the current user has the `shop_manager` capability otherwise the amounts will be calculated automatically with no override allowed (with the exception of credit).
3. Credit will be allowed on a per item basis rather than the current state which is per order.

**Comment by cklosowski** [comment]
Perfect. Thanks for the perfect "meeting" notes @sunnyratilal.

**Comment by spencerfinnell** [comment]
Playing with this, I was pretty confused.

"Override" has no context to what it actually does, and clicking it immediately disables it and nothing else happens. It wasn't until I looked at the code did I realize that I had to click on an existing value to edit it.

I think the button should be moved to the "Order Amounts" meta box and clicking it should immediately make anything that is overridable an input box, and simply remain an input until the order is saved.

There are also a few CSS issues with the input widths: https://cloudup.com/cYXIrFZA9gp

**Comment by JJJ** [comment]
The way you describe it is the way I remember it working. Possible something broke or got shuffled around.

We are also trying to have there be some intentional friction, as the ability to directly modify monetary values reduces the integrity/correctness of accounting and reporting.

If you’ve got UI/UX suggestions, you’re great with that stuff, so I’d love to see what you’ve got.

**Comment by spencerfinnell** [comment]
@JJJ maybe that was the plugin's functionality? Not sure.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/index.js#L133 is what requires the click to switch them now.

I can implement the one-way automatic toggle-to-input for comparison testing.

**Comment by spencerfinnell** [comment]
Hmm the way the inputs are returned in the AJAX right now makes that not so great to implement. I'll have to think about it.

**Comment by pippinsplugins** [comment]
Personally, I really like that @spencerfinnell.

**Comment by spencerfinnell** [comment]
Attached a PR that implements this UI functionality, but it seems like creating the order is a little messed up. As far as I can tell the order creation processing recalculates totals based off the input values, so it seems like some math in `edd_add_manual_order` needs to be looked at.

**Comment by pippinsplugins** [comment]
@spencerfinnell I don't see any input fields. Do I need to do anything special to make them show up?

**Comment by spencerfinnell** [comment]
Click "Override" under the order totals.

**Comment by spencerfinnell** [comment]
The non-editable fields were styled to appear like text until you toggle them to help reduce the usage of this functionality based on what @JJJ said before:

> We are also trying to have there be some intentional friction, as the ability to directly modify monetary values reduces the integrity/correctness of accounting and reporting.

**Comment by pippinsplugins** [comment]
Didn't do it for me.

I see the override button but clicking it doesn't do anything.

**Comment by pippinsplugins** [comment]
Working now, thanks!

A few things:

1. I don't think `Override` is intuitive enough. How about `Override Amounts` to be abundantly clear the button affects the order items amounts?

2. The auto amount calculations are a bit wonky. Changing the item quantity results in the order totals getting updated but not the individual item total. That causes things like this to happen:
![image](https://user-images.githubusercontent.com/1034109/48205838-8855e280-e332-11e8-9ffe-c233ea9ade35.png)

Notice that the item total is $125, the quantity is 2, and the order total is $290. That doesn't add up.

**Comment by spencerfinnell** [comment]
Yeah I saw that too, and wasn’t sure if it was intentional to allow full control. Did the previous plugin keep the line item total auto calculated?

**Comment by pippinsplugins** [comment]
It did not but I think we should now.

**Comment by JJJ** [comment]
I’m working on a function like that as part of Refunds. It needs a way to sum up an array of keyed values, including support for negative numbers. I’ve gone back and forth on having an EDD\Math class, because there could be lots of little things that need hard coding.

For the sake of progress, you could build one here, and I can work around it and integrate the end result later.

**Comment by cklosowski** [comment]
@spencerfinnell The previous view order details screen had inputs that were always editable except for the item total:
![image](https://user-images.githubusercontent.com/1390124/51517039-b6e24600-1dd6-11e9-9cb2-7ec73b34c8a6.png)

As you update the item price, quantity and tax, that last Item Total is live updated on the `change` listener, that was done here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/admin-scripts.js#L629

**Comment by pippinsplugins** [comment]
@spencerfinnell This is looking much better.

Once the `Override Amounts` button is clicked, can we disable the button or toggle it to a `Confirm` button? Right now with the button staying active, it's a bit confusing what's happening once you click it, especially since the price input fields aren't super obvious.

**Comment by spencerfinnell** [comment]
@pippinsplugins Updated to remain disabled once overrides has been started.

**Comment by pippinsplugins** [comment]
Much better.

**Comment by pippinsplugins** [comment]
I'm going to merge this in. There are still improvements to make to the Add Order screen, but they are separate from this issue.
