### ISSUE TITLE
3.0: Separate tax rates & revert adjustments back to discounts

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6820]
After discussion in Slack with @mindctrl and @cklosowski; a decision was made to create a new table for tax rates in order for the data structure to be best used.

With this change, it was also decided to rename `adjustments` back to `discounts`.

**Comment by cklosowski** [comment]
@sunnyratilal Since we've been having people use this beta (in testing) we should probably kill the adjustments tables. Obviously a migration of the data isn't necessary since this is an 'in progress' release and shouldn't be on any production environments, but we should remove the adjustment and adjustmentmeta tables.

**Comment by sunnyratilal** [comment]
Merged.
