### ISSUE TITLE
Download amount set to 0.00 during import if Products (Raw) column does not contain {

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6841]
### Expected behavior
When importing a CSV file that includes a column called `Products (Raw)`, the downloads added to the resulting payment record should each be set with a price equal to the amount proceeding the `|` in the CSV row.

The expected format is like this: `Product Name|10.99`

We also support formats like this: `Product Name|10.99{0.10}`. The amount in the curly brackets is the tax amount.

### Actual behavior

When the first format, the one with out the brackets, is used, the amount always gets imported as 0.00 instead of the specified amount.

### Steps to reproduce the behavior
1) Import a CSV that contains a column called `Products (Raw)`
2) Set the `Products (Raw)` column value in one or more rows to `Product Name|10.99`
3) The product name doesn't actually matter.
4). The imported amount should be 10.99 but it's actually 0.00.

**Comment by SDavisMedia** [comment]
Replicated on `master`. Confirmed on `issue/6841` that when reviewing the imported payment record, the price is properly set based on the value of the `Products (raw) column when it does not include a tax amount. So thumbs up there. However...

I'm curious about two things that may be unrelated and/or intentional:

1. Is the automagically-created download supposed to have its price properly set too? The download is created with a price of `0.00`.

2. I noticed on both `master` and `issue/6841` that on the payment record, the `Price` and `Tax` values for the download reflect a product with prices inclusive of tax. However, my tax settings are prices exclusive of tax.

**Comment by SDavisMedia** [comment]
@pippinsplugins If I import a purchase with $500 product, $10 tax, for $510 payment total, and my taxes are exclusive, the payment import records the product as $490, $10 tax, and $510 payment total... as if my taxes were inclusive (which throws off the overall payment total).

**So while I do think there's value in simply storing what's given in the CSV**, it appears that there _is_ some sort of calculation happening. The scenario above is producing the $490 value on its own, not from the CSV.

**Comment by SDavisMedia** [comment]
@cklosowski Got any ideas here?

**Comment by cklosowski** [comment]
@SDavisMedia the site you are importing to, does it have the same settings as the one exported from, as related to the taxes and how they are included into the order?

Really this setting:
> and my taxes are exclusive

**Comment by SDavisMedia** [comment]
@cklosowski Same settings. Definitely seems like there's an extra calculation happening. And the settings on the import site don't affect the aforementioned results since it's just trying to pull in values from the CSV.

**Comment by pippinsplugins** [comment]
@SDavisMedia I think we should merge this as is and handle the issue you described separately. It wasn't introduced by this changeset so is, mostly, irrelevant.

**Comment by SDavisMedia** [comment]
@pippinsplugins I see no issues with that. :+1:
