### ISSUE TITLE
3.0: Payment Gateway Icons - Improve display

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6872]
I can't capture it in the screenshot but the cursor is set to `move` when you hover over each `label` in either the `Payment Gateways` section, or the `Payment Method Icons` section. This is confusing since the primary interaction should be to _select_ a checkbox when clicking on a label, not to move it.

I propose we only make the cursor show the `move` icon...

<img width="64" alt="screen shot 2018-08-24 at 4 04 18 pm" src="https://user-images.githubusercontent.com/52581/44564508-69c25f80-a7b7-11e8-868d-f6751e7d889d.png">

When you interact with the draggable icons to the far right.

<img width="818" alt="screen shot 2018-08-24 at 4 00 39 pm" src="https://user-images.githubusercontent.com/52581/44564408-e0ab2880-a7b6-11e8-9068-0f9c61232ed0.png">

___

The icon used for drag and drop is `'\f228'`:

<img width="34" alt="screen shot 2018-08-24 at 4 12 11 pm" src="https://user-images.githubusercontent.com/52581/44564687-7c896400-a7b8-11e8-99c8-a1b9a34cabba.png">

This is typically an icon used for menus, and is used already in the WP admin menu bar at mobile sizes:

<img width="215" alt="screen shot 2018-08-24 at 4 09 09 pm" src="https://user-images.githubusercontent.com/52581/44564627-0edd3800-a7b8-11e8-80d7-ccba3d9abab3.png">

I think we should replace the icon we are using with something more suitable, perhaps dashicons-move?

<img width="459" alt="screen shot 2018-08-24 at 4 17 26 pm" src="https://user-images.githubusercontent.com/52581/44564822-3c76b100-a7b9-11e8-88a9-f1d107089a8b.png">

**Comment by spencerfinnell** [comment]
I can open a PR that implements:

https://cloudup.com/cnhACcmZaB4 (hover state)
https://cloudup.com/c1p6OsRhJZ2 (tool tip)

Also fixes the correct cursor showing when you are hovering over the label (hand shows instead of move when you are over text).

**Comment by amdrew** [comment]
@spencerfinnell I agree, an invisible UI with what you have proposed would be much nicer 👍We'd need to implement it for the payment gateways also.

**Comment by SDavisMedia** [comment]
Love it. Working well on my end. :heart:

**Comment by spencerfinnell** [comment]
Nice that’s a great way to add hover intent without using the actual hoverIntent script. Much better.

**Comment by JJJ** [comment]
I'm bias, because I designed the original, but now there's no indication they are sortable until they are hovered over.

**Comment by JJJ** [comment]
I tried out the PR, and really tried to like it, but I still don't. Sorry, nothing personal.

> This is confusing since the primary interaction should be to select a checkbox when clicking on a label, not to move it.

The current approach follows existing WordPress UI/UX conventions. Everything else uses the move cursor on draggable things: Menus, Widgets, Meta-boxes, Customizer, and so on. Their primary actions are to edit/click them. Those do not feel/look wrong, and neither does this, IMO.

I purposely omitted tooltips because they are distracting and busy. Dragging/dropping is a pretty simple & obvious thing. Hiding the functionality, then adding tooltip to say it's possible, hides the obviousness behind an annoying pop-up tooltip thing.

Don't pop a thing up in between the thing the user wants to interact with, kinda thing.

The hamburger menu _used to_ be the icon to use for this interaction, simply because the sorting is veritcal-only. The up/down arrow combo works too, but doesn't always look as pleasing due to its sharp lines and accuse angles.

If the meaning has changed so dramatically in recent times that it's unclear here, that happened without me noticing. BuddyPress still uses them in XProfile fields and it's received literally no negative feedback:

<img width="956" alt="screen shot 2018-11-01 at 1 24 45 pm" src="https://user-images.githubusercontent.com/88951/47871399-fbfb6b00-ddd9-11e8-9f30-14f622d55b25.png">

----

Which icon translates best is pretty situational. In these cases, our sortables are strictly vertical, and it's not 100% obvious to users that these items would even _be_ sortable. So, to avoid inevitable "I'd really like to sort these" and "you can already!" support conversations, I would prefer we keep these more obvious than hidden.

By removing the icons, there is no visual indication of how wide the sortables are until you hover over them. If you hover to the right of them, you'll never know it's sortable. Without the icons always visible, the handle with seems very arbitrary, but there's also no way to find the width of the widest contents, and enforce that value on the others.

Persistent icons guide users without forcing an interaction to happen to learn what hidden powers exist inside the elements.

----

I _do_ like the simplicity of having fewer things onscreen, just as a general rule, always. If there's a way to do that without compromising discoverability and consistency within WordPress admin, I think this is worth iterating on.

**Comment by spencerfinnell** [comment]
I also believe the three line icon on iOS is an icon that is more suited for touch devices. It makes sense as an indication that you can "grab" something and move it around when you're using your finger, but that interaction isn't as common on desktop devices and therefore I don't think the icon has the same implied meaning.

**Comment by pippinsplugins** [comment]
I've spent a little while playing with both `release/3.0` and `issue/6872`. I'll be honest, I really don't care for the experience in `issue/6872` nearly as much as the experience in `release/3.0`.

I've pushed up a new PR that implements just @amdrew's original request of changing the move cursor such that it only shows when hovering over the drag icon. I think this is the best of both worlds and, unless there is objection, I'm going to merge it in and call this closed.
