### ISSUE TITLE
VENDD Theme - Vendor Profile Template

### ISSUE THREAD

**Issue by huemane** [easydigitaldownloads/easy-digital-downloads#6889]
in the current download package of the Vendd Theme,
the following file has wrong code at line 81:

Vendd/content/content-fes-vendor.php

It currently looks like this:

php get_template_part( 'template-vendor-page' ); 

It should be:

php the_content();

Cheers!

**Comment by SDavisMedia** [comment]
Hi @huemane!

Thanks for taking the time to open an issue. However, I don't think that is correct. Here's line 81 of the file you referred to: https://github.com/easydigitaldownloads/vendd/blob/master/content/content-fes-vendor.php#L81 Just above that line, `the_content()` is being called, as you've suggested.

Can you please make sure you are on Vendd version 1.2.3? Also, make sure you have not customized the theme, or you are not looking at a custom child theme instead.

----

I am going to close this issue as we are currently on the Easy Digital Downloads repo instead of the [Vendd repo](https://github.com/easydigitaldownloads/vendd). 

Please go ahead and review the code again. If you still believe the code is wrong, you can open an issue on the Vendd repo and _link directly to_ the line of code you are referring to.

Thanks!

**Comment by huemane** [comment]
Hi, i meant in the zip file downloaded from edd's official site, i double
checked and im right ☺️
