### ISSUE TITLE
3.0: Clicking a tooltip can toggle an admin option

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6906]
With v3.0, tooltips are now a child of the `label` tag. This can result in an admin option being accidentally toggled on/off. 

Example: Customer clicks a tooltip (instead of hovering) thinking it enables the description. They then update another admin setting and click `Save Changes`. Both admin options, the one they purposely changed, and the one that had the tooltip are now saved.

I suggest we move the tooltip's span tag outside the label like how it was in 2.9.x.

<img width="651" alt="screen shot 2018-09-05 at 2 15 44 pm" src="https://user-images.githubusercontent.com/52581/45067218-4338e880-b116-11e8-806e-a22617027e7f.png">

**Comment by SDavisMedia** [comment]
At the moment I'm not seeing any visual issues if the tooltip is moved back outside of the label.

Note that our tooltips throughout admin are located in various places when it comes to HTML structure. Some, like for a select menu field that uses a paragraph description instead of a label, has the tooltip inside of that paragraph. Pointing that out just to say there's a variation in how tooltips are used anyway, so I don't think it would be a big deal for labeled checkbox settings to keep it outside the label.

I did check to see if there was another way, like CSS using `pointer-events: none;` on the span for the tooltip. But it's looking like HTML structure and the required behavior of the label element may override anything set on the span.

So I'm in favor of moving the span back out of the label, which again does not appear to cause any visual style changes for 3.0.

**Comment by JJJ** [comment]
Fixed and pushed to `release/3.0`.
