### ISSUE TITLE
Licenses Pagination in WP-ADMIN

### ISSUE THREAD

**Issue by doothemes** [easydigitaldownloads/easy-digital-downloads#6914]
File: edd-software-licensing/includes/admin/classes/class-sl-list-table.php
Line: 26

`$this->per_page = 30;`

use per_page 20 👍

**Comment by cklosowski** [comment]
This is a software licensing issue not an EDD core issue. @doothemes is there a reason you want this to be set to 20 instead of 30?

Is there a technical bug in this or is it simply to limit the number of items being viewed?

I'm going to close the issue so we can open it in Software Licensing if there is a bug, but please feel free to respond with your reasoning for this change.
