### ISSUE TITLE
what is edd_payment and edd_log post types?!

### ISSUE THREAD

**Issue by nabeghe** [easydigitaldownloads/easy-digital-downloads#7077]
Hi, What's _edd_payment_  post type and can I delete them from _wp-posts_ table? for me, all of _edd_payment_ and _edd_log_ records has no any content!

and Is it possible to completely disable these types of posts?

**Comment by cklosowski** [comment]
Hey @nabeghe 

I would not delete these records as they are your payments for your store. Deleting them would basically remove all payments from your store. The reason that there is no `post_content` is that the data is stored in `postmeta`. Since this data is not content related, storing it as post meta allows us to specific queries for it where storing it as `post_content` would not.

In EDD 3.0 (the next major release that will be coming) all this data is moved to a custom table, so they will not exist in the `wp_posts` table.

In the future requests like this should be directed to our customer support team at https://easydigitaldownloads.com/support. We use Github for development tracking only.
