### ISSUE TITLE
Remove Legacy JS code for Software Licensing Metabox

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7136]
## Enhancement Request
The newer markup for EDD Metaboxes from https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2704 is being added to Software Licensing here: https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1179

This means that we can remove the legacy handler from EDD core here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/admin-backwards-compatibility.js#L16

@pippinsplugins and @cklosowski [had said ~2 years ago](https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1179#issuecomment-335594128) that they wanted to leave it in in order to support older versions of EDD SL. Is that still the case?

**Comment by mintplugins** [comment]
See testing steps here:
https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1179

**Comment by cklosowski** [comment]
@mintplugins I'd like to leave it in EDD core until we get the new markup released in https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1179 for at least a major SL release. If we release the new markup in 3.6.6, I'd say we can fully commit to it and remove all backcompat code in SL 3.7.

**Comment by mintplugins** [comment]
@cklosowski I'm unclear on how to actually do that in this case. Because core is detecting _anything_ that begins with `sl-`, we would have to name the classes for the SL metabox in [easydigitaldownloads/EDD-Software-Licensing#1179](https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1179) something that doesn;t begin with `sl-`. Otherwise, this code will take over. 

I'm either having a brain fart, or this isn't possible without a weird naming convention on the SL CSS classes. Thoughts?

**Comment by mintplugins** [comment]
After speaking with @cklosowski, we decided the best way to handle this is to separate the SL backwards compat JS into its own file. That way, when SL can dequeue the backwards compat once it is no longer needed. 

So for this issue, we'll separate all the back-compat JS into their own files.

**Comment by robincornett** [comment]
@ashleyfae I've been working on the related issue for SL and wondering about just making this a breaking change in 3.0 and removing the backwards compatibility scripts altogether there. The extensions involved will be getting 3.0 critical updates anyway (I know for sure EDD 3.0 will require Software Licensing 3.7, for example). What do you think?

**Comment by ashleyfae** [comment]
@robincornett That works for me. :+1:

**Comment by spencerfinnell** [comment]
@robincornett and I were discussing a few things related to this issue and when I was looking in to it I realized there were never proper deprecations for the "legacy" handling of the metabox. 

I'm wondering if completely removing the script/compatibility layer at once in 3.0 gives 3rd party extension authors enough of a notice to make the change after we've been handling it behind the scenes for ~5 years. We didn't even have open issues for the majority of our own extensions that need the updates.

There is mention of the new hook in the [Easy Digital Downloads 2.8 beta 1 available for testing](https://easydigitaldownloads.com/development/2017/06/29/easy-digital-downloads-2-8-beta-1-available-for-testing/) but as far as I can tell no follow ups or true deprecations after that.

**Comment by robincornett** [comment]
So, our current thoughts are that the script can go ahead and come out without issue, as it impacts four specific extensions which are all owned by Sandhills. @spencerfinnell pointed out that there are also significant sections of PHP related to this:

- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/downloads/metabox.php#L1459-L1515
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/downloads/metabox.php#L509-L531
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/downloads/metabox.php#L410-L420

However, since the `edd_download_price_table_head` and `edd_download_price_table_row` hooks have never been formally deprecated, Spencer suggests that we cannot remove that part of the backwards compatibility work without more warning. So my suggestion/thought is:
1. Continue with the work in PR #8212 to remove the script for 3.0.
2. Create a new issue/PR to be done soonest (2.10) to formally deprecate the two action hooks involved, either by using `edd_debug_log` or be a bit more aggressive and use `do_action_deprecated` to get a PHP Notice (my vote).
3. Create a new issue/PR to remove the legacy PHP code, possibly for 3.0.

@ashleyfae, what do you think?

**Comment by ashleyfae** [comment]
@robincornett That plan sounds good to me. Regarding point 2, Let's go with `do_action_deprecated`.
