### ISSUE TITLE
Unable to retrieve SL update on same site as EDD

### ISSUE THREAD

**Issue by JasonTheAdams** [easydigitaldownloads/easy-digital-downloads#7168]
### Expected behavior
When I install a EDD SL plugin on a website, I expect updates to work properly for that plugin. This is useful to us as we want to show off the plugin on the same site. Therefore, to update we'd have to delete the plugin and add it again.

### Actual behavior
When I install the plugin on the same site as where EDD is (i.e. EDD is on abc.com and I've installed and activated the plugin on abc.com), the plugin updates do not show up.

This is due to : https://github.com/easydigitaldownloads/easy-digital-downloads/blob/4aef85c45ebe99073bf628ae2881bb4cadd4d5e1/includes/EDD_SL_Plugin_Updater.php#L403

### Steps to reproduce the behavior
1) Install EDD and SL on a WP instance
2) Add a plugin as a product
3) Install the plugin on the same site, create a license, and activate it
4) Change the version of the plugin on the site to some previous value
5) Go to updates and notice the plugin does not show up.

EDD Version (or branch): 2.9.11

WordPress Version: 5.1

**Comment by afragen** [comment]
Is it reasonable to assume the EDD store doesn’t have the same update needs as the customer site? 

I assume that this is to avoid some sort of race condition.

**Comment by JasonTheAdams** [comment]
Thank you for your input, @afragen.

Do you not feel like it's a common scenario for a plugin seller to both sell and demo the plugin from the same site? If there was a better way to update the plugin than deleting and re-adding, it wouldn't be as much of an issue.

Others have remarked on a potential race condition. One individual noted that it may have to do with the fact that the updater runs in WP_Cron and checking against and needing to validate oneself would trigger the race condition.

The potential complexity is completely valid, but I still imagine it's simply going to feel like a bug, not a feature or limitation to folks, therefore it seems worth considering. Possibly checking to see if the current request is a validation and removing any hooks that may cause the race condition would suffice. I'm still wrapping my head around the exact race condition, so I haven't attempted a solution, yet.

**Comment by cklosowski** [comment]
@JasonTheAdams @afragen This is something we have logged on the Software Licensing repository, the challenge, however, is that your site goes into Maintenance mode when you start the plugin upgrades, and therefore retrieving the update package returns invalid since maintenance mode is active.

It's not a 'race condition', it's more of a condition that your site goes into while updating plugins that leaves your site unable to deliver the package update. As stated above, we have this as an open issue, however at this time have not found a solid solution to bypassing the maintenance mode that doesn't pose a risk to your site breaking in the process.

**Comment by cklosowski** [comment]
As a note, I closed the issue not because it is invalid, but because we have it logged in the repository where the code would have to be changed, EDD core just uses the updater class from there when it's updated.

**Comment by JasonTheAdams** [comment]
@cklosowski Ahh... yeah, that makes sense! Hard to handle the request for the update when the site is in maintenance mode. That's a real head scratcher. WP clearly made the assumption in its updater process that the updated files will always be remote.

It seems like — if this is even possible — you'd have to bypass the update as a request and instead retrieve the file directly. But I don't know enough about how the updater works to really speak with any confidence.

Thank you for chiming in an affirming the issue!

**Comment by cklosowski** [comment]
@JasonTheAdams No problem. It is a head scratcher. The main concern we have is that while we can likely find a way to "sideload" the version, we need a way for all requests _except_ for the updater package request to be done in maintenance mode, so that someone doesn't try and access the main front end while the new package is being written, otherwise you could end up in a state where they get a 500 error if all the files are not yet copied into place.

It's something we hope to solve with no side effects, but until then, there are a few ways we do it. Once is by using the git repos of our own projects and using `git export`. You could look at using something like this plugin as well, which allows updating via .zip file from the UI:
https://wordpress.org/plugins/easy-theme-and-plugin-upgrades/

**Comment by afragen** [comment]
You could use GitHub Updater and a webhook to automatically and quickly, usually less than 5 seconds, to update plugins. 😉

In all seriousness at some point the store will be unavailable for something. Since I now have a working local setup I’m going to see if this is really an issue though I can’t obviously test all scenarios.

**Comment by afragen** [comment]
So this is what I found locally. I think it's exactly as @cklosowski said. You simply cannot use core update methods to update a plugin in the store while trying to get the update from the store.

![screenshot_01](https://user-images.githubusercontent.com/1296790/53444670-a61f8400-39c3-11e9-9a77-e4da1c24e9f4.png)

**Comment by JasonTheAdams** [comment]
@cklosowski Thanks for the info! That plugin is definitely helpful in the workaround. Look forward to seeing what you come up with. It may require a change to core.

@afragen Thank you for testing that out. Now we know for sure. 😄

**Comment by afragen** [comment]
It might be possible to hook into the update mechanism and remove the maintenance mode, but that might cause other more serious issues.

**Comment by afragen** [comment]
Well, hooking into the update mechanism didn't work.

How do store owners currently update those plugins?

**Comment by cklosowski** [comment]
@afragen a variety of methods. Either with SFTP, or the easy plugin and theme updates plugin which allows uploading a new .zip file. Some just use `git export` via command line.

**Comment by kevinwhoffman** [comment]
With Give and WP Business Reviews, we update manually via FTP. I understand the technical hurdle better now with @cklosowski's explanation. When you're developing a new plugin, the plugin's site is the first place most devs will look to confirm updates are working, and I thought we had misconfigured something when we didn't see updates on our own site.

In the meantime, it may be helpful to document that it's not currently possible to update the plugin on the hosted site in this doc. I remember checking here when I first ran into the issue: https://docs.easydigitaldownloads.com/article/937-why-do-my-plugin-updates-not-show-up
