### ISSUE TITLE
Paypal Adaptive Payment is deprecated 

### ISSUE THREAD

**Issue by benotf** [easydigitaldownloads/easy-digital-downloads#7182]
Everything is in the title. You should not sell it any more and find another way (with express checkout, braintree for example) or subscribe to Marketplace... 
Thank you
Ref : h[ttps://www.paypal-engineering.com/2016/09/27/adaptive-payments-limited-release/ ](https://www.paypal-engineering.com/2016/09/27/adaptive-payments-limited-release/)

**Comment by pippinsplugins** [comment]
PayPal Adaptive Payments is still available because PayPal accounts created before the cut off are still able to use it.

Note, I'm going to close this issue since it is related to an add-on and not to the core Easy Digital Downloads plugin. This repo is for the core plugin only. If you'd like to discuss possible options, please contact the support team: https://easydigitaldownloads.com/support

**Comment by benotf** [comment]
Hello Pippin,

Sure, you can close it. I did already send my request to support, but
Daniel who answered me didn't understand what I said... I was looking for
an alternative, but it doesn't exist I guess.

You should change the notice on the add-on to explain it's discontinued
(PayPal side).

Do you know if "plugin team" is going to work on an alternative solution ?

Thank you very much for your email and your attention.


Fred,
