### ISSUE TITLE
You do not have permission to download this file after upgrading to 2.9.13

### ISSUE THREAD

**Issue by Pratik-Jain12** [easydigitaldownloads/easy-digital-downloads#7249]
# Instructions (START):
After updating EDD to 2.9.3 users are facing an error like "You do not have permission to download this file".

I have debug this this issue and found that function `edd_local_file_location_is_allowed` return false while checking "ABSPATH" and "WP_CONTENT_DIR" path

When we have attachment `$requested_file` argument is coming with DIR path like `E:\wamp\www\wprelease\wp\wp-content\uploads\edd\2019\05\Tulips-300x225.jpg`

ABSPATH becomes like this : `E:\wamp\www\wprelease\wp/`
WP_CONTENT_DIR path becomes like this : `E:\wamp\www\wprelease\wp/wp-content`

Condition is checking strpos but due to backward slash problem `\` it returns false. Same with WP_CONTENT_DIR condition.

### Steps to reproduce the behavior
1) After updating EDD 2.9.13
2) Navigate to purchase history.
3) Click on "View Details and Downloads"
4) Try to download the file.

### Information (if a specific version is affected):
PHP Version: 7.2.14
EDD Version (or branch): 2.9.13
WordPress Version: 5.2
OS : windows

**Comment by cklosowski** [comment]
@Zebedeu Are your files in the `wp-content` directory?

**Comment by Zebedeu** [comment]
> @Zebedeu Os seus arquivos estão no `wp-content`diretório?

yes ... are inside the directory wp-content /

**Comment by cklosowski** [comment]
The usage of `wp_normalize_path` has basically made this untestable from a unit test standpoint b/c we're tossing 'fake files' at it, in paths that don't exist when doing windows paths...so the unit tests are not going to help, since we're ending up with empty strings instead of the paths we are trying to use.

I'm going to have to setup a Windows server to do actual testing on these.

**Comment by Pratik-Jain12** [comment]
Hi,
I have checked it and it is working fine now. Thanks.

**Comment by Ratcreamsoup** [comment]
We're getting hit by this same problem after upgrading to 2.9.14. In our case the issue lies one step deeper, as we have symlinked wp-content/uploads to a path outside of the wordpress documentroot directory. In that case, wp_normalize_path doesn't resolve the issue that PHP's realpath( $requested_file ) uses the canonical path.

As a workaround we have moved the uploads directory to the canonical path, thus getting rid of the symlink, but this messes with our file storage and backup procedures.

Even though this may not be an issue for 99.9% of EDD installations, I have the feeling that it is a valid use case to move images and other binaries to a different file system or different path anyway than the code and use a symlink to keep the original directory layout intact.

So I'd like to re-open this bug report. Steps to reproduce are the same as in the original issue report.

Information:
PHP Version: `7.0.33-6+0~20190412071436.12+stretch~1.gbp26747c`
EDD Version (or branch): 2.9.14
WordPress Version: 5.2
OS : Debian 9.9 (Stretch)
