### ISSUE TITLE
3.0 - Fatal error when updating a log, update_meta method is missing

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7288]
### Expected behavior
Running this will update a log
```
$edd_logs->update_log(
array(
'post_content' => 'Updated Content',
'post_title'   => 'Updated Title',
'object_id'    => 1234567,
'object_type'  => 'updated_type',
),
array(
'custom_meta_key_1' => 'updated_meta_value_1',
'custom_meta_key_2' => 'updated_meta_value_2',
),
$log_id
);
```

### Actual behavior
`Call to undefined method EDD\Logs\Log::update_meta() in /app/public/wp-content/plugins/easy-digital-downloads/includes/class-edd-logging.php:332`

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

There does not appear to be any methods for adding/updating a log's meta. 

Issues I see:
- The [update_meta](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-edd-logging.php#L330) is not found
- The [add_meta](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-edd-logging.php#L218) method is not found

If I am tracing these back properly, I believe this ends up pulling in a Log object, which extends the Base Object: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-base-object.php

So when it calls $log->update_meta, it seems to be looking for that method in the Log object, which doesn't contain one.

**Comment by cklosowski** [comment]
Looks like we should just remove these references, as the new `Query` class knows to split off non-column items and put them in meta:
```
		// Splice new data into item, and cut out non-keys for meta
		$columns = $this->get_column_names();
		$data    = array_merge( $item, $data );
		$meta    = array_diff_key( $data, $columns );
		$save    = array_intersect_key( $data, $columns );

		// Maybe save meta keys
		if ( ! empty( $meta ) ) {
			$this->save_extra_item_meta( $item_id, $meta );
		}
```
If this is the case, we should just update the class to merge the meta and data into the same array and pass it into the `insert` and `update` methods for the query class handler so it does it's thing naturally.

**Comment by cklosowski** [comment]
Ok i've got this not fatal erroring, however we're hitting a case where we are only saving registered meta keys. I think we'll end up having some issues with this restriction as we've never required someone to register meta keys in the past:

```
		// Only save registered keys
		$keys = $this->get_registered_meta_keys();
		$meta = array_intersect_key( $meta, $keys );
```

This returns the example listed in the initial comment with no registered meta keys, and therefore doesn't insert any meta for the logs. We'll have to find a way to remove that restriction, but I'm not sure of the side affects @jjj, could you maybe provide some feedback?

I love the idea of restricting to a point, but I think that'll be a massive pain point for the migration to 3.0 since it was never a requirement to register them. Maybe we could introduce a `doing_it_wrong` call if we see someone trying to do this, still log it and save it, but that way they know they should register meta keys before EDD 3.X is releaased where we move to enforcing the meta keys being registered?

**Comment by mintplugins** [comment]
Are registered meta keys something we are doing across all meta tables in 3.0?

**Comment by cklosowski** [comment]
It appears so as this code above is in the `base-query` class.

**Comment by JJJ** [comment]
The original goal with only allowing registered meta keys was to guarantee the integrity of meta values, and to avoid it simply being a dumping ground for whatever doesn't fit.

Unregistered meta keys do not have sanitization callbacks; all that happens to those values in WordPress core is maybe_un/serialization, which is a known risk when it comes to serialized objects being magically invoked, so it's also an added bit of security hardening.

Because the majority of the meta data registration API has been considered "finished" since WordPress 4.6 (released 3 years ago) this is now more an expectation than a nice-to-have.

We _should_ go through everything, and make sure all meta keys are registered. I understand that kind of work is somewhat unrewarding, but it is also part of a necessary/required maintenance responsibility.

Here is what I think that base Query class could do in the meantime:
* Add support for unregistered meta keys in `save_extra_item_meta()`
* Add an extra meta-key/value to the `$item_id` that saves the array of _unregistered_ keys (maybe with a timestamp?) so the database has a way to communicate that "unsafe" keys and values exist on the `$item_id`
* Create/read/update/delete that key as needed
* Throw a notice (`doing_it_wrong()` or otherwise, like you said) on create/update when the array of unsafe keys is not empty

My intent with that unregistered keys array, is that there always exists a signature/fingerprint/log/feedback/something that the magic inside of `save_extra_item_meta()` failed gracefully, when and how.

I can put together a PR either way!

**Comment by cklosowski** [comment]
@JJJ I think I can take the PR work off your hands.

I agree, in a perfect world we'd have all registered meta keys...I'd love to see that happen as well, but the vast majority of devs building for EDD aren't doing it, would be my assumption. I think we should softly start encouraging them to do it for sure.

One thing I don't want is a bunch of doing it wrong notices when 3.0 launches...I wonder if there is a less obtrusive way to do it for 3.0, and then as we reach 3.1 we can throw a `doing_it_wrong()`.

I do like the idea of having a listing of unregistered meta keys somewhere as a registry, not sure what that looks like yet without impacting performance.

**Comment by cklosowski** [comment]
As a note, I think we _might_ hit some conflicts with #7283 but since that's further along we'll just accept it and work through them. Just noting for future us (me) in case we see issues.

**Comment by cklosowski** [comment]
I'm going to bump the points on this as the scope has changed from the original report with the supporting and cataloging of the non-registered meta keys.

Moving to a new sprint due to that.

**Comment by ashleyfae** [comment]
Closing this as I don't believe it's still an issue. Meta is now added via functions and doesn't use the Query class directly. Definitely no fatal errors.
