### ISSUE TITLE
3.0 - Quantity is not set on refund order items

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7307]
### Expected behavior
When I refund an order, I expect the "quantity" column to be correct in the order_items table. 

### Actual behavior
It is set to 0.

### Steps to reproduce the behavior
1) Buy an item.
2) Refund the order.
3) Look at the order_items table
4) Notice the quantity is set to `1` for the original order item, but is set to `0` for the refund order item.

<img width="1147" alt="Screen Shot 2019-06-19 at 3 26 30 PM" src="https://user-images.githubusercontent.com/1638128/59794432-f722f300-92a6-11e9-83d3-00cb3db9acd7.png">

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by cklosowski** [comment]
I believe this may be a database schema issue. We have quantity on the order items for the refunds being negated:
`'quantity'     => edd_negate_amount( $item->quantity ),`

The issue is then that we've made the `quantity` column an unsigned column:
`quantity bigint(20) unsigned NOT NULL default '0',`

Per the documentation for MySQL, the `unsigned` type for `bigint` has a minimum value of `0`.
https://dev.mysql.com/doc/refman/5.5/en/integer-types.html

So we either need to change this to a `signed` column, or we need to assume that an order with `refund` as the `type` is a negative quantity.

**Comment by cklosowski** [comment]
The only negative side affect of going `signed` that I'm aware of is the maximum allowed value, but for `bigint` the maximum value is `2^64 - 1` which is a lot of quantity! @JJJ is there something else I'm missing for the negative side affects of using a signed value?

**Comment by cklosowski** [comment]
While I'm on this topic, is it necessary for this to be a `bigint`? The storage for a `bigint` is 8 bytes, where as if we drop down to a `MEDIUMINT`, we drop down to 3 bytes and still retain a maximum of `8388607` and a minimum of `-8388608`.

If we split the difference we end with `INT` and that leaves us with 4 bytes of storage and a maximum of `2147483647` when signed. I seriously doubt quantities of that range will limit any usage of EDD in anyway, but could still produce substantial amounts of savings in the DB as the rows grow.

**Comment by cklosowski** [comment]
For reference, extrapolating these storage spaces across 200,000 rows, 4 bytes would use up 0.8MB for the entire table (just for the `quantity` column).

**Comment by JJJ** [comment]
Good catch. This is definitely a problem.

The only reason this is an unsigned bigint is because WordPress uses only those everywhere (it has no need to store a negative number anywhere itself.)

I agree that it is highly unlikely any of our users will ever have an astronomically large quantity value.

I’m generally not real worried about database size, but this is an easy place to optimize.

If, for some reason, we want to keep this unsigned, we _could_ fix this in PHP by looking at the status column, and saying that a “refunded” item status is always negative. I’m not suggesting we do this, but it would work fine. (Even if a single order contained an item swap, the “refunded” ones would always mean negative, and all other statuses would always mean positive.)

**Comment by cklosowski** [comment]
The largest issue i have with the column remaining a positive-only integer is that it now requires math to be done in PHP, which is exhausting and I feel is counterproductive to a lot of the efforts we've already made with this release.

I'm going to move this to an `INT signed`.

That will half our usage, while still allowing the right amount of space, and allow us to use negative numbers. I'll include an upgrade routine for this as well.
