### ISSUE TITLE
3.0 - Store the name of the price ID in the product_name column of the order_items table

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7308]
The order_items table has a column for `product_name`. This is good for immutability because you can always know what the name of the product was at the time of purchase. 

However, the price_id does not have its name stored in this table. If the site owner changes the name of a price_id at any time, any purchases of that item will change, including on things like the purchase receipt. 

@cklosowski recommended storing the Price Name after the Product Name in a format like this:

`Product Name - Price ID Name`

**Comment by mintplugins** [comment]
Also a note that it will be important to remove anywhere where we are appending the price ID when showing an order:

<img width="489" alt="Screen Shot 2019-06-20 at 3 49 52 PM" src="https://user-images.githubusercontent.com/1638128/59877179-4e8e9500-9373-11e9-9fa5-5bf07df1729b.png">

Possibly also in plugins like:
- EDD Invoices
- EDD PDF Invoices

**Comment by cklosowski** [comment]
I've been thinking on the backwards compatibilty on this and one thing to note, usually those areas pull the name by download ID, not the order item row. The main reason to keep these hard coded strings around, is so that if a product is deleted, we can still reference what was sold.

It think we should keep areas that pull the name and price ID by the stored IDs, and only fall back to the usage of the hard coded string for when those don't exist.

That will impact performance however.

**Comment by cklosowski** [comment]
@mintplugins this is ready for you to test further.

**Comment by mintplugins** [comment]
This is looking really good here. Great catches on all of those other places @cklosowski 

Email Screenshot"
<img width="316" alt="Screen Shot 2019-07-04 at 2 04 30 PM" src="https://user-images.githubusercontent.com/1638128/60683243-c32dfd00-9e64-11e9-8e21-3a614986de49.png">

Order View in Admin:
<img width="956" alt="Screen Shot 2019-07-04 at 2 04 38 PM" src="https://user-images.githubusercontent.com/1638128/60683247-c6c18400-9e64-11e9-8f34-cd10e768face.png">

Purchase Confirmation page:
<img width="756" alt="Screen Shot 2019-07-04 at 2 04 49 PM" src="https://user-images.githubusercontent.com/1638128/60683250-c9bc7480-9e64-11e9-8eb0-40c7bd89c9c2.png">

👍
