### ISSUE TITLE
3.0 - On the order page, changing countries does not change states

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7382]
### Expected behavior
When I go to "Orders" > Filtering Area > "More" > Switch Country, I expect the states to be updated to match that country. 

### Actual behavior
The states are not updated.

<img width="445" alt="Screen Shot 2019-08-20 at 11 05 38 AM" src="https://user-images.githubusercontent.com/1638128/63359405-b002be00-c33a-11e9-8d10-c9e7f32768e4.png">

### Steps to reproduce the behavior
1) Go to "Orders" > Filtering Area > "More" > Switch Country
2) I expect the states to be updated to match that country, but they do not.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by mintplugins** [comment]
I have pulled in #7297 as it is required for this issue. 

While the country switcher is now re-loading the proper states, the filter itself doesn't actually affect anything. 

Note that this purchase did not take place in Greenland, but it comes up when the filter is set for Greenland:

<img width="1243" alt="Screen Shot 2019-08-21 at 2 27 05 PM" src="https://user-images.githubusercontent.com/1638128/63457913-cdf61e80-c41f-11e9-9d4b-90def99492f1.png">

**Comment by mintplugins** [comment]
I'm getting an interesting URL when I filter it as well:

`http://unmigratededd32.local/wp-admin/edit.php?post_type=download&page=edd-payment-history&order_type=sale&mode=all&start-date&end-date&gateway=all&order-amount-filter-type=%3D&order-amount-filter-value&order-country-filter-value=GL&order-region-filter-value=all&s&_wpnonce=4e86e2b444&_wp_http_referer=%2Fwp-admin%2Fedit.php%3Fpost_type%3Ddownload%26page%3Dedd-payment-history%26order_type%3Dsale%26mode%3Dall%26start-date%3D%26end-date%3D%26gateway%3Dall%26order-amount-filter-type%3D%253D%26order-amount-filter-value%3D%26order-country-filter-value%3DUS%26order-region-filter-value%3DAZ%26s%3D%26_wpnonce%3D4e86e2b444%26_wp_http_referer%3D%252Fwp-admin%252Fedit.php%253Fpost_type%253Ddownload%2526page%253Dedd-payment-history%2526order_type%253Dsale%2526mode%253Dall%2526start-date%253D%2526end-date%253D%2526gateway%253Dall%2526order-amount-filter-type%253D%25253D%2526order-amount-filter-value%253D%2526order-country-filter-value%253DCA%2526order-region-filter-value%253DON%2526s%253D%2526_wpnonce%253D4e86e2b444%2526_wp_http_referer%253D%25252Fwp-admin%25252Fedit.php%25253Fpost_type%25253Ddownload%252526page%25253Dedd-payment-history%252526order_type%25253Dsale%252526mode%25253Dall%252526start-date%25253D%252526end-date%25253D%252526gateway%25253Dall%252526order-amount-filter-type%25253D%2525253D%252526order-amount-filter-value%25253D%252526order-country-filter-value%25253DCA%252526order-region-filter-value%25253DBC%252526s%25253D%252526_wpnonce%25253D4e86e2b444%252526_wp_http_referer%25253D%2525252Fwp-admin%2525252Fedit.php%2525253Fpost_type%2525253Ddownload%25252526page%2525253Dedd-payment-history%252526action%25253D-1%252526paged%25253D1%252526action2%25253D-1%2526action%253D-1%2526paged%253D1%2526action2%253D-1%26action%3D-1%26paged%3D1%26action2%3D-1&action=-1&paged=1&action2=-1`

**Comment by mintplugins** [comment]
It appears that every time I re-filter, it appends that to the URL instead of replacing it.

**Comment by mintplugins** [comment]
There doesn't appear to be anything built to handle filtering orders by country. Since the country of an order is recorded in the order addresses table, I assume some sort of a join query would need to be done here when country is attached to the args:

Country is part of the args sent to `edd_get_orders`:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/class-payments-table.php#L700

But `edd_get_orders` doesn't have a way to handle `country`:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/database/queries/class-order.php#L107-L160

Is that something we need to add to the query class @JJJ? Or is there another way this should be handled?

**Comment by cklosowski** [comment]
@mintplugins yeah looks like you're right. We have two options:

1) Add the ability to query orders by country, which would likely require a join of some sort.
2) Run two queries, first against the order addresses table to get the order_id column for order addresses that match the country, and then get the orders from the orders table, however that would also require a join to the orders table along with the order addresses table in order to limit things based of gateway, amount, date, etc.

I think our best bet is option 1, to allow the orders table to be queried via a join on the order addresses table. I'll see what I can work up.

**Comment by JJJ** [comment]
Basic history lesson for general public: the idea with recording order addresses separately was part of the snapshot idea… physical customer addresses can change, and we’d want to retain some record of the address that was used at the time an order was created.

A JOIN is perfectly acceptable for this. However, the portion of the database class to handle column-to-column relationships is unfinished. Meta queries are hard coded, because it was easy, and because most everything has meta. Mapping JOINable column relationships just never got done.

That means that any JOINs like this will require custom MySQL for now, which frankly is not the end of the world here.

My recommendation would be to watch for those args to be passed in, and have private methods to handle them for now. Query the tables directly and return a paginated list of order IDs, then do a separate edd_get_orders() call based on those IDs. This way, the JOIN stays in ached, but the order objects will hit or miss/prime theirs.

**Comment by cklosowski** [comment]
Thanks @JJJ great feedback

**Comment by cklosowski** [comment]
I've decided to make a new issue for the database support for this issue. The original issue was to fix the front end display so that the state list changes when the country input changes, we should focuse on that only for this issue, and open a new one to support the database query by country/region.

**Comment by cklosowski** [comment]
Created #7397 in order to handle the database side of things.

**Comment by cklosowski** [comment]
Just making a note here, it's not an actionable item, but if a country has no pre-defined regions (would output a text field on checkout/address forms), the dropdown is only 'All Regions'. I feel like we should possibly move this to a readonly state, but that isn't necessary at this time, can be a follow up UI improvement.
