### ISSUE TITLE
Update product schemes/markup

### ISSUE THREAD

**Issue by Sjeiti** [easydigitaldownloads/easy-digital-downloads#7387]
### Explain your enhancement (please be detailed)

As of late Google search console shows the following error: `Either “offers”, “review”, or “aggregateRating” should be specified`. There are also numerous warnings, like: `Missing field “brand”`, `Missing field “SKU”`, `Missing Field “offers”`.
Product schemes/markup should be updated accordingly.

### Justification or use case

No errors (or warnings) in Google search console.

**Comment by mintplugins** [comment]
Just a note that the entire schema.org markup is being switched over to json+ld in version 3.0. Changes were made here:

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5240

We may still need to add aggregateRating and the other missing fields there though.

**Comment by cklosowski** [comment]
This is a little interesting b/c `Reviews` and `aggregateRating` should not apply unless the Reviews addon is enabled. It does state `or offers`. So we just need to make sure EDD core has the offers filled out, which is the pricing of the product, both single and variable pricing.

For the Brand and SKU, those are unique, we can probably use the Brand being the Store name, or vendor name if FES is enabled (via a filter?), but for the SKU we shouldn't output unless someone has a 'SKU'. Part of me leans towards making sure that we've designated the product type properly, because it seems Google is applying physical product attributes (like sku and Brand) to products, which most digital products do not have/need.

**Comment by spencerfinnell** [comment]
The `aggregateRating`, and `review` fields are recommended, not required. Not providing them is not an error, it is reported as a `Warning` in the testing tool: https://search.google.com/structured-data/testing-tool/u/0/

> The aggregateRating field is recommended. Please provide a value if available.
> The review field is recommended. Please provide a value if available.

A few improvements we can make though:

- `image` is currently set to `false` if there is no featured image. This is an invalid URL. This entry should be omitted if there is no image available.
- `description` is added as an empty string.  This entry should be omitted if there is no description available.
- We should be able define `priceValidUntil` for the available `offers` as a pretty arbitrary value in the future, though this can also be safely omitted completely. 
- `sku` is currently set to `-` if there is no SKU. It should fallback to the Download ID or be omitted to ensure it remains unique. 

EDD Reviews should then be updated to fill in `aggregateRating` and `review` if available.

**Comment by spencerfinnell** [comment]
PR #7571 implements the above improvements and ensures core provides as much information as possible and that there are no **errors** (_warnings will still appear).

**Comment by spencerfinnell** [comment]
Reviews extension follow-up logged in https://github.com/easydigitaldownloads/edd-reviews/issues/265
