### ISSUE TITLE
3.0 - Stripe refunds not working

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7399]
The new refunds API in 3.0 needs to be integrated and tested with Stripe ( and ultimately all gateways) extensively. 

This issue is to ensure that refunds work with Stripe, and that subscription cancellation functionality from Recurring Payments also works with Stripe.

**Comment by spencerfinnell** [comment]
It seems like the issue for Stripe is the change from `publish` to `complete` as the "completed" payment status. 

The `update_status()` method _handles_ this by switching `publish` to `complete` as the `$old_status`, but that doesn't fix extensions that have been specifically looking for certain status changes from `publish` to act upon.

https://github.com/easydigitaldownloads/edd-stripe/blob/master/includes/payment-actions.php#L915

Perhaps we could:

- In `update_status()` if `$old_status` is `complete` run a _fake_ version of `edd_update_payment_status` that explicitly sets `$old_status` to `publish` and add a deprecation notice.

```php
do_action( 'edd_update_payment_status', $this->ID, $status, $old_status );

if ( 'complete' === $old_status ) {
  // Add a log about this needing to change...
  do_action( 'edd_update_payment_status', $this->ID, $status, 'publish' );
}
```

- Alert developers via a blog post that hooking in to `edd_update_payment_status` action should check for both `publish` and `complete` statuses when performing additional processing in the future.

That should allow extensions to make preemptive updates, but not break if they don't.

**Comment by nosegraze** [comment]
PR for the above issue: #7465

I've confirmed that fixes the refund problem. Still running more Stripe tests though to see if there's anything else to do here.

**Comment by nosegraze** [comment]
Getting this console error while adding a new card via the `[edd_subscriptions]` update payment method shortcode:

![Screenshot from 2019-11-19 16-32-48](https://user-images.githubusercontent.com/6324272/69165918-44232380-0aea-11ea-991a-023610a44207.png)

```
TypeError: name_field.validateCreditCard is not a function
```

From `assets/js/frontend/checkout/index.js`. Looks like it's due to using `validateCreditCard()`, but the jQuery card validator script is not being included. However, really I don't think that whole `EDD_Checkout` is needed on this page.

**Comment by mintplugins** [comment]
Just adding a few more tests I think we should cover since EDD Stripe has unique code for these situations:

## Recurring Tests

- [ ] Refund an initial subscription payment and set the subscription to cancel
- [ ] Refund a initial subscription payment and set the subscription not to cancel
- [ ] Refund an renewal subscription payment and set the subscription to cancel
- [ ] Refund a renewal subscription payment and set the subscription not to cancel

## Software Licensing Tests

- [x] Early renewal of license (non recurring)
- [x] Early renewal of license (recurring)
- [ ] Upgrade license (non recurring)
- [x] Upgrade license (recurring)

**Comment by nosegraze** [comment]
Thanks for that! I'll start working through them.

**Comment by nosegraze** [comment]
Something is definitely wrong with SL manual renewals. I got a whole new license key instead of renewing the existing one.

**Comment by nosegraze** [comment]
I think I'll need some help tracing this @mintplugins . I'm getting a little lost in all the meta rerouting.

Here's what I've found RE SL manual renewals:

- Everything looks okay prior to payment. Renewal is correctly added to cart, etc.
- What fails is `edd_sl_set_renewal_flag()`. The renewal is not picked up from the `$payment->cart_details` loop.
- I _think_ (not sure) that payment meta stuff was converted to order meta under the key `payment_meta`, however the license renewal flag is NOT set here.
- The license renewal flag is set as order item meta correctly with keys `_option_is_renewal` and `option_license_id` and `option_license_key`. But `$payment->cart_details` isn't being routed there, which is why it's not being picked up.

**Comment by nosegraze** [comment]
> I think I'll need some help tracing this @mintplugins . I'm getting a little lost in all the meta rerouting.
> 
> Here's what I've found RE SL manual renewals:
> 
> * Everything looks okay prior to payment. Renewal is correctly added to cart, etc.
> * What fails is `edd_sl_set_renewal_flag()`. The renewal is not picked up from the `$payment->cart_details` loop.
> * I _think_ (not sure) that payment meta stuff was converted to order meta under the key `payment_meta`, however the license renewal flag is NOT set here.
> * The license renewal flag is set as order item meta correctly with keys `_option_is_renewal` and `option_license_id` and `option_license_key`. But `$payment->cart_details` isn't being routed there, which is why it's not being picked up.

Split this into a new issue.

Instead of having one mega "test all the extensions with Stripe" issue with one single PR that fixes everything, I'd like to create separate issues for each problem we encounter through this testing.

I'd like to keep this one issue focused on tackling this problem, which we already have a PR for:

> It seems like the issue for Stripe is the change from `publish` to `complete` as the "completed" payment status.
> 
> The `update_status()` method _handles_ this by switching `publish` to `complete` as the `$old_status`, but that doesn't fix extensions that have been specifically looking for certain status changes from `publish` to act upon.
> 
> https://github.com/easydigitaldownloads/edd-stripe/blob/master/includes/payment-actions.php#L915
> 
> Perhaps we could:
> 
> * In `update_status()` if `$old_status` is `complete` run another version of `edd_update_payment_status` that explicitly sets `$old_status` to `publish` and add a deprecation notice.
> 
> ```
> do_action( 'edd_update_payment_status', $this->ID, $status, $old_status );
> 
> if ( 'complete' === $old_status ) {
>   // Add a log about this needing to change...
>   do_action( 'edd_update_payment_status', $this->ID, $status, 'publish' );
> }
> ```
> 
> * Alert developers via a blog post that hooking in to `edd_update_payment_status` action should check for both `publish` and `complete` statuses when performing additional processing in the future.
> 
> That should allow extensions to make preemptive updates, but not break if they don't.
