### ISSUE TITLE
3.0: Remove default tax rate

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7511]
Per the conversation [here](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6840#issuecomment-570452997), we are going to remove the default tax rate and then show a notice to site admins when we detect that a default tax rate has been previously configured.

**Comment by pippinsplugins** [comment]
PR submitted.

A notice is now displayed if the `tax_rate` option is detected and automatically removed when the settings are saved (which removes not-registered settings).
<img width="1353" alt="Screen Shot 2020-01-07 at 4 18 35 PM" src="https://user-images.githubusercontent.com/1034109/71934139-68ee5b80-3169-11ea-96c5-b35f941bf5c7.png">

**Comment by spencerfinnell** [comment]
Should this notice be shown on all dashboard pages? And perhaps something a little more warning-y? It seems like an important one to review after upgrading.

**Comment by spencerfinnell** [comment]
Maybe:

<img width="895" alt="Screen Shot 2020-02-05 at 2 23 23 PM" src="https://user-images.githubusercontent.com/491124/73875335-22048c00-4823-11ea-8b6e-3582c24b8588.png">

Potentially too far in the _error_ realm, but I do think it's an important notice. Tweaked the copy a little.

**Comment by pippinsplugins** [comment]
@spencerfinnell I like that. Push it up?

**Comment by spencerfinnell** [comment]
@pippinsplugins Pushed along with some other changes. I was unable to get the option to be removed because when on the "Rates" tab no input settings were being submitted. This bypassed the "unset if empty" settings logic.

In #7512 I added a custom callback for `tax_rate` that outputs a hidden field with an empty value along with a notice about verifying the settings below (with the header notice hidden). This allows saving settings _on that section_ to remove the `tax_rate` option.

<img width="830" alt="Screen Shot 2020-02-07 at 8 25 33 AM" src="https://user-images.githubusercontent.com/491124/74036152-b688fe80-4989-11ea-9a0d-248f5f750bf2.png">
<img width="1105" alt="Screen Shot 2020-02-07 at 9 11 58 AM" src="https://user-images.githubusercontent.com/491124/74036292-f819a980-4989-11ea-9560-1665893030b8.png">

**Comment by pippinsplugins** [comment]
Good catch @spencerfinnell. All tested and working great here. Merging.
