### ISSUE TITLE
3.0 - Allow Product Dropdown to Show Variations + Standard Downloads

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7551]
### Explain your enhancement (please be detailed)

When using `EDD()->html->product_dropdown()` allow for downloads with variations to show just variations, but still show standard downloads alongside.

### Justification or use case

Currently when showing only variations (not `(All Price Options)`) standard Downloads are not added to the prepopulated list of Downloads or included in search results.

This limits the results to something like:

```
Download A: Price 1
Download A: Price 2
```

vs.

```
Download A: Price 1
Download A: Price 2
Download B
Download C
```

Previously/Related #6760 #7149

**Comment by spencerfinnell** [comment]
I'm wondering if it's worth mapping `show_variations_only` to something like `show_variable_prices_only` which matches more what it's actually doing.

```php
EDD()->html->product_dropdown( array(
  'number' => 10,
) );
```

```
Download A: All Price Options
Download A: Price 1
Download A: Price 2
Download B
```

```php
EDD()->html->product_dropdown( array(
  'number' => 10,
  'variations' => false,
) );
```

```
Download A: All Price Options
Download B
```

```php
EDD()->html->product_dropdown( array(
  'number' => 10,
  'variations' => true,
  'show_variable_prices_only' => true,
) );
```

```
Download A: Price 1
Download A: Price 2
Download B
```

It seems like currently `show_variations_only` is used for creating a dropdown for Download Price Assignment and adding items when creating an Order, and introduced in 3.0 -- so a mapping may not be needed.

**Comment by pippinsplugins** [comment]
I like the idea of `hide_all_price_options`.

**Comment by cklosowski** [comment]
I’m good with that naming convention. Let’s move forward with that as an additional configuration for the products drop down.

**Comment by robincornett** [comment]
I just ran into this same issue today when I was trying to add a standard product to a bundle. Only variations were showing.

Looking at the logic in the product_dropdown method, it looks like in the foreach loop, that if both `variations` and `show_variations_only` are set to `true` (which is the case in the bundles), that any `$product` _without_ variable pricing will not be added to the list of possible bundle downloads. I think it's possible to fix this by [adding `! $has_variations` to the first conditional in the loop](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-edd-html-elements.php#L129) (as another `||`), but not sure if this will break other uses of this method.

I am not sure of the finer difference between setting `variations` and `show_variations_only`, and in this loop, they seem to be equivalent.

**Comment by cklosowski** [comment]
They are different in a very specific case.

For instance with things like Discount codes, you would want the ability to choose the product as a whole, or a specific variation, this would be `variations => true` and `show_variations_only => false`, which would allow you to meet this need.

Then there is the idea of a bundle, in which you need to pick a specific price ID to supply to the bundle. In this case you want `variations => true` and `show_variations_only => true`. This way the drop down only shows you product variations, and not the ‘main’ product which cannot be assigned as a bundled product since it would need a price ID association.

**Comment by spencerfinnell** [comment]
We should introduce a private method or helper function to that handles querying the products and building the array of options that get fed to `$this->select()` so we can add unit tests to define what is supported.

**Comment by robincornett** [comment]
I'd like to revisit this issue because at the moment, the product options are not working correctly for:
- adding products to bundles (only variations of variable products show; standard/single price items do not show)
- discounts (only bundles/parent items show, not variations...I think it's possible a store would want to discount one variation, but not necessarily another)

I think it's possible to fix the discounts by adding `'variations` => `true` to those fields, but at this point I still do not know what could be added to the bundle parameters to make single price products to show. `variations` and `show_variations_only` are both set to true, and [this condition](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/5751f4729ef20d33003291107fb98cd7754c3d9c/includes/class-edd-html-elements.php#L129) means that simple/single price products cannot be shown if that's the case.
