### ISSUE TITLE
Division by zero warnings in cart

### ISSUE THREAD

**Issue by Spreeuw** [easydigitaldownloads/easy-digital-downloads#7613]
## Bug Report
Got this error in my error log:

> Division by zero in /wp-content/plugins/easy-digital-downloads/includes/cart/class-edd-cart.php on line 689

I'm not sure what cart item (+discount?) exactly triggers this but it seems like an easy fix?

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): 2.9.20

WordPress Version: 4.9

Any other relevant information:

**Comment by robincornett** [comment]
I've been working to try to track this one down and although I know more, I haven't been able to successfully replicate it. What I can tell so far is this:

* it happens with a **flat** rate discount only, not percentage
* the discount must be **global**, that is, applied to the entire purchase
* the error happens when the discount is being calculated for each item in the cart (a flat discount of this type will be applied to everything being purchased, not just one item, so appears to be prorated across all items)
* the calculation can happen on page load (entering checkout) or as part of an ajax request (applying or removing the discount, or adding an item to the cart, for example)
* the function which contains the calculation is run on every item in the cart
* the calculation is not run if the item is *excluded* from the discount
* the `0` in question is the subtotal of the items in the cart,

The function is looking to get the discounted price of one item, but is run on everything in the cart, so it runs multiple times. If a discount is applied, and the item is not free, then the function cycles through all the discounts.

If the discount is both global and a flat amount, then the subtotal of the items is calculated by cycling through all items in the cart. The subtotal is initially set to `0.00` and then the cart item amounts are added to it. So theoretically, if there were no items in the cart, then the subtotal would stay at `0.00`; however, if there are no items in the cart, then the function won't be running.

This issue looks similar to #6901, which was resolved by making sure the item being checked had a price. The additional fix ("Fix 1") of making sure the math isn't run if it will result in dividing by 0 was not implemented, but maybe should be.

**Comment by cklosowski** [comment]
@robincornett perfect summary of the issue. We should move forward with that other fix that was not implemented for sure. I was pretty sure we didn't need to go quite that far but apparently there is still an edge case where it can rear its head.

I would say we should move forward with implementing a fix that stops the division by `0` from happening during this process.

**Comment by Spreeuw** [comment]
Good investigation! I suspect someone was bruteforcing discount codes because I got many of these errors a few days in a row and then none after that. I was too late to do more extensive logging, but I did find that all the matching discount codes were an email address, which would make sense if someones bruteforcing this... Quite the edge case, but like you said (and what I meant in my original report), doing the check to prevent division by 0 in the first place is the obvious solution here.

**Comment by robincornett** [comment]
The suggested fix was to add this:

```php
$subtotal_quantity = ( $price * $item['quantity'] )
$subtotal_percent  = ! empty( $subtotal_quantity ) ? ( $subtotal_quantity / $items_subtotal ) : 0;
```

but I think the `empty` check should actually be against the `$items_subtotal`, not the quantity, as that's where the error seems to be.  So instead:

```php
$subtotal_percent  = ! empty( $items_subtotal ) ? ( $subtotal_quantity / $items_subtotal ) : 0;
```

**Comment by cklosowski** [comment]
I cannot for the life of me replicate this whole thing, even with the information provided above. Seems like we might be missing a slight bit of the puzzle on the product configuration.

I have looked over the code change though and it does prevent the edge case that apparently got hit.

**Comment by Spreeuw** [comment]
I'm sorry about that - as I wrote, I suspect that someone was trying email addresses as discount codes with a brute force script in my store and I'm not even sure if that was on purpose (perhaps it was a bot using a wrong field for login) and it's even possible this was fired at the AJAX endpoint for applying a coupon without anything in the cart... All I saw was the (many) notices in my error log - I didn't mean to have 3 people spending so much time on something that is such an edge case bug.
Thanks for the fix! 💯

**Comment by cklosowski** [comment]
No problem at all @Spreeuw!
