### ISSUE TITLE
EDD 'edd-privacy-policy' toggle code should be in JS file.

### ISSUE THREAD

**Issue by Pratik-Jain12** [easydigitaldownloads/easy-digital-downloads#7631]
## Bug Report

During the EDD support (https://wordpress.org/support/topic/move-category-description-down-the-products/#post-12515723) I found one issue related to EDD "Show Terms & Condition" toggle button.

The toggle JS code is placed inline so It may create a problem for those theme who loads WordPress jQuery at footer. In this case your code generate error like 'jQuery' is not found.

This generally happens when web server is little slow in loading the assets. In this case toggle code runs before the jQuery load.

Please refer below screenshots
http://prntscr.com/rci210
http://prntscr.com/rcho9z

### Expected behavior
The JS toggle code should be in EDD JS file so this type of issue will not be generated.

### Information (if a specific version is affected):
PHP Version: 7.3.1
EDD Version (or branch): 2.9.21
WordPress Version: 5.3.2

**Comment by cklosowski** [comment]
I believe these exist here as a backwards compatibility with the 'disable ajax' feature we used to support. If that was used, it didn't load the JS files that were needed.

I'm going to put this in EDD 3.0 since it would constitute a 'breaking' change to move that to the JS that some stores might not load (older stores).

@spencerfinnell can we get this added to the checkout JS?

**Comment by spencerfinnell** [comment]
PR #7655 moves javascript to `edd-checkout-global`.
