### ISSUE TITLE
3.0 - Reports - Download report for specific variation still shows pie charts for variations.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7674]
### Expected behavior
When viewing the reports of a variable priced product, but just a single variation, not all variations, the pie chart showing the variation purchase distribution should be hidden.

### Actual behavior
The pie chart for variation purchase distribution is still shown when a single price ID is selected.

### Steps to reproduce the behavior
1) Create and buy different variations of a downlaod
2) Visit the Downloads > Reports > Downloads and filter by a single variation of a product.
3) See that the pie charts sill show

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7669

@cklosowski When thinking about #7669 I was leaning towards keeping the endpoints registered but not adding them to the actual report if they are irrelevant. Using that method allowed for what I think may be easier to grok than big conditionals wrapping the endpoint registration.

```php
$charts = array_filter( array(
	'chart_1',
	'chart_2',
	'chart_3',
), function( $endpoint ) use ( $download ) {
	// Determine if endpoint is relevant...
} );

$reports->add_report( 'foo', array(
	'endpoints' => array(
		'charts' => $charts,
	)
) );
```

**Comment by cklosowski** [comment]
So if I'm reading your thought process right, we could also exclude things like the pie graphs and only 'conditionally' register them alongside when they are relevant?

That would make #7669 a blocker, and once that method of 'registration' exclusion/inclusion is done we can complete this? Or even just do thing alongside #7669?

**Comment by spencerfinnell** [comment]
@cklosowski They would still be registered as an endpoint, but not added to the report. There is no extra overhead by keeping the endpoint registered since it's wont be executed if it's not attached to the report. With the current conditionals around the endpoint registration they are not output on the Report because when the Report sees them as invalid (since they aren't registered).

#7669 wouldn't necessarily be a blocker but I think we should establish a pattern for how we determine if an endpoint should be shown:

1. The endpoint isn't registered therefore it silently fails/isn't attached to the Report.
2. The Report doesn't declare the endpoint as a dependency.

My proposal aligns with the second option.

**Comment by spencerfinnell** [comment]
PR #7687 addresses these specific charts as well.

**Comment by spencerfinnell** [comment]
@cklosowski Can we close this in favor of #7687 and https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7687?

**Comment by cklosowski** [comment]
@spencerfinnell sure
