### ISSUE TITLE
3.0 - Question - should we add backwards compatibility for WP_Queries using the "edd_payment" post type?

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7685]
( @cklosowski you said to add the label `type-question` but there is no such label anymore. Wasn't sure if you wanted me to create one. )

When someone does a `get_posts()` / `WP_Query` call with the `edd_payment` post type, we throw a [`_doing_it_wrong()` notice](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/compat/class-payment.php#L90-L117), but we don't actually do anything to reroute this query to our new orders database. As one real life example, this means the legacy Stripe report no longer works in 3.0 because it uses `get_posts()` https://github.com/easydigitaldownloads/edd-stripe/blob/master/includes/admin/reporting/class-stripe-reports.php#L53-L76

Should we add backwards compatibility here?

Pros:

- It's nice to have. Code still using those queries won't break when updating to 3.0.

Cons:

- People will be expecting a `WP_Post` object, which essentially doesn't exist anymore in 3.0 so we'd have to awkwardly construct those somehow.
- Maintaining backwards compatibility like this encourages people to keep using deprecated functions. It might be better to do something to identify people/add-ons that are still using `get_posts()` calls and show warnings/notices to them _now_ about needing to update those in preparation for 3.0. (Or update our own, where possible.)

**Comment by cklosowski** [comment]
Added @ashleyfae. I forgot we moved it to `type-request`

**Comment by spencerfinnell** [comment]
I think it makes sense to route these since we are routing things like `get_post_meta()`.

**Comment by cklosowski** [comment]
The only thing that would be of concern is we’re going to have to return items in the `WP_Post` format since `get_posts` is expecting `WP_Post` objects, not `EDD_Order` objects.

**Comment by JJJ** [comment]
I believe @sunnyratilal and I concluded that full backwards compatibility was impossible back when we were building this.

Sunny may remember more (because he did the bulk of the research into it originally) but I remember something about it being impossible to safely predict the MySQL that `$wpdb` and `WP_Query` would generate, given the query arguments, meta-query, and date-query possibilities.

Some queries are always the same, allowing us to do some comparisons and then redirect them to their new equivalents. But calling `get_posts()` does not look discernibly different than using `WP_Query`, and `get_posts()` does not have a unique set of arguments or a filter or anything to indicate its usage to let us intelligently intercept it in a way that does not potentially interfere with other things.

One example is `EDD_Discount::is_used()` which still falls back to calling `get_posts()` using the `edd_payment` post type even in 3.0, though perhaps that's been edge-cased out by now.

Also of note is `Payment_Back_Compat_Tests::test_get_posts()` which is testing explicitly to make sure that `get_posts()` continues to work. See #4576.

**Comment by ashleyfae** [comment]
Just noting that in our beta announcement we will be advertising this:

```php
// NO LONGER VALID
$payments = get_posts( array(
    'post_type'   => 'edd_payment',
    'post_status' => 'publish'
) );

// NO LONGER VALID
$payments = new WP_Query( ( array(
    'post_type'   => 'edd_payment',
    'post_status' => 'publish'
) );

// Valid in both 2.9 and 3.0
$payments = edd_get_payments( array(
    'status' => 'publish'
) );
```

With that in mind, and with JJJ reporting that full backwards compatibility is near impossible anyway, I'm inclined to say we don't bother trying to add it. People should be using `edd_get_payments()`, which we _do_ support.
