### ISSUE TITLE
3.0 - Customer List Tables Tabbed Navigation URLs Can Be Incorrect

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7771]
### Expected behavior
The tab navigation links above the customers list tables should take me to a link showing all customers/emails/physical addresses.

### Actual behavior
Using the physical addresses table as an example, but the emails table is similarly affected: if I click the customer's name to view all addresses related to that customer, the tabbed navigation link for Physical Addresses is updated to this:

```
https://edd30.local/wp-admin/edit.php?post_type=download&page=edd-customers&page_type=physical&s=c%3A84
```
 So I am unable to return to an unfiltered/non-search view. All three tabs are affected, but I don't see a similar filter link in the main customer table rows.

### Steps to reproduce the behavior
1) in a 3.0 site, visit Downloads > Customers
2) then click on either the Email Addresses or Physical Addresses tab
3) click on a customer name to view all related addresses (filtered view)
4) try clicking on one of the tabs at the top of the page again

### Information (if a specific version is affected):
PHP Version: all
EDD Version (or branch): release/3.0
WordPress Version: 5.4

Any other relevant information:
Related: #7762

**Comment by spencerfinnell** [comment]
I have mixed feelings about the current behavior.

Clicking a Customer name essentially performs a search (adding `c:ID` to the search field). The search is persisted when switching between tabs (except for the main "Customers" tab). 

The search is a little confusing because it's not immediately apparent what happened, but also because the counts for the filters (which don't apply since there aren't other states) aren't updated.

My initial thought would be to adjust the link in the "Customer" column while viewing the "Email Addresses" or "Physical Addresses" to just link directly to the Customer record. This presents that  Customer's email and physical addresses all in one place. However, the tables in the Customer record would maybe benefit from having "Delete" links there as well.

**Comment by robincornett** [comment]
I have another issue open about the action links/filter behavior as well.

Regardless of the search behavior, which I agree is a bit disconcerting, the tabbed navigation links are incorrect. Currently, if you do anything which displays the customer list and modifies the URL, the tabbed links lock you in.

For example, in the Email Addresses table, I search for "example.com", and the Physical Addresses URL now becomes:

```
https://edd30.local/wp-admin/edit.php?s=example.com&_wpnonce=09a1fcfc7a&_wp_http_referer=%2Fwp-admin%2Fedit.php%3Fpost_type%3Ddownload%26page%3Dedd-customers%26page_type%3Demails&action=-1&paged=1&action2=-1&post_type=download&page=edd-customers&view=customers&page_type=physical
```

The only way I can "reset" the search is to use the link in the admin menu on the left--the three tabbed navigation links lock me into using the current URL. This behavior happens when using the search for any of the customer tables.

The linked PR changes the URL building behavior to properly retrieve the base admin url using `edd_get_admin_url()`.

**Comment by spencerfinnell** [comment]
@robincornett This is only "broken" if we decide that the search shouldn't be persisted between tabs. It's technically the correct behavior right now based on how filtering/search for addresses for a specific Customer works.

I think if your suggestions from #7762 are added then the current behavior (persisting the search) would be less desirable because it's less likely that the search will apply to both address types.

**Comment by robincornett** [comment]
The search being persistent is confusing, I think, and the results don't necessarily persist.

If I have a customer named "Bill" and I search for his first name on the Customers tab, I'll get a list which includes him. If I click over to the Email Addresses tab, I may just get an empty table unless his email address includes "bill". If I click over to the Physical Addresses tab, I won't get any results, because the customer name won't be included in that search.

I know the order screens have similar behavior, but they include a filter bar which shows the current search string, and can be cleared. I think if the customer search behavior is going to match the orders, then a similar filter bar maybe needs to be implemented. Not having it makes the tabs and subsequent behavior very confusing to me.

**Comment by ashleyfae** [comment]
I'm happy with clicking on a different tab clearing search. I think WordPress core's own implementation of list tables sets the expectation that clicking around loses your search. EDD doesn't always follow that, but as a close example, if you go to Posts > All Posts, search, then click one of the status filters, you lose your search. (I don't think EDD is doing this, but just an example of similar-ish behaviour from core.)

I think what Robin said above is a good argument: our own implementation of the search isn't consistent across the different tabs. So that doesn't make it particularly useful.

I think we make it not persist for now, and we can always revisit that decision later if/when we build up better consistency.
