### ISSUE TITLE
Run API processes later

### ISSUE THREAD

**Issue by techgarageblog** [easydigitaldownloads/easy-digital-downloads#7792]
**Run API processes later**

Actually, i build a store and the checkout page (payment process) is really slow. A view into New Relict shows me that every API request is the problem. API to Stripe, API to Jilt and API to Mailchimp. Now i can deactivate all these plugins but that's not the idea, right? 

Why all these request simultaneously? My feature request is, that all this information sent out later, after the payment process is done. So, the client has a nice experience, and we get the marketing information

**Comment by cklosowski** [comment]
We currently have a single event cron called `edd_after_payment_actions` that supplies the payment ID.

Items like Stripe require to be run, as it is part of the payment process. Jilt and Mailchimp can both be used to send receipts which also (currently) be run at the action of completing.

We've been working on moving some of the less critical items over to the after payment actions, which run after the process of the customer's purchase path.

Since we already have this in EDD core as an action to hook into, and we have plans to move other less critical items over, I'm closing this since core does offer this ability via hooks.

Thanks for the suggestion @techgarageblog
