### ISSUE TITLE
3.0 - After Migration, Email and Physical Address Dates are Based on Migration Date

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7859]
### Expected behavior
When I see a date in the admin, I expect it to be meaningful.

### Actual behavior
After migrating data from EDD 2.9 to 3.0, all migrated email and physical addresses show the migration date as the Date in the list tables, and as the "first used" date (for physical addresses) when viewing the customer record.

### Steps to reproduce the behavior
1) Migrate data from EDD 2.9 to 3.0
2) View the list tables for email and physical addresses

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
When viewing the individual customer screen, the "first used" date can be helpful information, but I'm not sure it's really needed on the list table. Wherever the date shows, I think it should be meaningful...I don't know if it is possible to pull the order date in when setting the address date during migration, but that seems like it would be a logical option.

**Comment by ashleyfae** [comment]
Looks like it might be possible for some, but not all.

**Addresses from orders**

Addresses stored in payment meta with an order could use the order date.

**Emails from orders**

Emails attached to orders are added like this:

```php
// Maybe add email address to customer record
if ( ! empty( $customer ) && $customer instanceof \EDD_Customer ) {
	$primary = ( $customer->email === $purchase_email );
	$customer->add_email( $purchase_email, $primary );
}
```

The tricky thing there is the customer `add_email()` method doesn't allow you to pass in `date_created`.

**Addresses from `_edd_user_address` user meta**
**Emails from `additional_email` customer meta**

Sadly there are simply no dates associated with these records. Perhaps at this point it's worth asking though if it would be better to use the customer's creation date rather than the migration date? It still wouldn't be accurate (the email/address could have been added days/weeks/months after the customer) but it might be slightly _more_ accurate than the migration date?

**Comment by spencerfinnell** [comment]
@ashleyfae Would that result in `date_created` being the date the Customer was created and `date_modified` be the date of the migration? I think that's reasonable for `_edd_user_address` and `additional_email` data.

**Comment by robincornett** [comment]
If it is possible to use an existing [order] date, I would vote for that, and the customer creation date seems like a reasonable fallback--makes more sense than the migration date.

**Comment by ashleyfae** [comment]
> @ashleyfae Would that result in `date_created` being the date the Customer was created and `date_modified` be the date of the migration? I think that's reasonable for `_edd_user_address` and `additional_email` data.

Yes that's exactly right.

**Comment by robincornett** [comment]
I poked at this some and adding:

```php
'date_created' => $date_completed,
```

to the `$order_address_data` (to update the physical addresses) and then updating the email adding functionality to this:

```php
		if ( ! empty( $customer ) && $customer instanceof \EDD_Customer ) {
			$type = ( $customer->email === $purchase_email ) ? 'primary' : 'secondary';
			edd_add_customer_email_address(
				array(
					'customer_id'  => $customer_id,
					'date_created' => $date_completed,
					'email'        => $purchase_email,
					'type'         => $type,
				)
			);
		}
```
seems to have worked. I do have some email addresses (all secondary, it seems) with the migration date, but the physical addresses and most of the email addresses do have earlier dates. Does this seem like a reasonable approach?
