### ISSUE TITLE
3.0 - Customer report screen may be incorrect

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7921]
### Expected behavior
I expect I should understand what the numbers mean for a report when I'm looking at it.

### Actual behavior
I don't really understand the tiles for the Customer reports, and I don't think some of the numbers are accurate. Example:

![image](https://user-images.githubusercontent.com/4853066/82089217-36c5ab00-96c1-11ea-8005-98d76a5dc559.png)

The average number of orders is more than are in my test storefront. I am not sure what the average age number is supposed to be, so I can't tell if that's correct or weird. I will assume the other two numbers are correct, though.

### Steps to reproduce the behavior
1) In EDD 3.0 with quite a few orders/customers, visit Downloads > Reports > Customers.

### Information (if a specific version is affected):
PHP Version: any
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

**Comment by spencerfinnell** [comment]
"Average Number of Orders" is definitely the wrong number.

"Average Age" is a confusing name, and I'm not sure how helpful of a stat it is to know the average number of days it's been since all customers have been created? I don't really know what that means... I would vote to remove that one. @cklosowski Thoughts?

**Comment by cklosowski** [comment]
I think the `Average Age` could be beneficial but I think it's being calculated incorrectly. A customer who made their first purchase in 2015, but hasn't made another purchase, including renewals, should not really be considered an 'active' customer in my mind.

I would say we can ditch that as it isn't helpful and instead look to the future to find a way to calculate 'churn' or 'loyalty'.

As far as the 'Average Number of Orders` just probably needs a query tweak.

**Comment by spencerfinnell** [comment]
@LisaCee Reports are registered here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/reports.php

Let's remove `average_number_of_orders_per_customer`.

It appears that the `$function` variable is being set to something like `COUNT(id)` or `AVG(id)`, but later on is checked differently:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/01b5a139f52eb12dcc5ebc70f9a57090a6d26f52/includes/class-stats.php#L2101-L2103

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/01b5a139f52eb12dcc5ebc70f9a57090a6d26f52/includes/class-stats.php#L2117

Causing it to use the other query.

I don't think we need to assign `$function` and instead can just check the validity of `$this->query_vars['function']` and set the values we need in the SQL directly (which is already being done in the `AVG` SQL).

**Comment by LisaCee** [comment]
Do you want me to 
- Just remove the tile for now, keeping the function for later correction?
- Remove the tile and function?
- Try to fix the query?  :scream_cat:

**Comment by spencerfinnell** [comment]
@LisaCee Let's remove the tile and function. We'll have a record of it in Git if we need it, but since it's not outputting the right information right now anyway it's probably not going to be needed again.

The pieces of the query should all be there, it's mainly the logic that needs to be updated to the correct query is used. 

`var_dump( $function );` above

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/01b5a139f52eb12dcc5ebc70f9a57090a6d26f52/includes/class-stats.php#L2117

and you should see what's happening more clearly.
