### ISSUE TITLE
edd_has_user_purchased returns false if purchase before last 20 orders

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#7926]
### Expected behavior
When calling the `edd_has_user_purchased` function, you would expect _all_ customer/user purchases to be checked but because `edd_get_users_purchases` function is called and assumes the default number parameter (20), only the last 20 purchases will be checked. This means if the customer has purchased prior, this will return `false`. This can be easily fixed by adding `- 1` to the call for the second parameter.

### Actual behavior
Will miss purchases before the last 20.

**Comment by spencerfinnell** [comment]
3.0 checks for a larger purchase set: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/user-functions.php#L200

@davidsherlock For now you can filter `edd_get_users_purchases_args` to adjust the default amount of `20` when querying purchases for a specific user.

```php
add_filter( 'edd_get_users_purchases_args', function( $args ) {
  if ( isset( $args['user'] ) ) {
    $args['number'] = 9999;
  }

  return $args;
} );
```

Since this issue currently exists (and has existed) in the `2.9.x` branch which we are trying to keep to critical fixes only, and has been fixed in `release/3.0`, I'm going to close this.
