### ISSUE TITLE
3.0 - When a customer has refunded orders, the lifetime value is incorrect

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7947]
### Expected behavior
If a customer has multiple orders, and one has been refunded, I expect that order to not count as part of the customer's lifetime value (or basically, that the order and refund would be added together to make $0).

### Actual behavior
When I view a customer with two orders and one refund, the refund is calculated as part of the lifetime value, but not the original order, so the lifetime value is/can be negative. Example:

![image](https://user-images.githubusercontent.com/4853066/82476616-57fd1180-9a9c-11ea-9d97-6baa045c0f65.png)

### Steps to reproduce the behavior
1) In 3.0, create two orders for a customer.
2) Refund one order.
3) Visit the customer's details screen to see their lifetime value.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

**Comment by cklosowski** [comment]
This is likely due to a bunch of math that happens whenever we do these alterations to the customer record. Prior to 3.0, this was done to try and keep a 'transactional' based record of the total spent so any time a payment record was modified, it did the math to add or subtract from the customer record.

I'm not positive this is the most efficient use of our cycles anymore as it can cause things to get out of sync if there is a fatal error or some other external source doing unexpected modifications.

Since 3.0 allows a much easier way to 'sum' up queries and not have to do math in PHP, would it not be wiser to just do a couple of queries with `SUM` operators.

I'm thinking we could actually do this in one query now by just querying all orders for the customer (completed and refunded) and running a 'SUM` operation on the result set. That would result in us not having to keep the ledger up to date, and possibly drifting off.

**Comment by cklosowski** [comment]
Pre-3.0, the reason for this ledger was that it was painfully slow to get all purchases and refunds of a customer, and calculate their totals. It either took an ugly JOIN query to the meta table, or a nasty foreach loop to do the math, or some combination of the two.

**Comment by cklosowski** [comment]
@JJJ do you think this would be ideal, or should we remain this ledger style work. I feel like the addition of BerlinDB would be efficient enough to do these calculations, even on a large data set without issue.

**Comment by JJJ** [comment]
@cklosowski it's a good question.

If these values were being saved in (and subsequently queried from) an `edd_customermeta` value, it would not make much sense to maintain them in that way and I would agree with you without much hesitation.

But because the `edd_customers` database table already has columns for `purchase_value` and `purchase_count`, the single use case I can think of for maintaining those values going forward is using it for sorting & ordering customers by those values, and then reading from it without any additional query necessary anywhere that value is presented alongside any individual customer (like in the screenshot above, for example.)

Note, however, that the `purchase_value` and `purchase_count` columns are not part of any index, so it is possible that their effectiveness for my above use case is less optimized than it could be.

I suggest generating a ton of dummy data and profiling whether or not adding indexes to those columns would speed that up. (Imagine a "Top 5 Customers" widget or report - querying only `edd_customers` would always be more efficient than SUM'ing `edd_orders` and then needing to also query for customers afterwards with an `in` query.)

If we stopped supporting those columns, the simple ability to sort & orderby them in a customer query is made relatively more complex, requiring a JOIN against a subquery to SUM the totals of orders across all customers.

To me, this seems like a 3.0 bug/regression worth fixing before 3.0 is released. The values that @robincornett posted don't add up to what I would expect, which is `$28.00`.

Related: In Robin's screenshots, the original order number was `116` but the refund is `222-R`. I thought that refunds had the same order number as their parent order with with `-R` appended to it. I could be wrong, but if I'm not, I just wanted to make sure that change was intentional and not another different bug. (I.E. Perhaps the order number relationships being off could cause this miscalculation.)

**Comment by robincornett** [comment]
The refund numbers here are based off of the transaction ID (the order ID in the database). So that order was 116 with sequential numbering enabled, but the database/transaction ID of the original order is 222. My personal preference would be to somehow use the order ID pretty much everywhere, as it keeps the relationship clearer if you have a customized one, but since the transaction ID is displayed elsewhere, I guess I assumed it was intentional with refunds.

**Comment by cklosowski** [comment]
@jjj I don't want to stop supporting them. I think they are useful. What I want to stop is the 'ledgering' of just adding or subtracting when we make a change to an order status.

I'd rather just run the full recalcuation and store that calculated amount into the column, instead of doing these minor modifications to it's value.

**Comment by JJJ** [comment]
@cklosowski Ah! Yes. That is definitely super easy to do now, and would be totally worth it.

I'd probably write it as a public method on the Customer class, so that it can be called and added to hooks easily with `$this` as needed, and even be abstracted into a global function later.

**Comment by robincornett** [comment]
Looking through the EDD_Customer class, the calculations you are describing sound like the existing [`recalculate_stats`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-edd-customer.php#L766-L791) method, but maybe updating the class with a method to run that? That appears to be where the customer purchase value is checked/updated, but the only status check is `complete`.

Removing the status entirely, so that all statuses are checked, and then creating a method like this, and using it instead of directly calling for the $customer->purchase_value`:

```php
	public function get_lifetime_value() {
		$this->recalculate_stats();

		return $this->purchase_value;
	}
```

 _seems_ to work, but is that the direction you are thinking, @cklosowski? I would assume that the statuses need to be narrowed down to just `complete`, `refunded`, and `partially_refunded` maybe?

**Comment by cklosowski** [comment]
So this issue has pointed out something interesting that I think we need to decide what we're going to do going forward.

In 2.9.x, we never really fully recalculated stats whenever there were changes. We used `increment` and `decrement` methods to add or subtract from existing values for the customer.

We wrote tests around these functions, and they allowed for arbitrary modification of the customer's lifetime value and purchase count. With the new database structure, it no longer is a performance hit to just recalculate a customer's stats without much load on the server, and we've started using the `recalculate_stats` method to do this. However, this will not account for arbitrary modifications. The 2.9.x code didn't account for this either, but it would have been only run when using the `Recount Stats` tool on the customer, which is hardly used.

I would vote we remove all usages of `increment/decrement` stats, remove the tests for them as they are deprecated, and leave the deprecation notices that @robincornett  has added. We'll have to go through all the code to find the uses of them to use the `recalculate_stats` method.

**Comment by cklosowski** [comment]
@ashleyfae I'd love to get your opinion on this approach, avoiding arbitrary modifications to a customer's lifetime value and purchase count, in favor of always just calculating off the data in the database.

**Comment by JJJ** [comment]
Everything Chris says above makes sense to me.

* Keep an eye out for when customer values are recalculated
* Make sure it's not done multiple times in a row (needlessly recalculating the same value)
* Try to cluster the database _writes_ close together if the code allows for it (to avoid race conditions with _reading_ in between retrieval from database/cache)

**Comment by ashleyfae** [comment]
I'm definitely in favour of calculating the data from the database. The idea of allowing arbitrary modifications without a "source" seems really weird to me.

**Comment by cklosowski** [comment]
Perfect. @robincornett go ahead and remove those tests related to arbitrary modifications to the customer stats. And do a once over on the code for the plugin looking for places where we do directly increase/decrease the stats instead of just running the recalculate.
