### ISSUE TITLE
3.0 - Manual orders apply flat rate discounts for each product instead of per order

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7955]
### Expected behavior
When I add a discount to a manually created order, I expect it to be applied one time.

### Actual behavior
For flat rate discounts, the discount is applied to each item in the order instead of the entire order. This is different from the front end behavior. Percentage discounts appear to be fine.

### Steps to reproduce the behavior
1) Create a flat rate discount.
2) Create a new order and add a product to it.
3) Add the discount to the order.
4) Add another product to the order. The discount is doubled.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
Tested two orders--one front end and one admin/manual--with identical products and a $10 discount. Discount applied was $20 for the manual order, but $10 for the front end order.

**Comment by spencerfinnell** [comment]
To help keep parity we might want to look at extracting https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/cart/class-edd-cart.php#L627 from being cart-specific.

**Comment by spencerfinnell** [comment]
I have some progress in `issue/7955` that fixes _most_ standard calculations but I'm still working on a way to handle penny rounding errors (https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2757) in the AJAX calculations on the Orders screen.

**Comment by spencerfinnell** [comment]
#7993 is ready for some heavy testing.

The important thing is to test situations like the ones described in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2757#issuecomment-65323603 where the rounding can leave a cent that needs to be applied to an arbitrary item -- this should be tested on both the frontend and backend with the abstraction of some of the Cart Discount handling.

The extra cent might not always be applied to the same item when manually creating an order due to the handling of the calculations in individual AJAX requests but the Discount's total amount should still be applied across all items.

**Comment by spencerfinnell** [comment]
Bringing some discussion back here. In https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7993#issuecomment-644749135 I mentioned that showing `$10.00` as the applied Discount makes sense because even if not all can be used the Discount itself cannot be reused (in the sense of using the remaining $9.00).

I'm now wavering on that and especially unsure after observing that an entry in `edd_order_adjustments` gets added with the full `10.00` discount amount applied:

<img width="692" alt="Screen Shot 2020-06-16 at 10 46 45 AM" src="https://user-images.githubusercontent.com/491124/84789895-b72c4400-afbe-11ea-8e8c-78c644674c53.png">

It seems like that could potentially affect reports.

I'm not sure the best path forward that accounts for both UX and the saved data.

**Comment by robincornett** [comment]
@spencerfinnell a related question as I'm working on some `edd_order_adjustments` fixes myself. In 3.0, the `tax_rate` is applied to each order item for new orders, but currently, the `discount` is applied to the entire order. With the way you've been separating the discounts to display per item, should discounts be treated the same way?

**Comment by spencerfinnell** [comment]
Do we think there is merit in keeping the individual discount amount under each Order Item in the admin view still? Or should we stay consistent to the frontend in that regard, which just shows a single amount?

<img width="616" alt="Screen Shot 2020-06-16 at 11 58 46 AM" src="https://user-images.githubusercontent.com/491124/84798384-e34cc280-afc8-11ea-9be0-75f985a40097.png">

I'm not sure that without a "no discount due to exclusions" note somewhere it will ever be completely clear why a full discount amount isn't being applied.

**Comment by robincornett** [comment]
In the database, we are storing tax rates per item, but discounts per order. Should this be changed? That may help determine how we decide what to do in terms of displaying, both in the admin and in the front end.

Note: I think there is potential value in showing more information in the admin than we do on the front end, but if a discount cannot be applied, or can only partially be applied because of exclusions, it does seem like we should include a notice for the customer.

**Comment by ashleyfae** [comment]
> Do we think there is merit in keeping the individual discount amount under each Order Item in the admin view still? Or should we stay consistent to the frontend in that regard, which just shows a single amount?

I don't particularly feel like I need that per-order-item admin view.

**Comment by spencerfinnell** [comment]
Updated #7993 to:

- Remove individual discount amount under Order Items in the admin view
- Save the _applied discount amount_ when creating an Order (both contexts)
- Output the _applied discount amount_ when creating an Order (both contexts)
