### ISSUE TITLE
3.0 - Review tax rates data for order adjustments table

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8060]
### Expected behavior
I feel like data in the `edd_order_adjustments` table should be consistently stored, with some variations as needed.

### Actual behavior
The way that tax rates are stored in the `edd_order_adjustments` table feels inconsistent and incomplete:
- The only numeric data stored for tax rates is the rate amount itself (as `total`). The `subtotal` and `tax` amounts are left to the default.
- On migration, tax rates are applied to/stored with the order.
- On subsequent/new orders, tax rates are applied to each order item, regardless of whether the item is taxable or not.
- When reviewing the database table, because the `subtotal` and `tax` are empty, and the `total` is the same, regardless of item cost or taxability, there is no ready way to scan and differentiate between items in the order.
- Tax rates are the only order adjustment items with no `subtotal` stored.
- It seems that discounts and tax rates could be considered to be similar kinds of data adjustments, because neither apply to free items, and order items can be excluded from a discount or tax. Additionally, when processing a refund, discounts and taxes are both prorated to calculate the refund amount. However, discounts are applied to the order as a whole ([historical and accounting reasons](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8014#issuecomment-655160388)), while tax rates are applied to each item. Should tax rates be applied to the order as a whole instead?

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.4.2

Any other relevant information:
Related: #8012 (order adjustments in general, original issue), #8056 (fees). Opening this issue to more specifically discuss tax rates behavior.

**Comment by ashleyfae** [comment]
Honestly I don't love the adjustments table. It's frustratingly abstract and I find the columns confusing for what's actually in there (mostly talking about the subtotal / tax / total).

That being said, I think it works well enough for now, and we store enough information that we can change this later.

**Comment by robincornett** [comment]
@ashleyfae so should we go ahead and close this as a won't fix?

**Comment by ashleyfae** [comment]
I'll remove it from the milestone but we can leave the issue open for now for further consideration at a later date.

**Comment by ashleyfae** [comment]
Tax rates are also, confusingly, stored in `edd_ordermeta` with the key `tax_rate`. I think this is mostly duplicated data, but it's confusing to me at least.

**Comment by ashleyfae** [comment]
Here's my understanding of what we need to support:

1. Taxes on orders.
2. The ability for certain order items to be tax exempt.
3. The ability for fees to be tax exempt.

With that in mind, I think there's the simpler solution, and the more complicated solution.

## Simpler solution

- Set the _tax rate_ (percentage) at the `edd_orders` level.
- Each order item (`edd_order_items`) still records the `tax` _amount_ the way it does now. Add a new column for `tax_exempt` (or similar) to distinguish if an item is excluded from tax.
- Each order adjustment (`edd_order_adjustments`) also continues to record the `tax` _amount_ the way it does now. Possibly add a new column for `tax_exempt` or similar, mostly to support fees that are excluded from tax.

The main point being: tax rates (percentage) are removed from `edd_order_adjustments` and are instead applied to the entire order.

**This configuration means that you can only have one tax rate for an order.**

## More complicated solution

Essentially what we have now, which seems to be set up in a way to _potentially_ support different order items having different tax rates. This isn't something we actually support right now via the UI in any way, but database-wise it seems set up for that possibility.

---

Personally I have no desire to actually officially support different tax rates for different order items.

I was working on an extremely simple PR related to tax rates ( https://github.com/easydigitaldownloads/edd-recurring/pull/1373 ) and was checking my work on both EDD master and EDD3. Mostly I was just extremely frustrated how difficult it was to find the order's tax rate. (We don't actually display it in the order UI right now, which I'll make a separate issue for.)

Although I did originally punt this from 3.0, as it's starting to bug me again I'm wondering if we should actually discuss it and see if there's merit in making some changes.

**Comment by spencerfinnell** [comment]
I personally am on board with having a single rate per Order as well. If we are sticking to our core of _digital downloads_ it seems unlikely that those types of items would have differing tax rates. If for some reason that changes we could add a `tax_rate` column to `edd_order_items` in the future that is used if set. Similarly to how [Stripe takes `default_tax_rates` that can be overridden](https://stripe.com/docs/api/subscriptions/create#create_subscription-default_tax_rates). Or we could prevent mixed carts.

> Each order item (edd_order_items) still records the tax amount the way it does now. Add a new column for tax_exempt (or similar) to distinguish if an item is excluded from tax.

@ashleyfae If we are storing the _amount_ do we need an exempt column? Couldn't we determine it by the fact that the Order was created with a tax percent, but the amount on the Order Item is `0`?

**Comment by ashleyfae** [comment]
> @ashleyfae If we are storing the _amount_ do we need an exempt column? Couldn't we determine it by the fact that the Order was created with a tax percent, but the amount on the Order Item is `0`?

It's not really needed. The only reason I thought of including it is:

1. You can easily differentiate between an item in an order that's actually exempt from tax, versus an order that just so happened to have no tax rate.
2. If you end up with an order item with a `0.00` tax amount, the exempt column gives you a more explicit reason _why_ (from a debugging / support perspective).

Not totally needed.

**Comment by JJJ** [comment]
Tax rates and exemptions are unique attributes to specific types of adjustments, not applicable to all, and not really critical to the function of the application, so adding a new column addresses 1 confusing thing by adding another 1 for the rows where it does not matter.

What about a `tax_exempt` key in `order_itemmeta` and/or `order_item_adjustmentmeta`?

I'm not sure a dedicated column is necessary. Will it ever be helpful to query/sort/order-by a `tax_exempt` column if one existed?

Storing the `tax_rate` as a meta key was done as a similar convenience. It is not required. It could be guessed, inferred, queried from the `adjustments` table (assuming that adjustment hasn't been deleted) or otherwise calculated inversely.

Since we _can_ stash it at write-time, why not help our future selves out, was the original thinking.

**Comment by ashleyfae** [comment]
I'm not tied to the idea of having a `tax_exempt` column so if we don't think it will be helpful then I'm fine omitting it. But if we are going to include it then I want it one of our main tables and not meta. The whole point of 3.0 is to get things out of meta. IMO if we're using something in the core plugin, we should be making space for it in a table. I see meta as mostly being there for third party developers; I don't like using it internally.

**Comment by robincornett** [comment]
Part of my original reason for opening the issue is that with the columns we have, I don't feel that we are being consistent with how we store the data across the different types of adjustments. For example, on an order with two products, one of which has a discount applied:

![image](https://user-images.githubusercontent.com/4853066/100878984-dccbdd80-3478-11eb-872d-a7c14662b115.png)

The discount is 20%, but what shows in the table is the actual currency amount that was deducted from the order, and it's applied to the order as a whole (one unrelated question is if this is technically accurate, since I had restricted the discount to apply to only one of the items in the order...fees will be stored against **both the order item and the order**; should discounts as well?). The tax rate rows are for each item, and show the actual rate (percentage), rather than the currency amount that was collected. So I am wondering why we store the adjustment rate for taxes, but the end result for discounts.

Also noting that in this store (admittedly with minimal data as it's been reset about 100 times), the `tax` column shows `0.0000000000` for every row. How are we using this row?

**Comment by ashleyfae** [comment]
> So I am wondering why we store the adjustment rate for taxes, but the end result for discounts.

I don't know for sure. Maybe it was to potentially support multiple / compound tax rates? (Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5696) The final tax amount per item is logged in `edd_order_items`. The total tax can be calculated by adding all those up. The tax rate is stored in order meta, but the individual rate per order item is stored in adjustments. The only reason I can think of to have it there as opposed to within the order_item itself is if you need to support more than one rate per order item.

However, if we end up pulling tax rates out of adjustments and put them at the order level, then that would mean everything in the adjustments table would now be a flat dollar amount as opposed to a percentage. That would at least make things more consistent.

> Also noting that in this store (admittedly with minimal data as it's been reset about 100 times), the `tax` column shows `0.0000000000` for every row. How are we using this row?

My guess is it's there to accommodate fees that have taxes applied.

**Comment by ashleyfae** [comment]
I'm making a list to try to figure out what we absolutely **need** in terms of storage requirements. Let me know what I've missed.

## Discounts

Discounts can be applied to an individual item or the whole order.

- Required: the discount ID and discount code.
    - Reason: reporting discount code usage. (Most commonly used discount, etc.)
- Required: discount as a dollar amount at an order item level.
    - Reason: this is how we ultimately calculate the discount amounts (see `edd_get_item_discount_amount()`). Discounts can be applied to an individual item only, or if they are for the whole cart then they are still evenly distributed across all items, and each item gets a discount amount. Because this is how we calculate it, I feel it's important to record this in the database, sort of as evidence of our calculations.
- Nice to have: essentially a copied record of the discount code setting (percentage vs flat, and the actual percentage amount or flat dollar amount).
    - Reason: immutability. In case someone changes a discount code's settings.

## Fees

Fees can be applied to an individual item or the whole order.

- Required: the fee ID and label.
    - Reason: record keeping, potentially reporting one day. Label is required for display on receipts.
- Required: the fee amount. Fees can either be applied to an individual item, or can be applied to the whole order. This fits very nicely with the adjustments table because it perfectly fits the schema and support of adding to an entire order or to just one order item.
    - Reason: record keeping and for display on invoices/receipts.

## Taxes

Tax rate is set once for the entire order, but individual items/fees can be excluded.

- Required: the final tax dollar amount per item.
    - Reason: tax obligations and display on the invoice.
- Required: The tax rate as a percentage.
    - Reason: tax obligations to display on the invoice. I do not want to reverse calculate it from the dollar amount given the possible tax configurations (inclusive, exclusive, tax rates changing, etc.).
- Nice to have: whether or not an item / fee is tax exempt.
    - Reason: immutability and providing stronger clarity between an item that's actually tax exempt, versus an order that simply has no tax rate. Arguably, if this is included, then the final tax dollar amount per item may not be necessary because you can then calculate it based on this setting and the tax rate. So therefore you really NEED either this or final dollar amount, or it's NICE to have both.

**Comment by JJJ** [comment]
> I'm making a list to try to figure out what we absolutely need in terms of storage requirements

The idea/goal with the Adjustments API in EDD3.0 was _not_ to design a highly optimized database table/schema that worked perfectly for everything that EDD already came with.

As @sunnyratilal and I architected every custom storage solution for the various first-class EDD Objects, the pattern emerged that became the Adjustments API because those Objects had so much in common with how their database schemas would ultimately look had they all been separate Object/Meta pairs of dedicated tables.

(What they did not have in common was what they _did_ with the data, and thankfully all that can be handled in PHP.)

The Adjustments API is akin to the Custom Post Type API. Its strength is not perfectly matching the shape of the data object in PHP. Instead, it comes from being highly flexible and adaptable to fit the 90% overlap between highly similar Object attributes.

> Let me know what I've missed

I'd love to, but I honestly do not think that I am physically able to. It's been 2 years since I've had all of EDD front loaded in my head. I would need to re-audit every database column and Object attribute side-by-side to identify any chads that need trimming. I am willing to help, but I question whether it's necessary, especially when releasing 3.0 is trying to get closer, not farther away.

Specific to the concerns raised in this issue so far, I'm having a hard time understanding and following them all in unison, and it reads to me like many different solutions trying to point at a single database schema _problem_ that exists _by design_.

All of EDD has been shoe-horned into meta-data for almost a decade, and for most installations that's never been a bother for them. The majority of EDD sites don't mess about with taxes. The ones that do just need a place to manage a few rates at a time. The outliers are the people who go digging into the database to mess with values.

Is 3.0 somehow worse than 2.x, or is it improved enough to revisit later?

**Comment by ashleyfae** [comment]
I think I'm decided that I want to move tax rates now. I'm happy with discounts and fees because I think they work and make sense. Taxes feel like the odd one out and suffer from a lack of clarity that makes it frustrating to deal with. Originally I proposed we address it later but I think my mind is changed.

So ultimately the main change I propose is moving the _tax rate percentage_ to the orders table.
And, optionally, the introduction of `tax_exempt` columns.

I don't feel this is a massive refactor of how adjustments work and won't seriously impact the 3.0 timeline.

**Comment by davidsherlock** [comment]
Being able to set the tax rates on a per-item basis, is paramount to my "Product Taxes" plugin, that being said storing the actual rate is not a strict requirement per-say (though useful to have when going back through transactional data). As long as the filter exists to manually change the tax amount within the cart items, that should be sufficient.

**Comment by ashleyfae** [comment]
> Being able to set the tax rates on a per-item basis, is paramount to my "Product Taxes" plugin, that being said storing the actual rate is not a strict requirement per-say (though useful to have when going back through transactional data). As long as the filter exists to manually change the tax amount within the cart items, that should be sufficient.

Existing filters in place wouldn't change. The tax _amount_ would still be stored individually with each order item, which theoretically would make it possible to have that set to something that doesn't obey the order-level percentage.

In core I only want one single tax rate. But the filters and storage we have in place should allow another plugin to change that behaviour.

**Comment by ashleyfae** [comment]
Thank you to @robincornett for reminding me that we do not allow tax rates to be edited, and therefore we can actually save the tax rate ID in `edd_orders` rather than the percentage.

**Comment by robincornett** [comment]
I think having the tax rate associated with the order itself makes sense to me, and removes what I perceive as inconsistent data from the adjustments table--and Ashley pointed out:

>So given that the [tax rate] information is all the same anyway, we can move the same data to orders and only store it once instead of potentially 5 times per order, if there are 5 order items.
>And that also removes all percentages from adjustments, so now adjustments only consists of dollar amounts, which fixes that inconsistency.

Scanning my own database order_adjustments table, I'm also noting that the `tax_rate` `type_id` is actually not being stored, at least not for migrated orders, and I think that's not correct.

**Comment by ashleyfae** [comment]
Just noting this down to ensure it's addressed:

In 2.9, it looks like tax rates are stored in `_edd_payment_tax_rate` meta as a decimal (e.g. `0.2` for 20%).

In 3.0, they're stored in adjustments as `20.000000000`.

However, this isn't getting converted in the migrator. (We should be getting the old tax rate and multiplying by `100` to make the data match.)
