### ISSUE TITLE
3.0 - Order credits & fees are not managed correctly with refunds

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8075]
### Expected behavior
When I refund a manually added order which includes a credit, I expect the refund total to match the original order total.

### Actual behavior
When I refund a manually added order which includes a credit, the refund total does not match ([ref](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8069#issuecomment-665744426)).

### Steps to reproduce the behavior
1) Generate a manual order and apply a credit.
2) Refund the order.
3) Compare the original order subtotal/total amounts in the database with the refund order subtotal/total amounts.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.4.2

**Comment by spencerfinnell** [comment]
Illustrating what can happen:

<img width="799" alt="Screen Shot 2020-07-29 at 12 09 20 PM" src="https://user-images.githubusercontent.com/491124/88824733-baf1df80-d194-11ea-9a86-6c578fd68167.png">
<img width="992" alt="Screen Shot 2020-07-29 at 12 09 28 PM" src="https://user-images.githubusercontent.com/491124/88824746-bd543980-d194-11ea-8a85-0f7193b8272b.png">

I originally added the `credit` type to the "Add Adjustment" flow because it existed in the original UI, but I'm not sure if handling of that adjustment type was fully fleshed out, especially with refunds. I believe only the Fees API is used in things like EDD Wallet?

At this point in time I believe removing Credits from the manual Order creation flow to be implemented more fully at a later date might be the best path forward.

**Comment by ashleyfae** [comment]
Copying from https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8203, which was about fees, but are ultimately the same as credits anyway:

## Bug Report
### Expected behavior

I expect to be able to issue a **full** refund, including any fees that were on the order.

### Actual behavior

Fees are not shown in the "Submit Refund" modal, which means you can never select them for refund, which means the most you can ever refund is the total **without** fees. It's impossible to truly do a full refund.

I manually created an order and applied a $50 fee to the whole order.

![Screenshot from 2020-11-11 13-40-55](https://user-images.githubusercontent.com/6324272/98818690-cefbdd00-2423-11eb-955b-080e1fddaa60.png)

The refund modal does not show this fee at all.

![Screenshot from 2020-11-11 13-41-07](https://user-images.githubusercontent.com/6324272/98818712-d4f1be00-2423-11eb-957a-dba91629992f.png)

And in the refund UI you can see the total is without the fee:

![Screenshot from 2020-11-11 13-41-35](https://user-images.githubusercontent.com/6324272/98818725-d9b67200-2423-11eb-954a-48bc5585a9a2.png)


### Steps to reproduce the behavior
1) Manually create a new order and add fees to the order. (Either to the whole order or a specific product.)
2) After saving the order, click `Initialize Refund`.
3) Fees do not appear to select in the modal.

---

Would be nice if we can get this working in at least a bare minimum state for 3.0. Maybe that means if you refund an order item, you **have** to also refund the fee attached to that item; you don't get an option. We can expand on it more later.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8075

**Comment by robincornett** [comment]
Noting after a conversation with Ashley last week about refunds in general: as I understand it, we need to also provide a way to add a free form adjustment to a refund--to allow a partial refund which is not tied to a specific order item (not returning it). The way [we recommend handling this in 2.x](https://docs.easydigitaldownloads.com/article/1068-how-do-i-process-refunds) won't be allowed in 3.0, as I understand it.

If we could add an adjustment where the admin can enter the amount of the adjustment, it would allow this to happen, and could include a description. We do have something like this set up already for adding fees to a manually created order: a fee can be applied to the entire order, or just one item in the order, and can include a description. This would be an improvement over 2.x, as it creates a paper trail of sorts.

If we implement this, there needs to be a final check added (if it doesn't exist already) to make sure the amount refunded is never more than the original amount charged.
