### ISSUE TITLE
Verify download_id is present in add to cart call before using it.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#8319]
### Expected behavior
When adding to the cart via ajax, a notice should not be generated if the download id is missing.

### Actual behavior
When adding to the cart via ajax, a notice is generated if the download id is missing.

### Steps to reproduce the behavior
1) Trigger the EDD add to cart admin-ajax.php call but do not include a download ID.
2) Notice the PHP notice logged.

### Information (if a specific version is affected):
PHP Version: Reported on PHP 7.4 and 8.0 but likely others.

EDD Version (or branch): latest 2.9.x

WordPress Version: All

Any other relevant information:
Reported here: https://wordpress.org/support/topic/lots-of-php-notices-7/#post-13940284

**Comment by cklosowski** [comment]
@LisaCee can you get this fixed up for the 2.10 release?

**Comment by LisaCee** [comment]
@cklosowski It looks like this has already been accounted for in 2.10 [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/fc1e3eb0685d4c094640468282e916a4f4786033/includes/cart/actions.php#L67).  The fix is slightly different from the users suggestion, but it should do the same thing.  Let me know if more is needed.

**Comment by cklosowski** [comment]
Perfect! Thanks for checking @LisaCee sorry about that.

Noted the fix was in #8181
