### ISSUE TITLE
EDD All Access Pass duration not synch with recurring payments

### ISSUE THREAD

**Issue by francescomiano** [easydigitaldownloads/easy-digital-downloads#8327]
Hi there!
EDD All access pass duration is not synch with recurring expiration (also if in the download page of the all access pass product is set to ” synch with recurring expiration” . Means after 1 month, the subscription status is active (and recurring payment on paypal is running ok) but the All access pass is expired.

Do you have any idea on how to sort this out?

All Access pass Version 1.1.4
EDD version 2.9.26
Recurring payments version 2.9.11

Many thanks for your support!

**Comment by mihaijoldis** [comment]
Hey @francescomiano 
I saw the same question posted on the .org forums. I sent a reply there so please try that first. Most likely you need to configure IPN notifications so that the recurring payments from PayPal will be sent to EDD which in turn will renew the pass.

Documentation for PayPal Standard IPN can be found here https://docs.easydigitaldownloads.com/article/918-paypal-standard#ipn
