### ISSUE TITLE
3.0 – Uncaught Error: Unknown named parameter $endpoint in class-table-endpoint.php on line 217

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8358]
### Expected behavior
When viewing the reports, I expect to not get a fatal error :-) This may still be in progress though, so mentioning it...

### Actual behavior
When clicking on "Downloads" or "Payment Gates" I get the above error.

**Comment by ashleyfae** [comment]
@davidsherlock Are you using PHP 8?

**Comment by davidsherlock** [comment]
@ashleyfae yes I am, the error does not occur on PHP 7.4.

**Comment by ashleyfae** [comment]
The issue is using an associative array here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/reports/data/class-table-endpoint.php#L214-L218

Pretty sure in version less than 8, that just ends up being passed as `array_values()` anyway (the keys not actually being relevant). But in 8.0, using an associative array properly uses named arguments.
