### ISSUE TITLE
3.0 – Disallow empty tax rates in table

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8401]
### Expected behavior
When I add an empty tax rate, it should not add to the table.

### Actual behavior
An empty row is added to the table.

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): latest beta

WordPress Version: 5.7

**Comment by ashleyfae** [comment]
@LisaCee We should do two things here:

1. Update the JavaScript to prevent the tax rate from being added to the table if the "Rate" is empty.
2. Update the PHP to skip saving a tax rate entirely if the rate is empty.

PHP saving is here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/settings/register-settings.php#L1455-L1504

JavaScript is here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/settings/tax-rates/views/table-add.js#L154-L185

While we're add it, let's also add the same checks if the country is empty, because we also shouldn't be saving empty countries.

**Comment by LisaCee** [comment]
PR #8419
