### ISSUE TITLE
3.0 - Order item meta arrays incorrectly stored as strings

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8422]
### Expected behavior

When I filter cart details to add additional data, I expect it to be stored and retrievable in the same way as EDD 2.9. I have a feeling Recurring Payments will also be impacted by this.

### Actual behavior
Using the following code, I needed to add additional cart details for purchased items (similar to Recurring Payments). I have omitted price ID specific code/functions:

```
function ds_add_cart_details( $cart_item ) {

  $download_id = $cart_item[ 'id' ];
  $price_id    = isset( $cart_item[ 'options' ][ 'price_id' ] ) ? intval( $cart_item[ 'options' ][ 'price_id' ] ) : null;

  if ( edd_has_variable_prices( $download_id ) && ( ! empty( $price_id ) || 0 === (int) $price_id ) ) {

    // Add the adjustment info for a variable price
    $cart_item[ 'options' ][ 'market_freeze' ] = array(
      'post_id' => $this->post_id,
    );

  } else {

    // Add the adjustment info for a variable price
    $cart_item[ 'options' ][ 'market_freeze' ] = array(
      'post_id' => $this->post_id,
    );

  }

  return $cart_item;
}
add_filter( 'edd_add_to_cart_item', 'ds_add_cart_details', 10, 1 );
```

When the data is stored in meta, it is stored like this:

`s:27:"a:1:{s:7:"post_id";i:2291;}";`

The same applies when I don't use an array, just add an ID for example.

### Steps to reproduce the behavior
1) See code above.

**Comment by robincornett** [comment]
Confirmed. Recurring item meta looks like this in the database:

```
s:93:"a:4:{s:6:"period";s:5:"month";s:5:"times";i:0;s:10:"signup_fee";i:0;s:12:"trial_period";b:0;}";
```

(Meta key is `_option_recurring`.)

If I comment out [these lines](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/orders/functions/orders.php#L961-L963), then the meta does appear to be correctly saved:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/677d4f2187938bea4a1680422a84dfd7ff908420/includes/orders/functions/orders.php#L961-L963

```
a:4:{s:6:"period";s:5:"month";s:5:"times";i:0;s:10:"signup_fee";i:0;s:12:"trial_period";b:0;}
```

Migrated orders are the same (string instead of an array)...looks like the [data migrator also calls `maybe_serialize`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L912-L914).

**Comment by davidsherlock** [comment]
Yep, we are good now.
