### ISSUE TITLE
Subscription search by name

### ISSUE THREAD

**Issue by shaynesanderson** [easydigitaldownloads/easy-digital-downloads#8490]
## Enhancement Request
When searching in Downloads-->Subscriptions it appears that only the download name returns results as well as the options available such as "id:", etc. 

It would be helpful to search subscriptions by customer name.

**Comment by ashleyfae** [comment]
@shaynesanderson Customer _email_ search is supported. All you have to do is enter an email address. Would that work for you?

Closing this because it actually is a Recurring issue and I'm unable to transfer the issue there. But if you'd like to specifically bring up searching by customer name then feel free to open a new issue in the Recurring repo. :+1:

**Comment by shaynesanderson** [comment]
Thanks @ashleyfae and DOH, I wasn't thinking about Recurring/subscriptions. My mistake!
