### ISSUE TITLE
3.0 - what should happen with downloads which have been partially refunded?

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8539]
Here is a question about partial refunds: what should a partial refund _mean_ in terms of access to download files, etc.? Should the download files still be available? Right now, they're not, and things are not completely consistent. Here's some things I noticed:

- In the order details screen (admin), the "Copy Download Links" button is missing for a partially refunded download.
- In the customer view of the receipt/payment confirmation, the download file is not available.
- In the purchase history view, a fully refunded order says "Refunded" and there is no link to view the details/downloads (should a user still be able to see the details of a refunded payment? It seems like they should?).
- In the purchase history view, a partially refunded order looks like any other order and shows the links to view details/downloads, but when clicking that link, it shows that the order status is refunded, but not the status of the individual items (something to consider updating in #8508)

_Originally posted by @robincornett in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8284#issuecomment-811871124_

I posted the above in testing partial refunds, but wanted to move it to its own issue. With partial refunds, we need to decide what should still be available to customers--should the download files still be available or not?

Should a customer still be able to view the details of a refunded/partially refunded order? I feel like the answer there is yes to both, even if download files are not available? And I do think partially refunded items (or if one item in an order is refunded), the receipt/confirmation screen should show specifically which have been affected.

**Comment by LisaCee** [comment]
> Should a customer still be able to view the details of a refunded/partially refunded order? I feel like the answer there is yes to both, even if download files are not available? And I do think partially refunded items (or if one item in an order is refunded), the receipt/confirmation screen should show specifically which have been affected.

I 100% agree with your suggestions.  
- A receipt should always be available (this may have more to do with the `[purchase_history]` than refunds)
- If an order is partially refunded, unaffected items should still have a link to the download
- If an order with quantities is partially refunded (1 of 2 qty refunded) they should still have a link to the download

As for partially refunded items, that's a bit more complicated.  Ideally, I'd like to give the store the option to have a download available or not, either store-wide or per order, but that sounds like it could be really challenging to add to our current refund system.  As a quicker fix, I tend to think we should err on the side of customer: if they paid for a download and it wasn't fully refunded, they should still have access.  It seems like that would catch more edge cases so that people don't accidentally lose access to something they should have.  I'm still thinking this through, though.

**Comment by kerijacoby** [comment]
I'll try to answer some of the questions above from a support perspective :)

I'll start by saying there are typically two types of partial refunds:
1. A partial refund for a price adjustment (Customer forgot to enter a discount code at checkout.) 
2. A partial refund because one or more products from the entire order were removed, but not not all.

If an item from an order is partially refunded the item should still be available for download. The partial refund was likely issued because of a price adjustment, scenario 1.
If a single item from a multiple item order was fully refunded, thus making the full order partially refunded, I feel as though the fully refunded single item should no longer be available for download, scenario 2.

In both cases I feel as though a detailed receipt should always be available. Customers do request receipts from us that show an item was purchased and then refunded. It's not as though the purchase never happened, it's just changed.

Current State
If a partial refund is issued for a price adjustment, the total is updated for the order/item within EDD and the partial refunded is issued directly from the gateway that was used.

If a partial refund is issued because one or more products is removed from an order we have to delete those items from the order and then issue the partial refund from the gateway. As you might imagine this presents a problem with receipts.
