### ISSUE TITLE
3.0 - edd_get_payment_fees is no longer consistent with 2.x

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8554]
### Expected behavior
When I use `edd_get_payment_fees( $payment->ID, 'item' )` (in the shortcode receipt template), I expect it to work the same way it does in 2.x.

### Actual behavior
No fees on order items are returned.

### Steps to reproduce the behavior
1. Make sure you have an order with fees which are tied to a specific product, so that the fee has `order_item` as the `object_type` in the database.
2. View the order receipt.
3. The fee is displayed in the general payment information part of the template, and [no fees are returned for the last section](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/templates/shortcode-receipt.php#L257) of the items table.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.7

Any other relevant information:
I believe that the intention is to display order level fees in the payment part of the receipt, and order item level fees with the related products. However, there is order item level logic in the upper part of the receipt--so if my understanding is correct, the receipt needs to be revised to either remove the order item fees section from the end, or remove the order item fees logic from the first part. This is really an issue we need to resolve in the PR for #8508.

However, the real issue with `edd_get_payment_fees` is that the `EDD_Payment` class is [setting the fee type for all order fees to `fee`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L629). I think it's really supposed to be the `$order_fee->object_type` instead, as the payments class is, I believe, expecting the type to be something like `item`. Note that even just properly setting the `object_type` as the fee type won't fix the backwards compatibility problem, because the 2.x usage of the function is to use `item`, and the `object_type` in 3.0 will be `order_item` instead. So we need to fix the array values, but also decide where exactly the `order_item`/`item` conversion needs to happen.

**Comment by ashleyfae** [comment]
After looking into this, I don't think the `item` type is meant to be equated to `order_item` fees.

In order to get an `item` fee, you have to explicitly set `'type' => 'item'` when adding the fee. However, you cannot have an `item` fee that is assigned to a specific download. This is specifically in there:

```php
// If the fee is for an "item" but we passed in a download id
if( 'item' === $args['type'] && ! empty( $args['download_id'] ) ) {
	unset( $args['download_id'] );
	unset( $args['price_id'] );
}
```

That essentially means that all `'item'` fees are always `order` fees (entire order; not order items).

Also, [in the docs](https://docs.easydigitaldownloads.com/article/543-edd-fees), it says:

> This is a fee that is not associated with anything else, think of it like a temporary product made up on the spot. Currently used for Wallet deposits for example.

Here's where fee types were originally introduced: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/1956#issuecomment-43164908 I linked to the comment where they started talking about it.

So an `item` fee is really meant to be more of an actual product (like a dynamic product made up on the spot).

However, I think this is a more deeply rooted issue. For example, we have no handling for fee types in the migrator, so any `item` fees end up getting converted just to `fee`.

I need to spend more time thinking about this but I am inclined to drop support for `item` fee types. I don't see a big enough difference between the description of that and just a normal order fee that's not attached to an order item.
