### ISSUE TITLE
Weird  behaviour on checkout page 

### ISSUE THREAD

**Issue by rohitp-bsf** [easydigitaldownloads/easy-digital-downloads#8644]
# Instructions (START):
 - I have setup my store with EDD but on checkout, there are two payment gateways Stripe and Paypal Express, by clicking on any it doing an Ajax Call and refreshes the DOM with a new template always.

- I debugged a code and I got a filter `edd_is_ajax_disabled` to which I disabled but checkout does not work anymore.
# Instructions (END):
- Is there any way to setup checkout without any AJAX call.

### Expected behavior
- It should not do an ajax call to fetch payment gateway templates.

### Actual behavior
- Ajax call happening always with the click of the payment gateway.

EDD Version (or branch): Latest

**Comment by ashleyfae** [comment]
Sorry but an ajax call is pretty much required here, because the two templates have different checkout requirements.

`edd_is_ajax_disabled` is kind of deprecated-esque. See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4758 The function is still in use in a few places, but the plan is to continue phasing it out. 

If you have any further questions you can contact our support team here: https://easydigitaldownloads.com/support/
