### ISSUE TITLE
3.0 - Migration - Migrated order totals don't include fees

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8671]
### Expected behavior

I expect the order total to be all order items + fees.

### Actual behavior

Fees are not being considered.

![Screenshot from 2021-05-29 10-09-34](https://user-images.githubusercontent.com/6324272/120064797-09e2fc80-c066-11eb-9c5a-dc948bf8140b.png)

The total should be $25.

### Steps to reproduce the behavior
1) Start in EDD 2.10 (master).
2) Have an order that contains a fee. In the above example it was an order fee, but we should also test order item fees.
3) Checkout release/3.0 and migrate.
4) Note the order total.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
It looks like order item level fees are migrating correctly (tested with Discounts Pro and Simple Shipping). But I manually created an order level fee and although it's showing in the database, it's not included in the order total.

I think this is maybe related to #8643 somewhat--I was thinking about that one some more and although I understand that the order needs to be created first, it seems like the order adjustments that modify the order information need to maybe update the order as well. I tinkered with that some in that PR with getting/calculating discounts before adding the order to the database, but wondering if the migrator needs to be running `edd_update_order` for things like fees (at least for the order level ones).

In this screenshot:

![image](https://user-images.githubusercontent.com/4853066/120339400-1748f280-c2c3-11eb-884b-59e3eb7b8ecc.png)

The discount is from Discounts Pro (and an `order_item` fee) and the Processing Fee is the manually added `order` fee. (Noting also that the negative fee isn't showing that it's negative?)

**Comment by robincornett** [comment]
Also: I'm looking at some old orders where renewal discounts were stored as fees and I'm thinking we have some serialization issues, or nesting, potentially?

```
$meta = get_post_custom( 96602 );
var_dump( $meta['_edd_payment_meta'] );
// result of var_dump:
Array
(
    [0] => a:7:{s:8:"currency";s:3:"usd";s:9:"downloads";s:111:"a:1:{i:0;a:3:{s:2:"id";s:5:"27451";s:7:"options";a:1:{s:8:"price_id";s:1:"2";}s:8:"quantity";i:1;}}";s:9:"user_info";s:341:"a:6:{s:2:"id";i:2794;s:5:"email";s:13:"joe@example.com";s:10:"first_name";s:4:"Joe";s:9:"last_name";s:5:"Sample";s:8:"discount";s:4:"none";s:7:"address";a:6:{removed}}";s:12:"cart_details";s:273:"a:1:{i:0;a:6:{s:4:"name";s:24:"PayPal Adaptive Payments";s:2:"id";s:5:"27451";s:11:"item_number";a:3:{s:2:"id";s:5:"27451";s:7:"options";a:1:{s:8:"price_id";s:1:"2";}s:8:"quantity";i:1;}s:5:"price";s:3:"123";s:8:"quantity";i:1;s:3:"tax";i:0;}}";s:3:"tax";s:1:"0";s:4:"fees";a:1:{s:14:"edd_sl_renewal";a:2:{s:6:"amount";s:6:"-24.60";s:5:"label";s:24:"License Renewal Discount";}}
)
```

**Comment by spencerfinnell** [comment]
I'm not as familiar with the migrator so there might be a reason I don't know about as to why this happens, but why is the total amount being recalculated instead of using `_edd_payment_total` metadata directly?

If that's not always available it still seems like trying to use that value first would make sense.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L463-L487

**Comment by robincornett** [comment]
I asked this as well as @ashleyfae and I are experiencing conflicts with what the cart details are actually showing. Her response:

> I'm in two minds about it. This is a nice opportunity to recalculate to ensure data validity. We might also be fixing a few calculation errors in the process. Like I recall one issue some time ago about fees accidentally screwing up order totals or subtotals or something. So that benefit is nice.
> But when we have old issues like this.... yeah, using the provided total would be easier.

**Comment by ashleyfae** [comment]
Yeah I think I'm leaning towards just using the provided one if available. If it's not available then we can recalculate.

**Comment by spencerfinnell** [comment]
Noting the comment in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8647#issuecomment-852097713 might also affect/adjust the calculations done if the `_edd_payment_total` meta does not exist.

**Comment by ashleyfae** [comment]
Our main goal at this point should be no regressions in order totals from what's currently in master (2.x).

- Fixing bugs is okay.
- Continuing to have errors in 3.0 when that same error exists in 2.x is okay.

**Comment by spencerfinnell** [comment]
PR #8675 adjusts the priority of data for `_edd_payment_tax` and `_edd_payment_total`. Previously these values were only used as a fallback when cart data was unable to be retrieved. Now these values -- the source of truth in 2.x -- serve as the primary source of truth during the migration, if available. If they are not available then recalculation attempts are made with the cart details.

The PR also adds support for Fees when manual calculations are needed. The tracking and final adjustment of the Order looks a little wonky because of how the original data is stored when Order and Order Item Fees are involved.

When an Order Item fee is used the fee amount is added to the cart item details `price`, which includes the base Download price plus tax. Because of this we need to track just the tax amount for Order Item Fees to add to the adjusted total at the end.

When an Order fee is used the fee amount is not calculated in the original Order total. We must track the Order Fee tax and total to manually adjust the Order tax and total if required.

To test:

1. Create a Download on `master` that includes Taxes, Order Fee, and Order Item Fees:

```
function add_handling_fee() {
	EDD()->fees->add_fee( '10', 'Handling Fee', 'handling_fee' );

	EDD()->fees->add_fee( array(
		'amount' => 12,
		'download_id' => 9,
	) );
}
add_action( 'init', 'add_handling_fee' );
```

2. Purchase the Download.
3. Switch to `issue/8671` and run the migration.

- Observe the Order total in `wp_edd_orders` equals what was shown on the payment confirmation page
- Observe the Order tax in `wp_edd_orders` equals what was shown on the payment confirmation page

---

1. Create a Download on `master` that includes Taxes, Order Fee, and Order Item Fees:

```
function add_handling_fee() {
	EDD()->fees->add_fee( '10', 'Handling Fee', 'handling_fee' );

	EDD()->fees->add_fee( array(
		'amount' => 12,
		'download_id' => 9,
	) );
}
add_action( 'init', 'add_handling_fee' );
```

2. Purchase the Download.
3. Delete `_edd_payment_total` and `_edd_payment_tax` from the payment's metadata in `wp_postmeta`
4. Switch to `issue/8671` and run the migration.

- Observe the Order total in `wp_edd_orders` equals what was shown on the payment confirmation page
- Observe the Order tax in `wp_edd_orders` equals what was shown on the payment confirmation page
