### ISSUE TITLE
3.0 - No hook is fired after discount is added from admin

### ISSUE THREAD

**Issue by dimadin** [easydigitaldownloads/easy-digital-downloads#8718]
### Expected behavior
When I  create a new discount in the admin, I expect that custom fields are saved too.

### Actual behavior
`edd_add_discount()` function, that is used to create a discount, does not have any hooks. This is different behaviour from function `edd_update_discount()` that is used when discount is edited in admin, which has hooks so submitted value can be saved.

### Steps to reproduce the behavior
1) Add custom field to Add Discount screen.
2) Save discount.
3) Value of custom field is not saved.

### Information (if a specific version is affected):

EDD branch:
`release/3.0`

**Comment by robincornett** [comment]
Related: #8683 

Looking at what's available in the BerlinDB files, could we maybe add a hook or two (pre/post) inside of the `add_item` method ([ref](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/database/engine/class-query.php#L1707)), maybe right before returning the `$result`?

When I add a discount, the transition hooks that are fired are:
- edd_transition_adjustment_parent
- edd_transition_adjustment_status
- edd_transition_adjustment_type
- edd_transition_adjustment_scope
- edd_transition_adjustment_amount_type

None of these quite _feel_ like something I would naturally assume to hook into when creating a discount.

**Comment by davidsherlock** [comment]
We do not want to depend on the transition hooks, since they do not apply to all objects within BerlinDB/EDD context. It would better if actual pre and post actions were built at BerlinDB level for the different objects and then we could use them for whenever

**Comment by ashleyfae** [comment]
For the scope of this issue, let's focus on discounts only. The missing hook in question is `edd_post_insert_discount`. I believe that's the one that used to fire, but isn't currently firing.

Pretty sure the problem is that it's now triggering in `edd_store_discount()`, but when you add a discount in the admin area that uses `edd_add_discount()`, and that does not fire the hook.

The tricky thing is that the hook expects arguments in the 2.10 format, and the ones used in `edd_add_discount()` are in the new format.
