### ISSUE TITLE
3.0 - EDD_Payments_Stats methods are returning unexpected results

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8727]
### Expected behavior
When I use the `EDD_Payments_Stats` methods, I expect it to return correct data.

### Actual behavior
When I use the `get_stats` and `get_earnings` methods, the data is incorrect.

### Steps to reproduce the behavior
1. In EDD 3.0, enable the EDD Email Reports plugin.
2. Preview an email report email.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.7.2

Any other relevant information:
Two of the functions that plugin has use the `EDD_Payments_Stats` class like this:

```php
/**
 * Returns the total earnings for today.
 *
 * @return string
 */
function edd_email_reports_daily_total() {
	$stats = new EDD_Payment_Stats();

	return edd_format_amount( $stats->get_earnings( 0, 'today', false ) );
}

/**
 * Returns the number of transactions for today.
 *
 * @return int
 */
function edd_email_reports_daily_transactions() {
	$stats = new EDD_Payment_Stats();

	return $stats->get_sales( false, 'today' );
}
```

There are others, but they're similar.

The second one is returning the total number of completed payments for the entire storefront; the first is returning `$0` (same for each total function in the plugin), even though it should not be.

**Comment by ashleyfae** [comment]
The problem is that the date condition is missing when `$download_id` is empty.

EDD 2.10.6 adds a WHERE clause with the dates before running `edd_count_payments()` https://github.com/easydigitaldownloads/easy-digital-downloads/blob/2.10.6/includes/payments/class-payment-stats.php#L52 That ensures the date condition is added.

EDD 3.0 is missing the date clauses completely: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-payment-stats.php#L57-L65
